// Person-first language library and detection helpers.
// Used by:
//  - IRIS generation prompts (server-side, injected into every system prompt)
//  - Real-time writer flag (client-side, scans textareas as people type)
//  - Score Me scoring engine (server-side, scored dimension)
//
// This is non-negotiable for Medicaid/Medicare proposals. State evaluators
// and CMS reviewers are trained to notice non-person-first language, and its
// presence signals cultural insensitivity about the population being served.

// ---------------------------------------------------------------------------
// Prompt instruction — injected into every IRIS system prompt.
// ---------------------------------------------------------------------------

export const PERSON_FIRST_INSTRUCTION = `PERSON-FIRST LANGUAGE REQUIREMENT (NON-NEGOTIABLE):
You must use person-first language in everything you generate. The person is never defined by their diagnosis, disability, socioeconomic status, or any other characteristic.

ALWAYS USE these forms:
- "person with diabetes" not "diabetic person"
- "member experiencing homelessness" not "homeless member"
- "person with a substance use disorder" not "addict" or "substance abuser"
- "member with a mental health condition" not "mentally ill member"
- "person with a disability" not "disabled person"
- "member with limited financial resources" not "low-income member"
- "person who uses a wheelchair" not "wheelchair-bound person"
- "child with autism" not "autistic child"
- "member with opioid use disorder" not "opioid addict"
- "person experiencing poverty" not "impoverished person"
- "member who is incarcerated" not "prisoner" or "inmate"
- "person with a chronic condition" not "chronically ill person"
- "older adult" or "senior" not "elderly" (unless quoting regulatory language directly)
- "member with limited English proficiency" not "non-English speaker"
- "undocumented person" or "person without documentation" not "illegal immigrant"
- "person in recovery" not "former addict" or "recovering addict"
- "Medicaid members" or "Medicaid beneficiaries" not "Medicaid recipients"
- "underserved populations" or name the specific group, not "vulnerable populations"
- "patients with elevated risk" not "high-risk patients"
- "patients who face barriers to adherence" not "non-compliant patients"

NEVER USE these terms under any circumstances:
addict, addicts, alcoholic, diabetic (as a noun), asthmatic (as a noun), epileptic (as a noun), schizophrenic (as a noun), the mentally ill, the disabled, the handicapped, the homeless, the elderly, the blind, the deaf, wheelchair-bound, suffers from, afflicted with, confined to a wheelchair, illegals, illegal aliens, welfare recipients, vulnerable populations (without naming the specific group), at-risk populations (without naming the specific risk), chronic disease patients.

When quoting directly from RFP language that uses non-person-first terms: quote accurately, but add person-first language in your analysis surrounding the quote, and add a short IRIS note advising the writer to use person-first phrasing in their response.

This standard applies to every IRIS brief, every Oracle section, every Score Me analysis and suggested language, every Ask IRIS response, every IRIS correction suggestion, every co-pilot message drafted by IRIS ASSIST, and every notification body text generated by IRIS.`;

// Convenience: prepend PFL instruction to any system prompt.
export function withPersonFirst(system: string): string {
  return `${PERSON_FIRST_INSTRUCTION}\n\n${system}`;
}

// ---------------------------------------------------------------------------
// Detection library — client-side real-time scan.
// ---------------------------------------------------------------------------

export type PersonFirstFlag = {
  match: string;        // term as it appears in the user's text (original case)
  pattern: string;      // canonical lowercase form from the library
  replacement: string;  // suggested person-first replacement
  start: number;        // start index in original text
  end: number;          // end index (exclusive)
};

// Entries are sorted longest-first below so multi-word phrases match
// before single-word substrings ("the homeless" before "homeless").
type Rule = { pattern: string; replacement: string };

const RULES: Rule[] = [
  // Multi-word phrases first
  { pattern: "wheelchair-bound person", replacement: "person who uses a wheelchair" },
  { pattern: "wheelchair bound person", replacement: "person who uses a wheelchair" },
  { pattern: "confined to a wheelchair", replacement: "uses a wheelchair" },
  { pattern: "wheelchair-bound", replacement: "uses a wheelchair" },
  { pattern: "wheelchair bound", replacement: "uses a wheelchair" },
  { pattern: "patients suffering from", replacement: "patients living with" },
  { pattern: "suffers from", replacement: "lives with" },
  { pattern: "afflicted with", replacement: "living with" },
  { pattern: "victims of", replacement: "people affected by" },
  { pattern: "non-compliant patients", replacement: "patients who face barriers to adherence" },
  { pattern: "noncompliant patients", replacement: "patients who face barriers to adherence" },
  { pattern: "high-risk patients", replacement: "patients with elevated risk" },
  { pattern: "high risk patients", replacement: "patients with elevated risk" },
  { pattern: "at-risk populations", replacement: "populations facing [specific risk]" },
  { pattern: "at risk populations", replacement: "populations facing [specific risk]" },
  { pattern: "vulnerable populations", replacement: "underserved populations" },
  { pattern: "chronic disease patients", replacement: "people managing chronic conditions" },
  { pattern: "chronically ill", replacement: "living with a chronic condition" },
  { pattern: "mentally ill members", replacement: "members with mental health conditions" },
  { pattern: "mentally ill beneficiaries", replacement: "beneficiaries with mental health conditions" },
  { pattern: "mentally ill patients", replacement: "patients with mental health conditions" },
  { pattern: "mentally ill", replacement: "people with mental health conditions" },
  { pattern: "the mentally ill", replacement: "people with mental health conditions" },
  { pattern: "the disabled", replacement: "people with disabilities" },
  { pattern: "the handicapped", replacement: "people with disabilities" },
  { pattern: "disabled people", replacement: "people with disabilities" },
  { pattern: "disabled person", replacement: "person with a disability" },
  { pattern: "disabled members", replacement: "members with disabilities" },
  { pattern: "the homeless", replacement: "people experiencing homelessness" },
  { pattern: "homeless population", replacement: "people experiencing homelessness" },
  { pattern: "homeless members", replacement: "members experiencing homelessness" },
  { pattern: "homeless patients", replacement: "patients experiencing homelessness" },
  { pattern: "homeless people", replacement: "people experiencing homelessness" },
  { pattern: "the elderly", replacement: "older adults" },
  { pattern: "elderly members", replacement: "older adult members" },
  { pattern: "elderly patients", replacement: "older adult patients" },
  { pattern: "elderly people", replacement: "older adults" },
  { pattern: "the blind", replacement: "people who are blind" },
  { pattern: "the deaf", replacement: "people who are deaf" },
  { pattern: "illegal immigrants", replacement: "undocumented people" },
  { pattern: "illegal immigrant", replacement: "undocumented person" },
  { pattern: "illegal aliens", replacement: "undocumented people" },
  { pattern: "illegal alien", replacement: "undocumented person" },
  { pattern: "welfare recipients", replacement: "people receiving public assistance" },
  { pattern: "medicaid recipients", replacement: "Medicaid members" },
  { pattern: "medicaid recipient", replacement: "Medicaid member" },
  { pattern: "diabetic members", replacement: "members with diabetes" },
  { pattern: "diabetic patients", replacement: "patients with diabetes" },
  { pattern: "diabetic people", replacement: "people with diabetes" },
  { pattern: "diabetic person", replacement: "person with diabetes" },
  { pattern: "asthmatic patients", replacement: "patients with asthma" },
  { pattern: "asthmatic members", replacement: "members with asthma" },
  { pattern: "epileptic patients", replacement: "patients with epilepsy" },
  { pattern: "schizophrenic patients", replacement: "patients with schizophrenia" },
  { pattern: "autistic child", replacement: "child with autism" },
  { pattern: "autistic children", replacement: "children with autism" },
  { pattern: "low-income members", replacement: "members with limited financial resources" },
  { pattern: "low income members", replacement: "members with limited financial resources" },
  { pattern: "low-income patients", replacement: "patients with limited financial resources" },
  { pattern: "low income patients", replacement: "patients with limited financial resources" },
  { pattern: "impoverished person", replacement: "person experiencing poverty" },
  { pattern: "impoverished people", replacement: "people experiencing poverty" },
  { pattern: "recovering addict", replacement: "person in recovery" },
  { pattern: "former addict", replacement: "person in recovery" },
  { pattern: "opioid addict", replacement: "person with opioid use disorder" },
  { pattern: "opioid addicts", replacement: "people with opioid use disorder" },
  { pattern: "drug addict", replacement: "person with a substance use disorder" },
  { pattern: "drug addicts", replacement: "people with a substance use disorder" },
  { pattern: "substance abuser", replacement: "person with a substance use disorder" },
  { pattern: "substance abusers", replacement: "people with a substance use disorder" },
  { pattern: "non-english speaker", replacement: "person with limited English proficiency" },
  { pattern: "non-english speakers", replacement: "people with limited English proficiency" },
  { pattern: "non english speaker", replacement: "person with limited English proficiency" },
  { pattern: "prisoners", replacement: "people who are incarcerated" },
  { pattern: "prisoner", replacement: "person who is incarcerated" },
  { pattern: "inmates", replacement: "people who are incarcerated" },
  { pattern: "inmate", replacement: "person who is incarcerated" },
  // Single-word last
  { pattern: "addicts", replacement: "people with a substance use disorder" },
  { pattern: "addict", replacement: "person with a substance use disorder" },
  { pattern: "alcoholics", replacement: "people with alcohol use disorder" },
  { pattern: "alcoholic", replacement: "person with alcohol use disorder" },
  { pattern: "diabetics", replacement: "people with diabetes" },
  { pattern: "asthmatics", replacement: "people with asthma" },
  { pattern: "epileptics", replacement: "people with epilepsy" },
  { pattern: "schizophrenics", replacement: "people with schizophrenia" },
  { pattern: "illegals", replacement: "undocumented people" },
];

// Word-boundary-ish scan. We want to match "diabetic" but not "diabetics-care".
// Use a regex per rule with case-insensitive flag and \b boundaries when the
// term starts/ends with a word character.
function buildRegex(pattern: string): RegExp {
  // Escape regex meta characters; the only meta we expect is "-".
  const escaped = pattern.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  // Use lookarounds so multi-word phrases match cleanly. Boundaries are
  // expressed as non-letter / non-digit characters or string ends.
  return new RegExp(`(?<![A-Za-z0-9])${escaped}(?![A-Za-z0-9])`, "gi");
}

const RULE_REGEXES: { rule: Rule; regex: RegExp }[] = RULES.map((rule) => ({
  rule,
  regex: buildRegex(rule.pattern),
}));

export function scanForPersonFirstFlags(text: string): PersonFirstFlag[] {
  if (!text) return [];
  const flags: PersonFirstFlag[] = [];
  const claimed: Array<[number, number]> = [];

  // Iterate longest-first (RULES already in that order) and skip overlaps.
  for (const { rule, regex } of RULE_REGEXES) {
    regex.lastIndex = 0;
    let match: RegExpExecArray | null;
    while ((match = regex.exec(text)) !== null) {
      const start = match.index;
      const end = start + match[0].length;
      const overlaps = claimed.some(([s, e]) => start < e && end > s);
      if (overlaps) continue;
      claimed.push([start, end]);
      flags.push({
        match: match[0],
        pattern: rule.pattern,
        replacement: rule.replacement,
        start,
        end,
      });
    }
  }

  // Sort by occurrence in text so we can present them in reading order.
  flags.sort((a, b) => a.start - b.start);
  return flags;
}

// Apply a single flag's replacement to text, preserving casing context for the
// first letter (so "Diabetic members" → "Members with diabetes" feels right).
export function applyPersonFirstReplacement(
  text: string,
  flag: PersonFirstFlag,
): string {
  let replacement = flag.replacement;
  const firstChar = flag.match.charAt(0);
  if (firstChar && firstChar === firstChar.toUpperCase() && firstChar !== firstChar.toLowerCase()) {
    replacement = replacement.charAt(0).toUpperCase() + replacement.slice(1);
  }
  return text.slice(0, flag.start) + replacement + text.slice(flag.end);
}
