export const QUOTES = [
  { q: "Excellence is not a destination but a continuous journey.", a: "Brian Tracy" },
  { q: "The secret of getting ahead is getting started.", a: "Mark Twain" },
  { q: "Quality is not an act, it is a habit.", a: "Aristotle" },
  { q: "Words are, of course, the most powerful drug used by mankind.", a: "Rudyard Kipling" },
  { q: "Either write something worth reading or do something worth writing.", a: "Benjamin Franklin" },
  { q: "You don't write because you want to say something, you write because you have something to say.", a: "F. Scott Fitzgerald" },
  { q: "The first draft is just you telling yourself the story.", a: "Terry Pratchett" },
  { q: "Deadlines are the mother of invention.", a: "Unknown" },
  { q: "Hard work beats talent when talent doesn't work hard.", a: "Tim Notke" },
  { q: "The difference between ordinary and extraordinary is that little extra.", a: "Jimmy Johnson" },
  { q: "Do the best you can until you know better. Then when you know better, do better.", a: "Maya Angelou" },
  { q: "It always seems impossible until it's done.", a: "Nelson Mandela" },
  { q: "Success is the sum of small efforts repeated day in and day out.", a: "Robert Collier" },
  { q: "Write with the door closed, rewrite with the door open.", a: "Stephen King" },
  { q: "Clarity is the counterbalance of profound thoughts.", a: "Luc de Clapiers" },
  { q: "The art of writing is the art of discovering what you believe.", a: "Gustave Flaubert" },
  { q: "A word after a word after a word is power.", a: "Margaret Atwood" },
  { q: "You can always edit a bad page. You can't edit a blank page.", a: "Jodi Picoult" },
  { q: "Start where you are. Use what you have. Do what you can.", a: "Arthur Ashe" },
  { q: "The greatest glory in living lies not in never falling, but in rising every time we fall.", a: "Nelson Mandela" },
  { q: "Believe you can and you're halfway there.", a: "Theodore Roosevelt" },
  { q: "Everything you've ever wanted is on the other side of fear.", a: "George Addair" },
  { q: "We may encounter many defeats but we must not be defeated.", a: "Maya Angelou" },
  { q: "The future belongs to those who believe in the beauty of their dreams.", a: "Eleanor Roosevelt" },
  { q: "Don't watch the clock; do what it does. Keep going.", a: "Sam Levenson" },
  { q: "Perseverance is not a long race; it is many short races one after the other.", a: "Walter Elliot" },
  { q: "The only way to do great work is to love what you do.", a: "Steve Jobs" },
  { q: "It does not matter how slowly you go as long as you do not stop.", a: "Confucius" },
  { q: "Writing is thinking on paper.", a: "William Zinsser" },
  { q: "The pen is the tongue of the mind.", a: "Miguel de Cervantes" },
  { q: "There is no greater agony than bearing an untold story inside you.", a: "Maya Angelou" },
  { q: "If it sounds like writing, I rewrite it.", a: "Elmore Leonard" },
  { q: "The most valuable of all talents is that of never using two words when one will do.", a: "Thomas Jefferson" },
  { q: "Fill your paper with the breathings of your heart.", a: "William Wordsworth" },
  { q: "A good writer possesses not only his own spirit but also the spirit of his friends.", a: "Friedrich Nietzsche" },
  { q: "Writing is the painting of the voice.", a: "Voltaire" },
  { q: "One day or day one. You decide.", a: "Unknown" },
  { q: "Push yourself because no one else is going to do it for you.", a: "Unknown" },
  { q: "Great things never come from comfort zones.", a: "Unknown" },
  { q: "Dream it. Wish it. Do it.", a: "Unknown" },
  { q: "Success doesn't just find you. You have to go out and get it.", a: "Unknown" },
  { q: "The harder you work for something, the greater you'll feel when you achieve it.", a: "Unknown" },
  { q: "Don't stop when you're tired. Stop when you're done.", a: "Unknown" },
  { q: "Wake up with determination. Go to bed with satisfaction.", a: "Unknown" },
  { q: "Do something today that your future self will thank you for.", a: "Sean Patrick Flanery" },
  { q: "Little things make big days.", a: "Unknown" },
  { q: "It's going to be hard but hard is not impossible.", a: "Unknown" },
  { q: "Don't wait for opportunity. Create it.", a: "Unknown" },
  { q: "Sometimes we're tested not to show our weaknesses but to discover our strengths.", a: "Unknown" },
  { q: "The key to success is to focus on goals, not obstacles.", a: "Unknown" },
  { q: "Dream bigger. Do bigger.", a: "Unknown" },
  { q: "You don't have to be great to start, but you have to start to be great.", a: "Zig Ziglar" },
  { q: "Act as if what you do makes a difference. It does.", a: "William James" },
  { q: "Success is not final, failure is not fatal: it is the courage to continue that counts.", a: "Winston Churchill" },
  { q: "Knowing is not enough; we must apply. Wishing is not enough; we must do.", a: "Johann Wolfgang von Goethe" },
  { q: "Imagine your life is perfect in every respect; what would it look like?", a: "Brian Tracy" },
  { q: "We generate fears while we sit. We overcome them by action.", a: "Dr. Henry Link" },
  { q: "Whether you think you can or think you can't, you're right.", a: "Henry Ford" },
  { q: "The man who has confidence in himself gains the confidence of others.", a: "Hasidic Proverb" },
  { q: "The only limit to our realization of tomorrow will be our doubts of today.", a: "Franklin D. Roosevelt" },
  { q: "Creativity is intelligence having fun.", a: "Albert Einstein" },
  { q: "What you lack in talent can be made up with desire, hustle, and giving 110% all the time.", a: "Don Zimmer" },
  { q: "Do what you can with all you have wherever you are.", a: "Theodore Roosevelt" },
  { q: "Develop an attitude of gratitude, and give thanks for everything.", a: "Brian Tracy" },
  { q: "You are never too old to set another goal or to dream a new dream.", a: "C.S. Lewis" },
  { q: "To see what is right and not do it is a lack of courage.", a: "Confucius" },
  { q: "Reading is to the mind, as exercise is to the body.", a: "Brian Tracy" },
  { q: "Fake it until you make it! Act as if you had all the confidence you require until it becomes your reality.", a: "Brian Tracy" },
  { q: "The most common way people give up their power is by thinking they don't have any.", a: "Alice Walker" },
  { q: "The mind is everything. What you think you become.", a: "Buddha" },
  { q: "The best time to plant a tree was 20 years ago. The second best time is now.", a: "Chinese Proverb" },
  { q: "An unexamined life is not worth living.", a: "Socrates" },
  { q: "Spread love everywhere you go. Let no one ever come to you without leaving happier.", a: "Mother Teresa" },
  { q: "When you reach the end of your rope, tie a knot in it and hang on.", a: "Franklin D. Roosevelt" },
  { q: "Always remember that you are absolutely unique. Just like everyone else.", a: "Margaret Mead" },
  { q: "Don't judge each day by the harvest you reap but by the seeds that you plant.", a: "Robert Louis Stevenson" },
  { q: "The future depends on what you do today.", a: "Mahatma Gandhi" },
  { q: "Tell me and I forget. Teach me and I remember. Involve me and I learn.", a: "Benjamin Franklin" },
  { q: "The best and most beautiful things in the world cannot be seen or even touched — they must be felt with the heart.", a: "Helen Keller" },
  { q: "It is during our darkest moments that we must focus to see the light.", a: "Aristotle" },
  { q: "Whoever is happy will make others happy too.", a: "Anne Frank" },
  { q: "Do not go where the path may lead, go instead where there is no path and leave a trail.", a: "Ralph Waldo Emerson" },
  { q: "You will face many defeats in life, but never let yourself be defeated.", a: "Maya Angelou" },
  { q: "The greatest glory in living lies not in never falling, but in rising every time we fall.", a: "Nelson Mandela" },
  { q: "In the end, it's not the years in your life that count. It's the life in your years.", a: "Abraham Lincoln" },
  { q: "Never let the fear of striking out keep you from playing the game.", a: "Babe Ruth" },
  { q: "Life is either a daring adventure or nothing at all.", a: "Helen Keller" },
  { q: "Many of life's failures are people who did not realize how close they were to success when they gave up.", a: "Thomas A. Edison" },
  { q: "You have brains in your head. You have feet in your shoes. You can steer yourself any direction you choose.", a: "Dr. Seuss" },
  { q: "If life were predictable it would cease to be life and be without flavor.", a: "Eleanor Roosevelt" },
  { q: "If you look at what you have in life, you'll always have more.", a: "Oprah Winfrey" },
  { q: "If you set your goals ridiculously high and it's a failure, you will fail above everyone else's success.", a: "James Cameron" },
  { q: "Life is not measured by the number of breaths we take, but by the moments that take our breath away.", a: "Maya Angelou" },
  { q: "If you want to live a happy life, tie it to a goal, not to people or things.", a: "Albert Einstein" },
  { q: "Never let the fear of striking out keep you from playing the game.", a: "Babe Ruth" },
  { q: "Money and success don't change people; they merely amplify what is already there.", a: "Will Smith" },
  { q: "Your time is limited, so don't waste it living someone else's life.", a: "Steve Jobs" },
  { q: "Not how long, but how well you have lived is the main thing.", a: "Seneca" },
  { q: "If life were predictable it would cease to be life, and be without flavor.", a: "Eleanor Roosevelt" },
  { q: "The purpose of our lives is to be happy.", a: "Dalai Lama" },
  { q: "Get busy living or get busy dying.", a: "Stephen King" },
  { q: "You only live once, but if you do it right, once is enough.", a: "Mae West" },
  { q: "Many of life's failures are people who did not realize how close they were to success when they gave up.", a: "Thomas Edison" },
  { q: "You have to be willing to be misunderstood if you're going to innovate.", a: "Jeff Bezos" },
  { q: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", a: "Ralph Waldo Emerson" },
  { q: "Do not let making a living prevent you from making a life.", a: "John Wooden" },
  { q: "Happiness is not something ready-made. It comes from your own actions.", a: "Dalai Lama" },
  { q: "First, have a definite, clear practical ideal — a goal, an objective.", a: "Aristotle" },
  { q: "The journey of a thousand miles begins with one step.", a: "Lao Tzu" },
  { q: "That which does not kill us makes us stronger.", a: "Friedrich Nietzsche" },
  { q: "Life shrinks or expands in proportion to one's courage.", a: "Anais Nin" },
  { q: "If you want to achieve greatness, stop asking for permission.", a: "Unknown" },
  { q: "Things work out best for those who make the best of how things work out.", a: "John Wooden" },
  { q: "To live a creative life we must lose our fear of being wrong.", a: "Joseph Chilton Pearce" },
  { q: "If you are not willing to risk the usual, you will have to settle for the ordinary.", a: "Jim Rohn" },
  { q: "Trust because you are willing to accept the risk, not because it's safe or certain.", a: "Unknown" },
  { q: "Take up one idea. Make that one idea your life.", a: "Swami Vivekananda" },
  { q: "All our dreams can come true, if we have the courage to pursue them.", a: "Walt Disney" },
  { q: "Good things come to people who wait, but better things come to those who go out and get them.", a: "Unknown" },
  { q: "If you do what you always did, you will get what you always got.", a: "Unknown" },
  { q: "Success is walking from failure to failure with no loss of enthusiasm.", a: "Winston Churchill" },
  { q: "Just when the caterpillar thought the world was ending, he turned into a butterfly.", a: "Proverb" },
  { q: "Successful entrepreneurs are givers and not takers of positive energy.", a: "Unknown" },
  { q: "Whenever you see a successful person, you only see the public glories, never the private sacrifices to reach them.", a: "Vaibhav Shah" },
  { q: "Opportunities don't happen. You create them.", a: "Chris Grosser" },
  { q: "Try not to become a person of success, but rather try to become a person of value.", a: "Albert Einstein" },
  { q: "Great minds discuss ideas; average minds discuss events; small minds discuss people.", a: "Eleanor Roosevelt" },
  { q: "I have not failed. I've just found 10,000 ways that won't work.", a: "Thomas Edison" },
  { q: "If you don't value your time, neither will others.", a: "Kim Garst" },
  { q: "A successful man is one who can lay a firm foundation with the bricks others have thrown at him.", a: "David Brinkley" },
  { q: "No one can make you feel inferior without your consent.", a: "Eleanor Roosevelt" },
  { q: "The whole secret of a successful life is to find out what is one's destiny to do, and then do it.", a: "Henry Ford" },
  { q: "If you're going through hell, keep going.", a: "Winston Churchill" },
  { q: "The ones who are crazy enough to think they can change the world, are the ones that do.", a: "Unknown" },
  { q: "Don't raise your voice, improve your argument.", a: "Desmond Tutu" },
  { q: "What seems to us as bitter trials are often blessings in disguise.", a: "Oscar Wilde" },
  { q: "The meaning of life is to find your gift. The purpose of life is to give it away.", a: "Pablo Picasso" },
  { q: "The distance between insanity and genius is measured only by success.", a: "Bruce Feirstein" },
  { q: "When you stop chasing the wrong things, you give the right things a chance to catch you.", a: "Lolly Daskal" },
  { q: "I believe that the only courage anybody ever needs is the courage to follow your own dreams.", a: "Oprah Winfrey" },
  { q: "No masterpiece was ever created by a lazy artist.", a: "Unknown" },
  { q: "Happiness is a butterfly, which when pursued, is always beyond your grasp.", a: "Nathaniel Hawthorne" },
  { q: "If you can't explain it simply, you don't understand it well enough.", a: "Albert Einstein" },
  { q: "We become what we think about most of the time, and that's the strangest secret.", a: "Earl Nightingale" },
  { q: "The only place where success comes before work is in the dictionary.", a: "Vidal Sassoon" },
  { q: "The road to success and the road to failure are almost exactly the same.", a: "Colin R. Davis" },
  { q: "I cannot give you the formula for success, but I can give you the formula for failure, which is: try to please everybody.", a: "Herbert Bayard Swope" },
  { q: "It's not what you look at that matters, it's what you see.", a: "Henry David Thoreau" },
  { q: "The two most important days in your life are the day you are born and the day you find out why.", a: "Mark Twain" },
  { q: "Whatever the mind of man can conceive and believe, it can achieve.", a: "Napoleon Hill" },
];
