/**
 * IRIS Dock — persistent conversational co-pilot. Collapsed in the
 * bottom-right corner; expands to a 400px panel (full screen on mobile).
 * Streams responses token-by-token from /api/chat/iris.
 */
import { useEffect, useMemo, useRef, useState } from "react";
import { useNavigate } from "@tanstack/react-router";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "sonner";
import { ChevronDown, Mic, Send, Sparkles, X, ExternalLink, Copy } from "lucide-react";
import { IrisMark } from "@/components/iris/IrisMark";
import { Button } from "@/components/ui/button";
import ReactMarkdown from "react-markdown";
import { useIris, getPageLabel } from "./IrisContext";
import { useIrisBoltRef } from "@/lib/iris-bolt";


const GOLD = "#C9A55C";
// IRIS brand mark color (matches the violet/blue eye in the logo)
const IRIS_BRAND = "#A78BFA";
const IRIS_BRAND_DEEP = "#6D5BD0";

type Msg = {
  id: string;
  role: "user" | "assistant";
  text: string;
  at: number;
  card?: DraftCard | ScoreCard | RiskCard | IntelCard;
};

type DraftCard = { kind: "draft"; draft: string };
type ScoreCard = { kind: "score"; total: number; breakdown: Array<{ label: string; score: number; max: number }>; gaps: string[]; detail: string };
type RiskCard = { kind: "risks"; items: Array<{ label: string; detail: string; href: string }> };
type IntelCard = { kind: "intel"; items: Array<{ headline: string; url: string | null; assessment: string | null; href: string }> };

const QUICK_DEFAULT = [
  "Brief me on this mission",
  "What's at risk right now?",
  "Latest intelligence",
  "What should I work on today?",
];
const QUICK_QUESTION = [
  "What is this question really asking?",
  "Draft a response",
  "Score my draft",
  "What research supports this?",
];

// Track proactive nudges per question so each one fires only once per session.
const proactiveFiredFor = new Set<string>();

type Props = {
  prefillSignal?: { value: string; nonce: number } | null;
  openSignal?: number;
};

export function IrisDock({ prefillSignal, openSignal }: Props) {
  const navigate = useNavigate();
  const iris = useIris();
  const [open, setOpen] = useState(false);
  const [minimized, setMinimized] = useState(false);
  const [input, setInput] = useState("");
  const [messages, setMessages] = useState<Msg[]>([]);
  const [streaming, setStreaming] = useState(false);
  const [waitingFirstToken, setWaitingFirstToken] = useState(false);
  const [hasUnread, setHasUnread] = useState(false);
  const scrollRef = useRef<HTMLDivElement | null>(null);
  const inputRef = useRef<HTMLTextAreaElement | null>(null);

  // External open trigger (Assists Bar buttons).
  useEffect(() => {
    if (openSignal) { setOpen(true); setMinimized(false); }
  }, [openSignal]);
  useEffect(() => {
    if (prefillSignal?.value) {
      setOpen(true);
      setMinimized(false);
      setInput(prefillSignal.value);
      setTimeout(() => inputRef.current?.focus(), 50);
    }
  }, [prefillSignal]);

  // Auto-scroll on new content.
  useEffect(() => {
    if (open && scrollRef.current) scrollRef.current.scrollTop = scrollRef.current.scrollHeight;
  }, [messages, open]);

  // Proactive nudge when question context changes.
  useEffect(() => {
    if (!iris.current_question_id) return;
    if (proactiveFiredFor.has(iris.current_question_id)) return;
    proactiveFiredFor.add(iris.current_question_id);
    const qNum = iris.current_question_number ?? "(question)";
    const qText = (iris.current_question_text ?? "").slice(0, 60);
    const nudge: Msg = {
      id: crypto.randomUUID(),
      role: "assistant",
      text: `I see you're working on ${qNum} — ${qText}${(iris.current_question_text ?? "").length > 60 ? "…" : ""}. Want me to brief you on this question?`,
      at: Date.now(),
    };
    setMessages((m) => [...m, nudge]);
    if (!open) setHasUnread(true);
  }, [iris.current_question_id, iris.current_question_number, iris.current_question_text, open]);

  const pageLabel = useMemo(() => getPageLabel(iris.current_page), [iris.current_page]);
  const chips = iris.current_question_id ? QUICK_QUESTION : QUICK_DEFAULT;

  const contextLine = iris.current_question_id
    ? `You are working on: ${iris.current_question_number ?? ""} — ${iris.current_section_name ?? "section"}`
    : `Viewing: ${pageLabel}`;

  const send = async (raw: string) => {
    const text = raw.trim();
    if (!text || streaming) return;

    // Special: Score-my-draft (numerical score generated by the model).
    if (/^score (my|this) draft/i.test(text)) {
      return runScore(text);
    }
    // Special: Draft a response
    if (/^draft (a |the )?response/i.test(text)) {
      return runDraft(text);
    }
    // Special: at-risk lookup
    if (/(what'?s|whats|what is).*at risk|risk(s)? right now/i.test(text)) {
      return runRisks(text);
    }
    // Special: latest intelligence
    if (/latest intelligence|recent intelligence|what.*new intel/i.test(text)) {
      return runLatestIntel(text);
    }

    const userMsg: Msg = { id: crypto.randomUUID(), role: "user", text, at: Date.now() };
    setMessages((m) => [...m, userMsg]);
    setInput("");
    await streamReply([...messages, userMsg]);
  };

  const streamReply = async (history: Msg[]) => {
    setStreaming(true);
    setWaitingFirstToken(true);
    const assistantId = crypto.randomUUID();
    setMessages((m) => [...m, { id: assistantId, role: "assistant", text: "", at: Date.now() }]);
    try {
      const { data: { session } } = await supabase.auth.getSession();
      const last = history.slice(-10).map((h) => ({ role: h.role, content: h.text }));
      const res = await fetch("/api/chat/iris", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          ...(session?.access_token ? { Authorization: `Bearer ${session.access_token}` } : {}),
        },
        body: JSON.stringify({
          missionId: iris.current_mission_id,
          sectionId: iris.current_section_id,
          questionId: iris.current_question_id,
          questionText: iris.current_question_text,
          questionNumber: iris.current_question_number,
          sectionName: iris.current_section_name,
          pageLabel,
          messages: last,
        }),
      });
      if (!res.ok || !res.body) {
        const errTxt = await res.text();
        setMessages((m) => m.map((mm) => mm.id === assistantId ? { ...mm, text: errTxt || "IRIS couldn't respond. Try again." } : mm));
        return;
      }
      const reader = res.body.getReader();
      const decoder = new TextDecoder();
      let acc = "";
      while (true) {
        const { value, done } = await reader.read();
        if (done) break;
        const chunk = decoder.decode(value, { stream: true });
        if (waitingFirstToken) setWaitingFirstToken(false);
        acc += chunk;
        setMessages((m) => m.map((mm) => mm.id === assistantId ? { ...mm, text: acc } : mm));
      }
      if (!acc) {
        setMessages((m) => m.map((mm) => mm.id === assistantId ? { ...mm, text: "Response interrupted. Ask again?" } : mm));
      }
    } catch (e) {
      setMessages((m) => m.map((mm) => mm.id === assistantId ? { ...mm, text: `Response interrupted. ${(e as Error).message}. Ask again?` } : mm));
    } finally {
      setStreaming(false);
      setWaitingFirstToken(false);
    }
  };

  // ---------- Special capability handlers ----------
  const runRisks = async (text: string) => {
    setMessages((m) => [...m, { id: crypto.randomUUID(), role: "user", text, at: Date.now() }]);
    if (!iris.current_mission_id) {
      setMessages((m) => [...m, { id: crypto.randomUUID(), role: "assistant", at: Date.now(), text: "Open a mission first and I'll surface its live risks." }]);
      return;
    }
    const mid = iris.current_mission_id;
    const [qs, asg] = await Promise.all([
      supabase.from("questions").select("id,question_number,status").eq("mission_id", mid).in("status", ["at_risk", "blocked", "overdue"]).limit(8),
      supabase.from("mission_assignments").select("id,acceptance_status").eq("mission_id", mid).eq("acceptance_status", "pending").limit(8),
    ]);
    const items: RiskCard["items"] = [
      ...((qs.data ?? []).map((q) => ({
        label: `Question ${(q as { question_number: string | null }).question_number ?? "?"}`,
        detail: `Status: ${(q as { status: string }).status}`,
        href: `/olympus/missions/${mid}?tab=questions`,
      }))),
      ...((asg.data ?? []).map((a) => ({
        label: `Assignment pending acceptance`,
        detail: `id ${(a as { id: string }).id.slice(0, 8)}`,
        href: `/olympus/missions/${mid}?tab=team`,
      }))),
    ];
    setMessages((m) => [...m, {
      id: crypto.randomUUID(), role: "assistant", at: Date.now(),
      text: items.length ? `${items.length} item${items.length === 1 ? "" : "s"} need attention right now.` : "Nothing flagged at risk right now.",
      card: { kind: "risks", items },
    }]);
  };

  const runLatestIntel = async (text: string) => {
    setMessages((m) => [...m, { id: crypto.randomUUID(), role: "user", text, at: Date.now() }]);
    if (!iris.current_mission_id) {
      setMessages((m) => [...m, { id: crypto.randomUUID(), role: "assistant", at: Date.now(), text: "Open a mission first and I'll pull the latest intel." }]);
      return;
    }
    const mid = iris.current_mission_id;
    const { data } = await supabase
      .from("intelligence_feed_items")
      .select("headline,source_url,iris_assessment")
      .eq("mission_id", mid)
      .eq("is_reviewed", false)
      .gte("iris_relevance_score", 60)
      .order("created_at", { ascending: false })
      .limit(5);
    const items: IntelCard["items"] = (data ?? []).map((d) => ({
      headline: (d as { headline: string }).headline,
      url: (d as { source_url: string | null }).source_url,
      assessment: (d as { iris_assessment: string | null }).iris_assessment,
      href: `/olympus/missions/${mid}?tab=oracle&sub=feed`,
    }));
    setMessages((m) => [...m, {
      id: crypto.randomUUID(), role: "assistant", at: Date.now(),
      text: items.length ? "Here's the latest intelligence:" : "Nothing new at relevance 60+ yet.",
      card: { kind: "intel", items },
    }]);
  };

  const runDraft = async (text: string) => {
    setMessages((m) => [...m, { id: crypto.randomUUID(), role: "user", text, at: Date.now() }]);
    const assistantId = crypto.randomUUID();
    setMessages((m) => [...m, { id: assistantId, role: "assistant", text: "", at: Date.now() }]);
    setStreaming(true);
    try {
      const { data: { session } } = await supabase.auth.getSession();
      const promptText = `Draft a complete response for the current question/section. Use the Style Guide voice, connect to Win Themes, and cite a research finding. Return the draft body only — no preamble.`;
      const res = await fetch("/api/chat/iris", {
        method: "POST",
        headers: { "Content-Type": "application/json", ...(session?.access_token ? { Authorization: `Bearer ${session.access_token}` } : {}) },
        body: JSON.stringify({
          missionId: iris.current_mission_id,
          sectionId: iris.current_section_id,
          questionId: iris.current_question_id,
          questionText: iris.current_question_text,
          questionNumber: iris.current_question_number,
          sectionName: iris.current_section_name,
          pageLabel,
          messages: [{ role: "user", content: promptText }],
        }),
      });
      const txt = await res.text();
      setMessages((m) => m.map((mm) => mm.id === assistantId ? { ...mm, text: "Drafted a response.", card: { kind: "draft", draft: txt } } : mm));
    } catch (e) {
      setMessages((m) => m.map((mm) => mm.id === assistantId ? { ...mm, text: `Draft failed: ${(e as Error).message}` } : mm));
    } finally { setStreaming(false); }
  };

  const runScore = async (text: string) => {
    const draftText = text.replace(/^score (my|this) draft:?/i, "").trim();
    setMessages((m) => [...m, { id: crypto.randomUUID(), role: "user", text, at: Date.now() }]);
    const assistantId = crypto.randomUUID();
    setMessages((m) => [...m, { id: assistantId, role: "assistant", text: "Scoring your draft…", at: Date.now() }]);
    setStreaming(true);
    try {
      const { data: { session } } = await supabase.auth.getSession();
      const scorePrompt = `Score the following draft against: RFP requirements, evaluation criteria, Win Themes, Style Guide, page/word limits. Return ONLY valid JSON: { "total": number (0-100), "breakdown": [{"label": "Requirements Coverage", "score": number 0-30, "max": 30}, {"label":"Win Theme Alignment","score":number 0-25,"max":25}, {"label":"Evidence Quality","score":number 0-20,"max":20}, {"label":"Style Compliance","score":number 0-15,"max":15}, {"label":"Conciseness","score":number 0-10,"max":10}], "gaps": string[] (specific gaps with fix recommendations), "detail": string (full analysis 3-5 sentences) }.\n\nDRAFT:\n${draftText || "(no draft pasted — score based on prior conversation context)"}`;
      const res = await fetch("/api/chat/iris", {
        method: "POST",
        headers: { "Content-Type": "application/json", ...(session?.access_token ? { Authorization: `Bearer ${session.access_token}` } : {}) },
        body: JSON.stringify({
          missionId: iris.current_mission_id,
          sectionId: iris.current_section_id,
          questionId: iris.current_question_id,
          questionText: iris.current_question_text,
          questionNumber: iris.current_question_number,
          sectionName: iris.current_section_name,
          pageLabel,
          messages: [{ role: "user", content: scorePrompt }],
        }),
      });
      const raw = await res.text();
      const match = raw.match(/\{[\s\S]*\}/);
      if (!match) throw new Error("IRIS returned no score JSON.");
      const parsed = JSON.parse(match[0]) as ScoreCard;
      setMessages((m) => m.map((mm) => mm.id === assistantId ? { ...mm, text: `Scored: ${parsed.total}/100.`, card: { kind: "score", total: parsed.total, breakdown: parsed.breakdown, gaps: parsed.gaps, detail: parsed.detail } } : mm));
    } catch (e) {
      setMessages((m) => m.map((mm) => mm.id === assistantId ? { ...mm, text: `Scoring failed: ${(e as Error).message}` } : mm));
    } finally { setStreaming(false); }
  };

  // ---------- Render ----------
  if (!open) {
    return (
      <button
        onClick={() => { setOpen(true); setHasUnread(false); }}
        title="Ask IRIS"
        className="fixed bottom-5 right-5 z-50 group"
      >
        <span
          className="relative inline-flex items-center justify-center h-14 w-14 rounded-full shadow-lg"
          style={{ background: `radial-gradient(circle at 30% 30%, ${IRIS_BRAND}, ${IRIS_BRAND_DEEP} 70%, #1A1140)` }}
        >
          <IrisMark className="h-9 w-9 relative z-10" />
          <span className="absolute inset-0 rounded-full animate-ping opacity-25" style={{ background: IRIS_BRAND, animationDuration: "3s" }} />
          {hasUnread && <span className="absolute top-0 right-0 h-3 w-3 rounded-full" style={{ background: IRIS_BRAND, boxShadow: "0 0 0 2px #0F1A2E" }} />}
        </span>
        <span className="absolute right-16 bottom-3 hidden group-hover:inline-block px-2 py-1 rounded text-xs bg-card text-foreground border whitespace-nowrap">
          Ask IRIS
        </span>
      </button>
    );
  }

  if (minimized) {
    return (
      <button
        onClick={() => setMinimized(false)}
        className="fixed bottom-5 right-5 z-50 rounded-full shadow-lg px-4 py-2 text-sm font-semibold text-white"
        style={{ background: `linear-gradient(135deg, ${IRIS_BRAND}, ${IRIS_BRAND_DEEP})` }}
      >
        <IrisMark className="inline h-4 w-4 mr-1 align-[-2px]" /> IRIS
      </button>
    );
  }

  return (
    <div
      className="fixed z-50 flex flex-col bg-card text-foreground shadow-2xl bottom-0 right-0 md:bottom-5 md:right-5 w-full md:w-[400px] h-full md:h-[520px] md:rounded-lg overflow-hidden"
      style={{ borderTop: `3px solid ${IRIS_BRAND}`, background: "#0F1A2E" }}
    >
      {/* Header */}
      <div className="flex items-start justify-between px-3 py-2 border-b border-white/10">
        <div className="flex-1 min-w-0 flex items-center gap-2">
          <IrisMark className="h-5 w-5 shrink-0" />
          <div className="min-w-0">
            <div className="text-sm font-bold" style={{ color: IRIS_BRAND }}>IRIS</div>
            <div className="text-[10px] text-white/60 truncate">{contextLine}</div>
          </div>
        </div>
        <div className="flex items-center gap-1">
          <button onClick={() => setMinimized(true)} title="Minimize" className="h-6 w-6 inline-flex items-center justify-center text-white/70 hover:text-white"><ChevronDown className="h-4 w-4" /></button>
          <button onClick={() => setOpen(false)} title="Close" className="h-6 w-6 inline-flex items-center justify-center text-white/70 hover:text-white"><X className="h-4 w-4" /></button>
        </div>
      </div>

      {/* Conversation */}
      <div ref={scrollRef} className="flex-1 overflow-y-auto px-3 py-3 space-y-3 text-sm">
        {messages.length === 0 && (
          <div className="text-white/70 text-xs italic">
            Ask me anything about this mission. I can brief you, draft responses, score your work, or surface what needs attention.
          </div>
        )}
        {messages.map((m) => (
          <MessageRow key={m.id} m={m} onOpenInThread={(draft) => {
            if (iris.current_mission_id && iris.current_question_id) {
              toast.success("Opening Sticky Notes…");
              navigate({ to: "/olympus/missions/$missionId", params: { missionId: iris.current_mission_id }, search: { tab: "questions", question: iris.current_question_id, draft } as never });
            } else {
              toast.error("No active question. Open a question first.");
            }
          }} onNavigate={(href) => navigate({ to: href })} />
        ))}
        {streaming && waitingFirstToken && (
          <div className="flex gap-1 items-center pl-2">
            <span className="h-1.5 w-1.5 rounded-full animate-pulse" style={{ background: IRIS_BRAND, animationDelay: "0ms" }} />
            <span className="h-1.5 w-1.5 rounded-full animate-pulse" style={{ background: IRIS_BRAND, animationDelay: "150ms" }} />
            <span className="h-1.5 w-1.5 rounded-full animate-pulse" style={{ background: IRIS_BRAND, animationDelay: "300ms" }} />
          </div>
        )}
      </div>

      {/* Quick chips */}
      <div className="px-3 py-2 border-t border-white/10 flex flex-wrap gap-1 relative z-10">
        {chips.map((c) => (
          <button
            key={c}
            type="button"
            onClick={(e) => { e.preventDefault(); e.stopPropagation(); if (streaming) { toast("IRIS is still answering — one sec…"); return; } send(c); }}
            className="text-[11px] px-2 py-1 rounded-full border border-white/15 text-white/85 hover:bg-white/10 cursor-pointer"
          >
            {c}
          </button>
        ))}
      </div>

      {/* Input */}
      <div className="px-3 py-2 border-t border-white/10 flex items-end gap-2">
        <textarea
          ref={inputRef}
          rows={1}
          value={input}
          onChange={(e) => setInput(e.target.value)}
          onKeyDown={(e) => { if (e.key === "Enter" && !e.shiftKey) { e.preventDefault(); send(input); } }}
          placeholder="Ask IRIS anything about this mission..."
          className="flex-1 bg-white/5 text-white placeholder:text-white/40 rounded px-2 py-1 text-sm border border-white/10 focus:outline-none focus:border-white/30 resize-none max-h-32"
          disabled={streaming}
        />
        <Button size="icon" variant="ghost" className="h-8 w-8 text-white/70" onClick={() => toast("Voice input coming soon")} title="Voice input"><Mic className="h-4 w-4" /></Button>
        <Button size="icon" className="h-8 w-8" style={{ background: IRIS_BRAND, color: "#0F1A2E" }} disabled={streaming || !input.trim()} onClick={() => send(input)} title="Send">
          <Send className="h-4 w-4" />
        </Button>
      </div>
    </div>
  );
}

function MessageRow({ m, onOpenInThread, onNavigate }: {
  m: Msg;
  onOpenInThread: (draft: string) => void;
  onNavigate: (href: string) => void;
}) {
  if (m.role === "user") {
    return (
      <div className="flex justify-end">
        <div className="rounded-lg px-3 py-2 max-w-[85%] text-white" style={{ background: "rgba(255,255,255,0.08)" }}>
          <div className="whitespace-pre-wrap break-words">{m.text}</div>
          <div className="text-[9px] text-white/40 mt-1 text-right">{new Date(m.at).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}</div>
        </div>
      </div>
    );
  }
  return (
    <div className="flex gap-2">
      <span className="mt-1 h-5 w-5 rounded-full shrink-0 inline-flex items-center justify-center" style={{ background: IRIS_BRAND, color: "#0F1A2E" }}><IrisMark className="h-3.5 w-3.5" /></span>
      <div className="rounded-lg px-3 py-2 max-w-[85%] text-white border-l-2" style={{ background: "rgba(255,255,255,0.04)", borderLeftColor: IRIS_BRAND }}>
        <div className="prose prose-invert prose-sm max-w-none">
          <ReactMarkdown>{m.text || " "}</ReactMarkdown>
        </div>
        {m.card?.kind === "draft" && <DraftCardView card={m.card} onOpenInThread={onOpenInThread} />}
        {m.card?.kind === "score" && <ScoreCardView card={m.card} />}
        {m.card?.kind === "risks" && <RiskCardView card={m.card} onNavigate={onNavigate} />}
        {m.card?.kind === "intel" && <IntelCardView card={m.card} onNavigate={onNavigate} />}
        <div className="text-[9px] text-white/40 mt-1">{new Date(m.at).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}</div>
      </div>
    </div>
  );
}

function DraftCardView({ card, onOpenInThread }: { card: DraftCard; onOpenInThread: (draft: string) => void }) {
  return (
    <div className="mt-2 rounded border-2 p-3" style={{ borderColor: IRIS_BRAND, background: "rgba(167,139,250,0.07)" }}>
      <div className="text-[11px] uppercase tracking-wider mb-2" style={{ color: IRIS_BRAND }}><Sparkles className="inline h-3 w-3 mr-1" />Draft</div>
      <div className="whitespace-pre-wrap text-white text-sm max-h-40 overflow-y-auto">{card.draft}</div>
      <div className="flex gap-2 mt-2">
        <Button size="sm" variant="outline" className="text-xs" onClick={() => { navigator.clipboard.writeText(card.draft); toast.success("Copied to clipboard"); }}>
          <Copy className="h-3 w-3 mr-1" /> Copy
        </Button>
        <Button size="sm" className="text-xs" style={{ background: IRIS_BRAND, color: "#0F1A2E" }} onClick={() => onOpenInThread(card.draft)}>
          📌 Notes
        </Button>
      </div>
    </div>
  );
}

function ScoreCardView({ card }: { card: ScoreCard }) {
  const [expanded, setExpanded] = useState(false);
  return (
    <div className="mt-2 rounded border p-3" style={{ borderColor: IRIS_BRAND, background: "rgba(167,139,250,0.08)" }}>
      <div className="flex items-baseline justify-between">
        <span className="text-[11px] uppercase tracking-wider" style={{ color: IRIS_BRAND }}>Score</span>
        <span className="text-2xl font-bold" style={{ color: IRIS_BRAND }}>{card.total}<span className="text-sm text-white/60">/100</span></span>
      </div>
      <div className="mt-2 space-y-1">
        {card.breakdown.map((b) => (
          <div key={b.label} className="flex items-center justify-between text-xs">
            <span className="text-white/80">{b.label}</span>
            <span className="text-white/60">{b.score}/{b.max}</span>
          </div>
        ))}
      </div>
      {card.gaps.length > 0 && (
        <div className="mt-2">
          <div className="text-[11px] uppercase tracking-wider mb-1" style={{ color: IRIS_BRAND }}>Gaps</div>
          <ul className="text-xs text-white/80 space-y-1 list-disc pl-4">
            {card.gaps.map((g, i) => <li key={i}>{g}</li>)}
          </ul>
        </div>
      )}
      <button className="mt-2 text-xs underline text-white/70" onClick={() => setExpanded((x) => !x)}>
        {expanded ? "Hide Detailed Report" : "Detailed Report"}
      </button>
      {expanded && <p className="mt-2 text-xs text-white/80 leading-relaxed">{card.detail}</p>}
    </div>
  );
}

function RiskCardView({ card, onNavigate }: { card: RiskCard; onNavigate: (href: string) => void }) {
  if (!card.items.length) return null;
  return (
    <ul className="mt-2 space-y-1">
      {card.items.map((it, i) => (
        <li key={i}>
          <button onClick={() => onNavigate(it.href)} className="w-full text-left text-xs rounded px-2 py-1 hover:bg-white/5 border border-white/10">
            <span className="font-semibold text-white">{it.label}</span>
            <span className="text-white/60"> — {it.detail}</span>
          </button>
        </li>
      ))}
    </ul>
  );
}

function IntelCardView({ card, onNavigate }: { card: IntelCard; onNavigate: (href: string) => void }) {
  if (!card.items.length) return null;
  return (
    <ul className="mt-2 space-y-1">
      {card.items.map((it, i) => (
        <li key={i} className="text-xs rounded px-2 py-1 border border-white/10">
          <div className="font-semibold text-white">{it.headline}</div>
          {it.assessment && <div className="text-white/60 mt-0.5">{it.assessment}</div>}
          <div className="flex gap-2 mt-1">
            {it.url && <a href={it.url} target="_blank" rel="noreferrer" className="underline" style={{ color: IRIS_BRAND }}>Open <ExternalLink className="inline h-3 w-3" /></a>}
            <button onClick={() => onNavigate(it.href)} className="underline" style={{ color: IRIS_BRAND }}>View in IRIS</button>
          </div>
        </li>
      ))}
    </ul>
  );
}
