import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { useServerFn } from "@tanstack/react-start";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { useParams } from "@tanstack/react-router";
import { Loader2, Sparkles } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import {
  buildAthenaInsight,
  listMissionInsights,
  listMissionSections,
} from "@/lib/athena-insights.functions";
import { AthenaInsightCard, AthenaInsightLoading, type AthenaInsight } from "@/components/insights/AthenaInsightCard";

export const Route = createFileRoute("/_authenticated/missions/$missionId/insights")({
  component: InsightsPage,
});

function InsightsPage() {
  const { missionId } = useParams({ from: "/_authenticated/missions/$missionId/insights" });
  const qc = useQueryClient();
  const list = useServerFn(listMissionInsights);
  const listSections = useServerFn(listMissionSections);
  const build = useServerFn(buildAthenaInsight);

  const [regenIds, setRegenIds] = useState<Set<string>>(new Set());
  const [bulkProgress, setBulkProgress] = useState<{ done: number; total: number } | null>(null);

  const { data: isAdmin } = useQuery({
    queryKey: ["is-admin"],
    queryFn: async () => {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) return false;
      const { data } = await supabase.rpc("has_role", { _user_id: user.id, _role: "admin" });
      return Boolean(data);
    },
  });

  const insightsQuery = useQuery({
    queryKey: ["mission-insights", missionId],
    queryFn: () => list({ data: { missionId } }),
  });

  const sectionsQuery = useQuery({
    queryKey: ["mission-sections-for-insights", missionId],
    queryFn: () => listSections({ data: { missionId } }),
  });

  const insights = (insightsQuery.data?.insights ?? []) as AthenaInsight[];
  const sections = sectionsQuery.data?.sections ?? [];
  const sectionById = new Map<string, any>(sections.map((s: any) => [s.id, s]));

  const daily = insights.find((i) => i.is_daily_insight) ?? null;
  const atRiskInsights = insights.filter((i) => i.insight_type === "at_risk");
  const sectionInsights = insights.filter((i) => i.insight_type === "section");

  const regenerate = async (insight: AthenaInsight) => {
    setRegenIds((s) => new Set([...s, insight.id]));
    try {
      await build({
        data: {
          missionId,
          type: (insight.insight_type as "daily" | "section" | "at_risk") ?? "daily",
          section_id: insight.section_id,
          question_id: insight.question_id,
          force_regenerate: true,
        },
      });
      await qc.invalidateQueries({ queryKey: ["mission-insights", missionId] });
    } catch (e) {
      console.error("[regenerate] failed", e);
    } finally {
      setRegenIds((s) => {
        const n = new Set(s); n.delete(insight.id); return n;
      });
    }
  };

  const generateAll = async () => {
    const sevenDaysAgo = Date.now() - 7 * 86400000;
    const existingSectionIds = new Set(sectionInsights
      .filter((i) => i.updated_at && new Date(i.updated_at).getTime() > sevenDaysAgo)
      .map((i) => i.section_id));
    const toGenerate = sections.filter((s: any) => !existingSectionIds.has(s.id));
    if (!toGenerate.length) return;
    setBulkProgress({ done: 0, total: toGenerate.length });
    for (let i = 0; i < toGenerate.length; i++) {
      try {
        await build({ data: { missionId, type: "section", section_id: toGenerate[i].id, force_regenerate: true } });
      } catch (e) {
        console.error("[generate-all] failed for section", toGenerate[i].id, e);
      }
      setBulkProgress({ done: i + 1, total: toGenerate.length });
    }
    await qc.invalidateQueries({ queryKey: ["mission-insights", missionId] });
    setBulkProgress(null);
  };

  if (insightsQuery.isLoading) {
    return (
      <div className="mx-auto max-w-4xl px-4 py-6">
        <AthenaInsightLoading />
      </div>
    );
  }

  const hasAny = insights.length > 0;

  return (
    <div className="mx-auto max-w-4xl px-4 sm:px-6 py-6 space-y-6">
      <header className="flex items-center justify-between">
        <div>
          <h1 className="text-xl font-medium text-foreground">Athena Insights</h1>
          <p className="text-xs text-muted-foreground mt-1">
            Strategic guidance generated by IRIS for this mission.
          </p>
        </div>
        {isAdmin && (
          <button
            type="button"
            onClick={generateAll}
            disabled={!!bulkProgress}
            className="inline-flex items-center gap-2 rounded border border-border/60 px-3 py-1.5 text-xs text-foreground hover:bg-white/5 disabled:opacity-60"
          >
            {bulkProgress ? (
              <><Loader2 className="h-3 w-3 animate-spin" /> Generating insight {bulkProgress.done + 1} of {bulkProgress.total}…</>
            ) : (
              <><Sparkles className="h-3 w-3" /> Generate All Section Insights</>
            )}
          </button>
        )}
      </header>

      {!hasAny && <AthenaInsightLoading />}

      {daily && (
        <AthenaInsightCard
          insight={daily}
          variant="daily"
          defaultExpanded
          canRegenerate={isAdmin}
          regenerating={regenIds.has(daily.id)}
          onRegenerate={() => regenerate(daily)}
        />
      )}

      {atRiskInsights.length > 0 && (
        <section className="space-y-3">
          <h2 className="text-[11px] font-medium uppercase tracking-wider text-muted-foreground">At Risk</h2>
          {atRiskInsights.map((i) => (
            <AthenaInsightCard
              key={i.id}
              insight={i}
              variant="at_risk"
              defaultExpanded
              canRegenerate={isAdmin}
              regenerating={regenIds.has(i.id)}
              onRegenerate={() => regenerate(i)}
            />
          ))}
        </section>
      )}

      {sectionInsights.length > 0 && (
        <section className="space-y-3">
          <h2 className="text-[11px] font-medium uppercase tracking-wider text-muted-foreground">By Section</h2>
          {sectionInsights
            .slice()
            .sort((a, b) => {
              const sa = sectionById.get(a.section_id ?? "")?.order_index ?? 999;
              const sb = sectionById.get(b.section_id ?? "")?.order_index ?? 999;
              return sa - sb;
            })
            .map((i) => {
              const s = i.section_id ? sectionById.get(i.section_id) : null;
              const label = s ? `${s.section_number ? `${s.section_number} — ` : ""}${s.description ?? "Section"}` : null;
              return (
                <AthenaInsightCard
                  key={i.id}
                  insight={i}
                  variant="section"
                  sectionLabel={label}
                  canRegenerate={isAdmin}
                  regenerating={regenIds.has(i.id)}
                  onRegenerate={() => regenerate(i)}
                />
              );
            })}
        </section>
      )}
    </div>
  );
}
