import { useState, useEffect, useRef } from "react";
import { useServerFn } from "@tanstack/react-start";
import { useMutation } from "@tanstack/react-query";
import { ChevronDown, X, RefreshCw, Copy, Sparkles } from "lucide-react";
import { toast } from "sonner";
import { generateFastReport } from "@/lib/iris-fast-report.functions";

type ReportType =
  | "mission_pulse"
  | "writer_sitrep"
  | "iris_coverage_gap"
  | "deadline_radar"
  | "win_theme_alignment";

const ITEMS: { key: ReportType; label: string }[] = [
  { key: "mission_pulse", label: "Mission Pulse" },
  { key: "writer_sitrep", label: "Writer Situation Report" },
  { key: "iris_coverage_gap", label: "IRIS Coverage Gap" },
  { key: "deadline_radar", label: "Deadline Radar" },
  { key: "win_theme_alignment", label: "Win Theme Alignment" },
];

export function FastReportsMenu() {
  const [open, setOpen] = useState(false);
  const [active, setActive] = useState<ReportType | null>(null);
  const wrapRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (!open) return;
    const onDoc = (e: MouseEvent) => {
      if (wrapRef.current && !wrapRef.current.contains(e.target as Node)) setOpen(false);
    };
    document.addEventListener("mousedown", onDoc);
    return () => document.removeEventListener("mousedown", onDoc);
  }, [open]);

  return (
    <>
      <div ref={wrapRef} className="relative">
        <button
          onClick={() => setOpen((v) => !v)}
          className="inline-flex items-center gap-1.5 rounded-md border border-white/15 bg-white/5 px-3 py-1.5 text-[11px] font-semibold uppercase tracking-[0.18em] text-foreground hover:bg-white/10 transition-colors"
        >
          <Sparkles className="h-3 w-3" style={{ color: "#C9A84C" }} />
          Fast Reports
          <ChevronDown className="h-3 w-3 opacity-70" />
        </button>
        {open && (
          <div className="absolute right-0 mt-2 w-64 rounded-md border border-white/10 bg-[#0d1421] shadow-xl z-50 overflow-hidden">
            {ITEMS.map((it) => (
              <button
                key={it.key}
                onClick={() => {
                  setOpen(false);
                  setActive(it.key);
                }}
                className="block w-full text-left px-4 py-2.5 text-sm text-foreground/90 hover:bg-white/5"
              >
                {it.label}
              </button>
            ))}
          </div>
        )}
      </div>
      {active && <ReportModal reportType={active} onClose={() => setActive(null)} />}
    </>
  );
}

function ReportModal({ reportType, onClose }: { reportType: ReportType; onClose: () => void }) {
  const generate = useServerFn(generateFastReport);
  const mutation = useMutation({
    mutationFn: () => generate({ data: { report_type: reportType } }),
  });

  useEffect(() => {
    mutation.mutate();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [reportType]);

  const data = mutation.data;
  const isLoading = mutation.isPending;
  const error = mutation.error as Error | undefined;

  const title = data?.title ?? labelFor(reportType);
  const stamp = data?.generated_at
    ? new Date(data.generated_at).toLocaleString()
    : new Date().toLocaleString();

  const copy = async () => {
    if (!data?.content) return;
    try {
      await navigator.clipboard.writeText(`${data.title}\nGenerated by IRIS™ · ${stamp}\n\n${data.content}`);
      toast.success("Report copied to clipboard");
    } catch {
      toast.error("Copy failed");
    }
  };

  return (
    <div className="fixed inset-0 z-[100] bg-black/80 backdrop-blur-sm flex items-stretch justify-center p-0 sm:p-6">
      <div className="w-full max-w-[960px] mx-auto bg-[#0a0e1a] border border-white/10 rounded-none sm:rounded-xl flex flex-col overflow-hidden">
        {/* Header */}
        <div className="flex items-start justify-between px-6 py-4 border-b border-white/10">
          <div>
            <div className="text-[20px] font-extrabold tracking-tight">{title}</div>
          </div>
          <div className="flex items-start gap-4">
            <div className="text-right text-[11px] text-muted-foreground">
              <span className="font-bold uppercase tracking-[0.18em]" style={{ color: "#C9A84C" }}>
                Generated by IRIS™
              </span>
              <div>{stamp}</div>
            </div>
            <button
              onClick={onClose}
              className="text-muted-foreground hover:text-foreground transition-colors"
              aria-label="Close"
            >
              <X className="h-5 w-5" />
            </button>
          </div>
        </div>

        {/* Body */}
        <div className="flex-1 overflow-y-auto px-6 py-6">
          {isLoading && (
            <div className="flex flex-col items-center justify-center py-24 text-muted-foreground">
              <RefreshCw className="h-6 w-6 animate-spin mb-3" style={{ color: "#C9A84C" }} />
              <div className="text-sm">IRIS™ is generating your report…</div>
            </div>
          )}
          {!isLoading && error && (
            <div className="rounded-md border border-destructive/40 bg-destructive/10 p-4 text-sm text-destructive">
              {error.message || "Failed to generate report"}
            </div>
          )}
          {!isLoading && !error && data?.content && (
            <ReportContent content={data.content} />
          )}
        </div>

        {/* Footer */}
        <div className="flex items-center justify-end gap-2 px-6 py-3 border-t border-white/10 bg-white/[0.02]">
          <button
            onClick={() => mutation.mutate()}
            disabled={isLoading}
            className="inline-flex items-center gap-1.5 rounded-md border border-white/15 bg-white/5 px-3 py-1.5 text-sm hover:bg-white/10 disabled:opacity-50"
          >
            <RefreshCw className={`h-3.5 w-3.5 ${isLoading ? "animate-spin" : ""}`} />
            Refresh
          </button>
          <button
            onClick={copy}
            disabled={isLoading || !data?.content}
            className="inline-flex items-center gap-1.5 rounded-md px-3 py-1.5 text-sm font-medium disabled:opacity-50"
            style={{ background: "#C9A84C", color: "#0a0e1a" }}
          >
            <Copy className="h-3.5 w-3.5" />
            Copy Report
          </button>
        </div>
      </div>
    </div>
  );
}

function labelFor(t: ReportType): string {
  return ITEMS.find((i) => i.key === t)?.label ?? "Report";
}

/**
 * Render IRIS narrative as formatted text:
 * - Paragraph breaks between blocks
 * - Lines starting with -, *, • render as bullet items
 * - Inline **bold** segments render bold
 */
function ReportContent({ content }: { content: string }) {
  const blocks = content
    .replace(/\r\n/g, "\n")
    .split(/\n{2,}/)
    .map((b) => b.trim())
    .filter(Boolean);

  return (
    <div className="space-y-4 text-[14px] leading-[1.7] text-foreground/90">
      {blocks.map((block, i) => {
        const lines = block.split("\n");
        const isList = lines.every((l) => /^\s*[-*•]\s+/.test(l) || /^\s*\d+\.\s+/.test(l));
        if (isList) {
          return (
            <ul key={i} className="list-disc pl-6 space-y-1.5">
              {lines.map((l, j) => (
                <li key={j}>{renderInline(l.replace(/^\s*([-*•]|\d+\.)\s+/, ""))}</li>
              ))}
            </ul>
          );
        }
        return <p key={i}>{renderInline(block)}</p>;
      })}
    </div>
  );
}

function renderInline(text: string): React.ReactNode {
  const parts = text.split(/(\*\*[^*]+\*\*)/g);
  return parts.map((part, i) => {
    if (part.startsWith("**") && part.endsWith("**")) {
      return (
        <strong key={i} className="font-semibold text-foreground">
          {part.slice(2, -2)}
        </strong>
      );
    }
    return <span key={i}>{part}</span>;
  });
}
