/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as OlympusRouteImport } from './routes/olympus'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as CheckinTokenRouteImport } from './routes/checkin.$token'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedPortfolioRouteImport } from './routes/_authenticated/portfolio'
import { Route as AuthenticatedMyWorkRouteImport } from './routes/_authenticated/my-work'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedHelpRouteImport } from './routes/_authenticated/help'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedProfileIndexRouteImport } from './routes/_authenticated/profile/index'
import { Route as AuthenticatedMissionsIndexRouteImport } from './routes/_authenticated/missions/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiChatIrisRouteImport } from './routes/api/chat/iris'
import { Route as AuthenticatedProfileExpertiseRouteImport } from './routes/_authenticated/profile/expertise'
import { Route as AuthenticatedOlympusTeamRouteImport } from './routes/_authenticated/olympus.team'
import { Route as AuthenticatedOlympusFlightDeckRouteImport } from './routes/_authenticated/olympus.flight-deck'
import { Route as AuthenticatedOlympusSplatRouteImport } from './routes/_authenticated/olympus.$'
import { Route as AuthenticatedAdminTeamRouteImport } from './routes/_authenticated/admin.team'
import { Route as AuthenticatedOlympusMissionsIndexRouteImport } from './routes/_authenticated/olympus.missions.index'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicHooksRefreshIntelligenceGraphRouteImport } from './routes/api/public/hooks/refresh-intelligence-graph'
import { Route as ApiPublicHooksMonitorStateFeedsRouteImport } from './routes/api/public/hooks/monitor-state-feeds'
import { Route as ApiPublicHooksMonitorResearchFeedsRouteImport } from './routes/api/public/hooks/monitor-research-feeds'
import { Route as ApiPublicHooksMonitorCustomFeedsRouteImport } from './routes/api/public/hooks/monitor-custom-feeds'
import { Route as ApiPublicHooksMonitorCmsFeedsRouteImport } from './routes/api/public/hooks/monitor-cms-feeds'
import { Route as ApiPublicHooksIrisMonitorRouteImport } from './routes/api/public/hooks/iris-monitor'
import { Route as ApiPublicHooksGenerateDailyBriefsRouteImport } from './routes/api/public/hooks/generate-daily-briefs'
import { Route as AuthenticatedOlympusMissionsNewRouteImport } from './routes/_authenticated/olympus.missions.new'
import { Route as AuthenticatedAdminTeamMemberIdRouteImport } from './routes/_authenticated/admin.team.$memberId'
import { Route as AuthenticatedOlympusMissionsMissionIdIndexRouteImport } from './routes/_authenticated/olympus.missions.$missionId.index'
import { Route as AuthenticatedOlympusMissionsMissionIdWizardRouteImport } from './routes/_authenticated/olympus.missions.$missionId.wizard'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const OlympusRoute = OlympusRouteImport.update({
  id: '/olympus',
  path: '/olympus',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckinTokenRoute = CheckinTokenRouteImport.update({
  id: '/checkin/$token',
  path: '/checkin/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPortfolioRoute = AuthenticatedPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMyWorkRoute = AuthenticatedMyWorkRouteImport.update({
  id: '/my-work',
  path: '/my-work',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHelpRoute = AuthenticatedHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileIndexRoute =
  AuthenticatedProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMissionsIndexRoute =
  AuthenticatedMissionsIndexRouteImport.update({
    id: '/missions/',
    path: '/missions/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatIrisRoute = ApiChatIrisRouteImport.update({
  id: '/api/chat/iris',
  path: '/api/chat/iris',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileExpertiseRoute =
  AuthenticatedProfileExpertiseRouteImport.update({
    id: '/profile/expertise',
    path: '/profile/expertise',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOlympusTeamRoute =
  AuthenticatedOlympusTeamRouteImport.update({
    id: '/olympus/team',
    path: '/olympus/team',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOlympusFlightDeckRoute =
  AuthenticatedOlympusFlightDeckRouteImport.update({
    id: '/olympus/flight-deck',
    path: '/olympus/flight-deck',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOlympusSplatRoute =
  AuthenticatedOlympusSplatRouteImport.update({
    id: '/olympus/$',
    path: '/olympus/$',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminTeamRoute = AuthenticatedAdminTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedOlympusMissionsIndexRoute =
  AuthenticatedOlympusMissionsIndexRouteImport.update({
    id: '/olympus/missions/',
    path: '/olympus/missions/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksRefreshIntelligenceGraphRoute =
  ApiPublicHooksRefreshIntelligenceGraphRouteImport.update({
    id: '/api/public/hooks/refresh-intelligence-graph',
    path: '/api/public/hooks/refresh-intelligence-graph',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksMonitorStateFeedsRoute =
  ApiPublicHooksMonitorStateFeedsRouteImport.update({
    id: '/api/public/hooks/monitor-state-feeds',
    path: '/api/public/hooks/monitor-state-feeds',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksMonitorResearchFeedsRoute =
  ApiPublicHooksMonitorResearchFeedsRouteImport.update({
    id: '/api/public/hooks/monitor-research-feeds',
    path: '/api/public/hooks/monitor-research-feeds',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksMonitorCustomFeedsRoute =
  ApiPublicHooksMonitorCustomFeedsRouteImport.update({
    id: '/api/public/hooks/monitor-custom-feeds',
    path: '/api/public/hooks/monitor-custom-feeds',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksMonitorCmsFeedsRoute =
  ApiPublicHooksMonitorCmsFeedsRouteImport.update({
    id: '/api/public/hooks/monitor-cms-feeds',
    path: '/api/public/hooks/monitor-cms-feeds',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksIrisMonitorRoute =
  ApiPublicHooksIrisMonitorRouteImport.update({
    id: '/api/public/hooks/iris-monitor',
    path: '/api/public/hooks/iris-monitor',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksGenerateDailyBriefsRoute =
  ApiPublicHooksGenerateDailyBriefsRouteImport.update({
    id: '/api/public/hooks/generate-daily-briefs',
    path: '/api/public/hooks/generate-daily-briefs',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedOlympusMissionsNewRoute =
  AuthenticatedOlympusMissionsNewRouteImport.update({
    id: '/olympus/missions/new',
    path: '/olympus/missions/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminTeamMemberIdRoute =
  AuthenticatedAdminTeamMemberIdRouteImport.update({
    id: '/$memberId',
    path: '/$memberId',
    getParentRoute: () => AuthenticatedAdminTeamRoute,
  } as any)
const AuthenticatedOlympusMissionsMissionIdIndexRoute =
  AuthenticatedOlympusMissionsMissionIdIndexRouteImport.update({
    id: '/olympus/missions/$missionId/',
    path: '/olympus/missions/$missionId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOlympusMissionsMissionIdWizardRoute =
  AuthenticatedOlympusMissionsMissionIdWizardRouteImport.update({
    id: '/olympus/missions/$missionId/wizard',
    path: '/olympus/missions/$missionId/wizard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/olympus': typeof OlympusRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/help': typeof AuthenticatedHelpRoute
  '/home': typeof AuthenticatedHomeRoute
  '/my-work': typeof AuthenticatedMyWorkRoute
  '/portfolio': typeof AuthenticatedPortfolioRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/team': typeof AuthenticatedTeamRoute
  '/checkin/$token': typeof CheckinTokenRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/admin/team': typeof AuthenticatedAdminTeamRouteWithChildren
  '/olympus/$': typeof AuthenticatedOlympusSplatRoute
  '/olympus/flight-deck': typeof AuthenticatedOlympusFlightDeckRoute
  '/olympus/team': typeof AuthenticatedOlympusTeamRoute
  '/profile/expertise': typeof AuthenticatedProfileExpertiseRoute
  '/api/chat/iris': typeof ApiChatIrisRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/missions/': typeof AuthenticatedMissionsIndexRoute
  '/profile/': typeof AuthenticatedProfileIndexRoute
  '/admin/team/$memberId': typeof AuthenticatedAdminTeamMemberIdRoute
  '/olympus/missions/new': typeof AuthenticatedOlympusMissionsNewRoute
  '/api/public/hooks/generate-daily-briefs': typeof ApiPublicHooksGenerateDailyBriefsRoute
  '/api/public/hooks/iris-monitor': typeof ApiPublicHooksIrisMonitorRoute
  '/api/public/hooks/monitor-cms-feeds': typeof ApiPublicHooksMonitorCmsFeedsRoute
  '/api/public/hooks/monitor-custom-feeds': typeof ApiPublicHooksMonitorCustomFeedsRoute
  '/api/public/hooks/monitor-research-feeds': typeof ApiPublicHooksMonitorResearchFeedsRoute
  '/api/public/hooks/monitor-state-feeds': typeof ApiPublicHooksMonitorStateFeedsRoute
  '/api/public/hooks/refresh-intelligence-graph': typeof ApiPublicHooksRefreshIntelligenceGraphRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/olympus/missions/': typeof AuthenticatedOlympusMissionsIndexRoute
  '/olympus/missions/$missionId/wizard': typeof AuthenticatedOlympusMissionsMissionIdWizardRoute
  '/olympus/missions/$missionId/': typeof AuthenticatedOlympusMissionsMissionIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/olympus': typeof OlympusRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/help': typeof AuthenticatedHelpRoute
  '/home': typeof AuthenticatedHomeRoute
  '/my-work': typeof AuthenticatedMyWorkRoute
  '/portfolio': typeof AuthenticatedPortfolioRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/team': typeof AuthenticatedTeamRoute
  '/checkin/$token': typeof CheckinTokenRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/admin/team': typeof AuthenticatedAdminTeamRouteWithChildren
  '/olympus/$': typeof AuthenticatedOlympusSplatRoute
  '/olympus/flight-deck': typeof AuthenticatedOlympusFlightDeckRoute
  '/olympus/team': typeof AuthenticatedOlympusTeamRoute
  '/profile/expertise': typeof AuthenticatedProfileExpertiseRoute
  '/api/chat/iris': typeof ApiChatIrisRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/missions': typeof AuthenticatedMissionsIndexRoute
  '/profile': typeof AuthenticatedProfileIndexRoute
  '/admin/team/$memberId': typeof AuthenticatedAdminTeamMemberIdRoute
  '/olympus/missions/new': typeof AuthenticatedOlympusMissionsNewRoute
  '/api/public/hooks/generate-daily-briefs': typeof ApiPublicHooksGenerateDailyBriefsRoute
  '/api/public/hooks/iris-monitor': typeof ApiPublicHooksIrisMonitorRoute
  '/api/public/hooks/monitor-cms-feeds': typeof ApiPublicHooksMonitorCmsFeedsRoute
  '/api/public/hooks/monitor-custom-feeds': typeof ApiPublicHooksMonitorCustomFeedsRoute
  '/api/public/hooks/monitor-research-feeds': typeof ApiPublicHooksMonitorResearchFeedsRoute
  '/api/public/hooks/monitor-state-feeds': typeof ApiPublicHooksMonitorStateFeedsRoute
  '/api/public/hooks/refresh-intelligence-graph': typeof ApiPublicHooksRefreshIntelligenceGraphRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/olympus/missions': typeof AuthenticatedOlympusMissionsIndexRoute
  '/olympus/missions/$missionId/wizard': typeof AuthenticatedOlympusMissionsMissionIdWizardRoute
  '/olympus/missions/$missionId': typeof AuthenticatedOlympusMissionsMissionIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/olympus': typeof OlympusRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/help': typeof AuthenticatedHelpRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/my-work': typeof AuthenticatedMyWorkRoute
  '/_authenticated/portfolio': typeof AuthenticatedPortfolioRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/checkin/$token': typeof CheckinTokenRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/_authenticated/admin/team': typeof AuthenticatedAdminTeamRouteWithChildren
  '/_authenticated/olympus/$': typeof AuthenticatedOlympusSplatRoute
  '/_authenticated/olympus/flight-deck': typeof AuthenticatedOlympusFlightDeckRoute
  '/_authenticated/olympus/team': typeof AuthenticatedOlympusTeamRoute
  '/_authenticated/profile/expertise': typeof AuthenticatedProfileExpertiseRoute
  '/api/chat/iris': typeof ApiChatIrisRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/missions/': typeof AuthenticatedMissionsIndexRoute
  '/_authenticated/profile/': typeof AuthenticatedProfileIndexRoute
  '/_authenticated/admin/team/$memberId': typeof AuthenticatedAdminTeamMemberIdRoute
  '/_authenticated/olympus/missions/new': typeof AuthenticatedOlympusMissionsNewRoute
  '/api/public/hooks/generate-daily-briefs': typeof ApiPublicHooksGenerateDailyBriefsRoute
  '/api/public/hooks/iris-monitor': typeof ApiPublicHooksIrisMonitorRoute
  '/api/public/hooks/monitor-cms-feeds': typeof ApiPublicHooksMonitorCmsFeedsRoute
  '/api/public/hooks/monitor-custom-feeds': typeof ApiPublicHooksMonitorCustomFeedsRoute
  '/api/public/hooks/monitor-research-feeds': typeof ApiPublicHooksMonitorResearchFeedsRoute
  '/api/public/hooks/monitor-state-feeds': typeof ApiPublicHooksMonitorStateFeedsRoute
  '/api/public/hooks/refresh-intelligence-graph': typeof ApiPublicHooksRefreshIntelligenceGraphRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/_authenticated/olympus/missions/': typeof AuthenticatedOlympusMissionsIndexRoute
  '/_authenticated/olympus/missions/$missionId/wizard': typeof AuthenticatedOlympusMissionsMissionIdWizardRoute
  '/_authenticated/olympus/missions/$missionId/': typeof AuthenticatedOlympusMissionsMissionIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/olympus'
    | '/unsubscribe'
    | '/admin'
    | '/help'
    | '/home'
    | '/my-work'
    | '/portfolio'
    | '/reports'
    | '/team'
    | '/checkin/$token'
    | '/email/unsubscribe'
    | '/admin/team'
    | '/olympus/$'
    | '/olympus/flight-deck'
    | '/olympus/team'
    | '/profile/expertise'
    | '/api/chat/iris'
    | '/lovable/email/suppression'
    | '/admin/'
    | '/missions/'
    | '/profile/'
    | '/admin/team/$memberId'
    | '/olympus/missions/new'
    | '/api/public/hooks/generate-daily-briefs'
    | '/api/public/hooks/iris-monitor'
    | '/api/public/hooks/monitor-cms-feeds'
    | '/api/public/hooks/monitor-custom-feeds'
    | '/api/public/hooks/monitor-research-feeds'
    | '/api/public/hooks/monitor-state-feeds'
    | '/api/public/hooks/refresh-intelligence-graph'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/olympus/missions/'
    | '/olympus/missions/$missionId/wizard'
    | '/olympus/missions/$missionId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/olympus'
    | '/unsubscribe'
    | '/help'
    | '/home'
    | '/my-work'
    | '/portfolio'
    | '/reports'
    | '/team'
    | '/checkin/$token'
    | '/email/unsubscribe'
    | '/admin/team'
    | '/olympus/$'
    | '/olympus/flight-deck'
    | '/olympus/team'
    | '/profile/expertise'
    | '/api/chat/iris'
    | '/lovable/email/suppression'
    | '/admin'
    | '/missions'
    | '/profile'
    | '/admin/team/$memberId'
    | '/olympus/missions/new'
    | '/api/public/hooks/generate-daily-briefs'
    | '/api/public/hooks/iris-monitor'
    | '/api/public/hooks/monitor-cms-feeds'
    | '/api/public/hooks/monitor-custom-feeds'
    | '/api/public/hooks/monitor-research-feeds'
    | '/api/public/hooks/monitor-state-feeds'
    | '/api/public/hooks/refresh-intelligence-graph'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/olympus/missions'
    | '/olympus/missions/$missionId/wizard'
    | '/olympus/missions/$missionId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/olympus'
    | '/unsubscribe'
    | '/_authenticated/admin'
    | '/_authenticated/help'
    | '/_authenticated/home'
    | '/_authenticated/my-work'
    | '/_authenticated/portfolio'
    | '/_authenticated/reports'
    | '/_authenticated/team'
    | '/checkin/$token'
    | '/email/unsubscribe'
    | '/_authenticated/admin/team'
    | '/_authenticated/olympus/$'
    | '/_authenticated/olympus/flight-deck'
    | '/_authenticated/olympus/team'
    | '/_authenticated/profile/expertise'
    | '/api/chat/iris'
    | '/lovable/email/suppression'
    | '/_authenticated/admin/'
    | '/_authenticated/missions/'
    | '/_authenticated/profile/'
    | '/_authenticated/admin/team/$memberId'
    | '/_authenticated/olympus/missions/new'
    | '/api/public/hooks/generate-daily-briefs'
    | '/api/public/hooks/iris-monitor'
    | '/api/public/hooks/monitor-cms-feeds'
    | '/api/public/hooks/monitor-custom-feeds'
    | '/api/public/hooks/monitor-research-feeds'
    | '/api/public/hooks/monitor-state-feeds'
    | '/api/public/hooks/refresh-intelligence-graph'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/_authenticated/olympus/missions/'
    | '/_authenticated/olympus/missions/$missionId/wizard'
    | '/_authenticated/olympus/missions/$missionId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  OlympusRoute: typeof OlympusRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  CheckinTokenRoute: typeof CheckinTokenRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  ApiChatIrisRoute: typeof ApiChatIrisRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicHooksGenerateDailyBriefsRoute: typeof ApiPublicHooksGenerateDailyBriefsRoute
  ApiPublicHooksIrisMonitorRoute: typeof ApiPublicHooksIrisMonitorRoute
  ApiPublicHooksMonitorCmsFeedsRoute: typeof ApiPublicHooksMonitorCmsFeedsRoute
  ApiPublicHooksMonitorCustomFeedsRoute: typeof ApiPublicHooksMonitorCustomFeedsRoute
  ApiPublicHooksMonitorResearchFeedsRoute: typeof ApiPublicHooksMonitorResearchFeedsRoute
  ApiPublicHooksMonitorStateFeedsRoute: typeof ApiPublicHooksMonitorStateFeedsRoute
  ApiPublicHooksRefreshIntelligenceGraphRoute: typeof ApiPublicHooksRefreshIntelligenceGraphRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/olympus': {
      id: '/olympus'
      path: '/olympus'
      fullPath: '/olympus'
      preLoaderRoute: typeof OlympusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkin/$token': {
      id: '/checkin/$token'
      path: '/checkin/$token'
      fullPath: '/checkin/$token'
      preLoaderRoute: typeof CheckinTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/portfolio': {
      id: '/_authenticated/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof AuthenticatedPortfolioRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my-work': {
      id: '/_authenticated/my-work'
      path: '/my-work'
      fullPath: '/my-work'
      preLoaderRoute: typeof AuthenticatedMyWorkRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/help': {
      id: '/_authenticated/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AuthenticatedHelpRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile/': {
      id: '/_authenticated/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof AuthenticatedProfileIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/missions/': {
      id: '/_authenticated/missions/'
      path: '/missions'
      fullPath: '/missions/'
      preLoaderRoute: typeof AuthenticatedMissionsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat/iris': {
      id: '/api/chat/iris'
      path: '/api/chat/iris'
      fullPath: '/api/chat/iris'
      preLoaderRoute: typeof ApiChatIrisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile/expertise': {
      id: '/_authenticated/profile/expertise'
      path: '/profile/expertise'
      fullPath: '/profile/expertise'
      preLoaderRoute: typeof AuthenticatedProfileExpertiseRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/olympus/team': {
      id: '/_authenticated/olympus/team'
      path: '/olympus/team'
      fullPath: '/olympus/team'
      preLoaderRoute: typeof AuthenticatedOlympusTeamRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/olympus/flight-deck': {
      id: '/_authenticated/olympus/flight-deck'
      path: '/olympus/flight-deck'
      fullPath: '/olympus/flight-deck'
      preLoaderRoute: typeof AuthenticatedOlympusFlightDeckRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/olympus/$': {
      id: '/_authenticated/olympus/$'
      path: '/olympus/$'
      fullPath: '/olympus/$'
      preLoaderRoute: typeof AuthenticatedOlympusSplatRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/team': {
      id: '/_authenticated/admin/team'
      path: '/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AuthenticatedAdminTeamRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/olympus/missions/': {
      id: '/_authenticated/olympus/missions/'
      path: '/olympus/missions'
      fullPath: '/olympus/missions/'
      preLoaderRoute: typeof AuthenticatedOlympusMissionsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/refresh-intelligence-graph': {
      id: '/api/public/hooks/refresh-intelligence-graph'
      path: '/api/public/hooks/refresh-intelligence-graph'
      fullPath: '/api/public/hooks/refresh-intelligence-graph'
      preLoaderRoute: typeof ApiPublicHooksRefreshIntelligenceGraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/monitor-state-feeds': {
      id: '/api/public/hooks/monitor-state-feeds'
      path: '/api/public/hooks/monitor-state-feeds'
      fullPath: '/api/public/hooks/monitor-state-feeds'
      preLoaderRoute: typeof ApiPublicHooksMonitorStateFeedsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/monitor-research-feeds': {
      id: '/api/public/hooks/monitor-research-feeds'
      path: '/api/public/hooks/monitor-research-feeds'
      fullPath: '/api/public/hooks/monitor-research-feeds'
      preLoaderRoute: typeof ApiPublicHooksMonitorResearchFeedsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/monitor-custom-feeds': {
      id: '/api/public/hooks/monitor-custom-feeds'
      path: '/api/public/hooks/monitor-custom-feeds'
      fullPath: '/api/public/hooks/monitor-custom-feeds'
      preLoaderRoute: typeof ApiPublicHooksMonitorCustomFeedsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/monitor-cms-feeds': {
      id: '/api/public/hooks/monitor-cms-feeds'
      path: '/api/public/hooks/monitor-cms-feeds'
      fullPath: '/api/public/hooks/monitor-cms-feeds'
      preLoaderRoute: typeof ApiPublicHooksMonitorCmsFeedsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/iris-monitor': {
      id: '/api/public/hooks/iris-monitor'
      path: '/api/public/hooks/iris-monitor'
      fullPath: '/api/public/hooks/iris-monitor'
      preLoaderRoute: typeof ApiPublicHooksIrisMonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/generate-daily-briefs': {
      id: '/api/public/hooks/generate-daily-briefs'
      path: '/api/public/hooks/generate-daily-briefs'
      fullPath: '/api/public/hooks/generate-daily-briefs'
      preLoaderRoute: typeof ApiPublicHooksGenerateDailyBriefsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/olympus/missions/new': {
      id: '/_authenticated/olympus/missions/new'
      path: '/olympus/missions/new'
      fullPath: '/olympus/missions/new'
      preLoaderRoute: typeof AuthenticatedOlympusMissionsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/team/$memberId': {
      id: '/_authenticated/admin/team/$memberId'
      path: '/$memberId'
      fullPath: '/admin/team/$memberId'
      preLoaderRoute: typeof AuthenticatedAdminTeamMemberIdRouteImport
      parentRoute: typeof AuthenticatedAdminTeamRoute
    }
    '/_authenticated/olympus/missions/$missionId/': {
      id: '/_authenticated/olympus/missions/$missionId/'
      path: '/olympus/missions/$missionId'
      fullPath: '/olympus/missions/$missionId/'
      preLoaderRoute: typeof AuthenticatedOlympusMissionsMissionIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/olympus/missions/$missionId/wizard': {
      id: '/_authenticated/olympus/missions/$missionId/wizard'
      path: '/olympus/missions/$missionId/wizard'
      fullPath: '/olympus/missions/$missionId/wizard'
      preLoaderRoute: typeof AuthenticatedOlympusMissionsMissionIdWizardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedAdminTeamRouteChildren {
  AuthenticatedAdminTeamMemberIdRoute: typeof AuthenticatedAdminTeamMemberIdRoute
}

const AuthenticatedAdminTeamRouteChildren: AuthenticatedAdminTeamRouteChildren =
  {
    AuthenticatedAdminTeamMemberIdRoute: AuthenticatedAdminTeamMemberIdRoute,
  }

const AuthenticatedAdminTeamRouteWithChildren =
  AuthenticatedAdminTeamRoute._addFileChildren(
    AuthenticatedAdminTeamRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminTeamRoute: typeof AuthenticatedAdminTeamRouteWithChildren
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminTeamRoute: AuthenticatedAdminTeamRouteWithChildren,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedHelpRoute: typeof AuthenticatedHelpRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedMyWorkRoute: typeof AuthenticatedMyWorkRoute
  AuthenticatedPortfolioRoute: typeof AuthenticatedPortfolioRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
  AuthenticatedOlympusSplatRoute: typeof AuthenticatedOlympusSplatRoute
  AuthenticatedOlympusFlightDeckRoute: typeof AuthenticatedOlympusFlightDeckRoute
  AuthenticatedOlympusTeamRoute: typeof AuthenticatedOlympusTeamRoute
  AuthenticatedProfileExpertiseRoute: typeof AuthenticatedProfileExpertiseRoute
  AuthenticatedMissionsIndexRoute: typeof AuthenticatedMissionsIndexRoute
  AuthenticatedProfileIndexRoute: typeof AuthenticatedProfileIndexRoute
  AuthenticatedOlympusMissionsNewRoute: typeof AuthenticatedOlympusMissionsNewRoute
  AuthenticatedOlympusMissionsIndexRoute: typeof AuthenticatedOlympusMissionsIndexRoute
  AuthenticatedOlympusMissionsMissionIdWizardRoute: typeof AuthenticatedOlympusMissionsMissionIdWizardRoute
  AuthenticatedOlympusMissionsMissionIdIndexRoute: typeof AuthenticatedOlympusMissionsMissionIdIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedHelpRoute: AuthenticatedHelpRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedMyWorkRoute: AuthenticatedMyWorkRoute,
  AuthenticatedPortfolioRoute: AuthenticatedPortfolioRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
  AuthenticatedOlympusSplatRoute: AuthenticatedOlympusSplatRoute,
  AuthenticatedOlympusFlightDeckRoute: AuthenticatedOlympusFlightDeckRoute,
  AuthenticatedOlympusTeamRoute: AuthenticatedOlympusTeamRoute,
  AuthenticatedProfileExpertiseRoute: AuthenticatedProfileExpertiseRoute,
  AuthenticatedMissionsIndexRoute: AuthenticatedMissionsIndexRoute,
  AuthenticatedProfileIndexRoute: AuthenticatedProfileIndexRoute,
  AuthenticatedOlympusMissionsNewRoute: AuthenticatedOlympusMissionsNewRoute,
  AuthenticatedOlympusMissionsIndexRoute:
    AuthenticatedOlympusMissionsIndexRoute,
  AuthenticatedOlympusMissionsMissionIdWizardRoute:
    AuthenticatedOlympusMissionsMissionIdWizardRoute,
  AuthenticatedOlympusMissionsMissionIdIndexRoute:
    AuthenticatedOlympusMissionsMissionIdIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  OlympusRoute: OlympusRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  CheckinTokenRoute: CheckinTokenRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  ApiChatIrisRoute: ApiChatIrisRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicHooksGenerateDailyBriefsRoute:
    ApiPublicHooksGenerateDailyBriefsRoute,
  ApiPublicHooksIrisMonitorRoute: ApiPublicHooksIrisMonitorRoute,
  ApiPublicHooksMonitorCmsFeedsRoute: ApiPublicHooksMonitorCmsFeedsRoute,
  ApiPublicHooksMonitorCustomFeedsRoute: ApiPublicHooksMonitorCustomFeedsRoute,
  ApiPublicHooksMonitorResearchFeedsRoute:
    ApiPublicHooksMonitorResearchFeedsRoute,
  ApiPublicHooksMonitorStateFeedsRoute: ApiPublicHooksMonitorStateFeedsRoute,
  ApiPublicHooksRefreshIntelligenceGraphRoute:
    ApiPublicHooksRefreshIntelligenceGraphRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
