/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPipelineHorizonRouteImport } from './routes/_authenticated/pipeline-horizon'
import { Route as AuthenticatedPathfinderRouteImport } from './routes/_authenticated/pathfinder'
import { Route as AuthenticatedOlympusRouteImport } from './routes/_authenticated/olympus'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedOlympusIndexRouteImport } from './routes/_authenticated/olympus/index'
import { Route as AuthenticatedOlympusWinThemesRouteImport } from './routes/_authenticated/olympus/win-themes'
import { Route as AuthenticatedOlympusVaultRouteImport } from './routes/_authenticated/olympus/vault'
import { Route as AuthenticatedOlympusUsersRouteImport } from './routes/_authenticated/olympus/users'
import { Route as AuthenticatedOlympusTeamRouteImport } from './routes/_authenticated/olympus/team'
import { Route as AuthenticatedOlympusSettingsRouteImport } from './routes/_authenticated/olympus/settings'
import { Route as AuthenticatedOlympusScoreMeRouteImport } from './routes/_authenticated/olympus/score-me'
import { Route as AuthenticatedOlympusQuestionsRouteImport } from './routes/_authenticated/olympus/questions'
import { Route as AuthenticatedOlympusIrisMemoryRouteImport } from './routes/_authenticated/olympus/iris-memory'
import { Route as AuthenticatedOlympusIntelligenceRouteImport } from './routes/_authenticated/olympus/intelligence'
import { Route as AuthenticatedOlympusGatesRouteImport } from './routes/_authenticated/olympus/gates'
import { Route as AuthenticatedOlympusAuditRouteImport } from './routes/_authenticated/olympus/audit'
import { Route as AuthenticatedOlympusAtlasSourcesRouteImport } from './routes/_authenticated/olympus/atlas-sources'
import { Route as AuthenticatedMissionsMissionIdRouteImport } from './routes/_authenticated/missions/$missionId'
import { Route as AuthenticatedCommandScoresRouteImport } from './routes/_authenticated/command/scores'
import { Route as AuthenticatedCommandQuestionHealthRouteImport } from './routes/_authenticated/command/question-health'
import { Route as AuthenticatedCommandPensDownRouteImport } from './routes/_authenticated/command/pens-down'
import { Route as AuthenticatedCommandBroadcastsRouteImport } from './routes/_authenticated/command/broadcasts'
import { Route as AuthenticatedCommandAttentionRouteImport } from './routes/_authenticated/command/attention'
import { Route as AuthenticatedCommandAlignmentConflictsRouteImport } from './routes/_authenticated/command/alignment-conflicts'
import { Route as AuthenticatedCommandAlignmentRouteImport } from './routes/_authenticated/command/alignment'
import { Route as AuthenticatedMissionsMissionIdIndexRouteImport } from './routes/_authenticated/missions/$missionId/index'
import { Route as ApiPublicHooksRefreshIntelligenceRouteImport } from './routes/api/public/hooks/refresh-intelligence'
import { Route as ApiPublicHooksIngestIntelRouteImport } from './routes/api/public/hooks/ingest-intel'
import { Route as ApiPublicHooksBackfillQuestionEmbeddingsRouteImport } from './routes/api/public/hooks/backfill-question-embeddings'
import { Route as AuthenticatedMissionsMissionIdTeamRouteImport } from './routes/_authenticated/missions/$missionId/team'
import { Route as AuthenticatedMissionsMissionIdStudioRouteImport } from './routes/_authenticated/missions/$missionId/studio'
import { Route as AuthenticatedMissionsMissionIdSettingsRouteImport } from './routes/_authenticated/missions/$missionId/settings'
import { Route as AuthenticatedMissionsMissionIdOverviewRouteImport } from './routes/_authenticated/missions/$missionId/overview'
import { Route as AuthenticatedMissionsMissionIdOperationsRouteImport } from './routes/_authenticated/missions/$missionId/operations'
import { Route as AuthenticatedMissionsMissionIdLibraryRouteImport } from './routes/_authenticated/missions/$missionId/library'
import { Route as AuthenticatedMissionsMissionIdIrisRouteImport } from './routes/_authenticated/missions/$missionId/iris'
import { Route as AuthenticatedMissionsMissionIdIntelligenceRouteImport } from './routes/_authenticated/missions/$missionId/intelligence'
import { Route as AuthenticatedMissionsMissionIdBriefingRouteImport } from './routes/_authenticated/missions/$missionId/briefing'
import { Route as AuthenticatedMissionsMissionIdBriefRouteImport } from './routes/_authenticated/missions/$missionId/brief'
import { Route as AuthenticatedMissionsMissionIdActivityRouteImport } from './routes/_authenticated/missions/$missionId/activity'
import { Route as AuthenticatedMissionsMissionIdQuestionsIndexRouteImport } from './routes/_authenticated/missions/$missionId/questions/index'
import { Route as AuthenticatedMissionsMissionIdQuestionsQuestionIdRouteImport } from './routes/_authenticated/missions/$missionId/questions/$questionId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPipelineHorizonRoute =
  AuthenticatedPipelineHorizonRouteImport.update({
    id: '/pipeline-horizon',
    path: '/pipeline-horizon',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPathfinderRoute = AuthenticatedPathfinderRouteImport.update({
  id: '/pathfinder',
  path: '/pathfinder',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOlympusRoute = AuthenticatedOlympusRouteImport.update({
  id: '/olympus',
  path: '/olympus',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOlympusIndexRoute =
  AuthenticatedOlympusIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedOlympusRoute,
  } as any)
const AuthenticatedOlympusWinThemesRoute =
  AuthenticatedOlympusWinThemesRouteImport.update({
    id: '/win-themes',
    path: '/win-themes',
    getParentRoute: () => AuthenticatedOlympusRoute,
  } as any)
const AuthenticatedOlympusVaultRoute =
  AuthenticatedOlympusVaultRouteImport.update({
    id: '/vault',
    path: '/vault',
    getParentRoute: () => AuthenticatedOlympusRoute,
  } as any)
const AuthenticatedOlympusUsersRoute =
  AuthenticatedOlympusUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedOlympusRoute,
  } as any)
const AuthenticatedOlympusTeamRoute =
  AuthenticatedOlympusTeamRouteImport.update({
    id: '/team',
    path: '/team',
    getParentRoute: () => AuthenticatedOlympusRoute,
  } as any)
const AuthenticatedOlympusSettingsRoute =
  AuthenticatedOlympusSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedOlympusRoute,
  } as any)
const AuthenticatedOlympusScoreMeRoute =
  AuthenticatedOlympusScoreMeRouteImport.update({
    id: '/score-me',
    path: '/score-me',
    getParentRoute: () => AuthenticatedOlympusRoute,
  } as any)
const AuthenticatedOlympusQuestionsRoute =
  AuthenticatedOlympusQuestionsRouteImport.update({
    id: '/questions',
    path: '/questions',
    getParentRoute: () => AuthenticatedOlympusRoute,
  } as any)
const AuthenticatedOlympusIrisMemoryRoute =
  AuthenticatedOlympusIrisMemoryRouteImport.update({
    id: '/iris-memory',
    path: '/iris-memory',
    getParentRoute: () => AuthenticatedOlympusRoute,
  } as any)
const AuthenticatedOlympusIntelligenceRoute =
  AuthenticatedOlympusIntelligenceRouteImport.update({
    id: '/intelligence',
    path: '/intelligence',
    getParentRoute: () => AuthenticatedOlympusRoute,
  } as any)
const AuthenticatedOlympusGatesRoute =
  AuthenticatedOlympusGatesRouteImport.update({
    id: '/gates',
    path: '/gates',
    getParentRoute: () => AuthenticatedOlympusRoute,
  } as any)
const AuthenticatedOlympusAuditRoute =
  AuthenticatedOlympusAuditRouteImport.update({
    id: '/audit',
    path: '/audit',
    getParentRoute: () => AuthenticatedOlympusRoute,
  } as any)
const AuthenticatedOlympusAtlasSourcesRoute =
  AuthenticatedOlympusAtlasSourcesRouteImport.update({
    id: '/atlas-sources',
    path: '/atlas-sources',
    getParentRoute: () => AuthenticatedOlympusRoute,
  } as any)
const AuthenticatedMissionsMissionIdRoute =
  AuthenticatedMissionsMissionIdRouteImport.update({
    id: '/missions/$missionId',
    path: '/missions/$missionId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCommandScoresRoute =
  AuthenticatedCommandScoresRouteImport.update({
    id: '/command/scores',
    path: '/command/scores',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCommandQuestionHealthRoute =
  AuthenticatedCommandQuestionHealthRouteImport.update({
    id: '/command/question-health',
    path: '/command/question-health',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCommandPensDownRoute =
  AuthenticatedCommandPensDownRouteImport.update({
    id: '/command/pens-down',
    path: '/command/pens-down',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCommandBroadcastsRoute =
  AuthenticatedCommandBroadcastsRouteImport.update({
    id: '/command/broadcasts',
    path: '/command/broadcasts',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCommandAttentionRoute =
  AuthenticatedCommandAttentionRouteImport.update({
    id: '/command/attention',
    path: '/command/attention',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCommandAlignmentConflictsRoute =
  AuthenticatedCommandAlignmentConflictsRouteImport.update({
    id: '/command/alignment-conflicts',
    path: '/command/alignment-conflicts',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCommandAlignmentRoute =
  AuthenticatedCommandAlignmentRouteImport.update({
    id: '/command/alignment',
    path: '/command/alignment',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMissionsMissionIdIndexRoute =
  AuthenticatedMissionsMissionIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedMissionsMissionIdRoute,
  } as any)
const ApiPublicHooksRefreshIntelligenceRoute =
  ApiPublicHooksRefreshIntelligenceRouteImport.update({
    id: '/api/public/hooks/refresh-intelligence',
    path: '/api/public/hooks/refresh-intelligence',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksIngestIntelRoute =
  ApiPublicHooksIngestIntelRouteImport.update({
    id: '/api/public/hooks/ingest-intel',
    path: '/api/public/hooks/ingest-intel',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksBackfillQuestionEmbeddingsRoute =
  ApiPublicHooksBackfillQuestionEmbeddingsRouteImport.update({
    id: '/api/public/hooks/backfill-question-embeddings',
    path: '/api/public/hooks/backfill-question-embeddings',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedMissionsMissionIdTeamRoute =
  AuthenticatedMissionsMissionIdTeamRouteImport.update({
    id: '/team',
    path: '/team',
    getParentRoute: () => AuthenticatedMissionsMissionIdRoute,
  } as any)
const AuthenticatedMissionsMissionIdStudioRoute =
  AuthenticatedMissionsMissionIdStudioRouteImport.update({
    id: '/studio',
    path: '/studio',
    getParentRoute: () => AuthenticatedMissionsMissionIdRoute,
  } as any)
const AuthenticatedMissionsMissionIdSettingsRoute =
  AuthenticatedMissionsMissionIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedMissionsMissionIdRoute,
  } as any)
const AuthenticatedMissionsMissionIdOverviewRoute =
  AuthenticatedMissionsMissionIdOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => AuthenticatedMissionsMissionIdRoute,
  } as any)
const AuthenticatedMissionsMissionIdOperationsRoute =
  AuthenticatedMissionsMissionIdOperationsRouteImport.update({
    id: '/operations',
    path: '/operations',
    getParentRoute: () => AuthenticatedMissionsMissionIdRoute,
  } as any)
const AuthenticatedMissionsMissionIdLibraryRoute =
  AuthenticatedMissionsMissionIdLibraryRouteImport.update({
    id: '/library',
    path: '/library',
    getParentRoute: () => AuthenticatedMissionsMissionIdRoute,
  } as any)
const AuthenticatedMissionsMissionIdIrisRoute =
  AuthenticatedMissionsMissionIdIrisRouteImport.update({
    id: '/iris',
    path: '/iris',
    getParentRoute: () => AuthenticatedMissionsMissionIdRoute,
  } as any)
const AuthenticatedMissionsMissionIdIntelligenceRoute =
  AuthenticatedMissionsMissionIdIntelligenceRouteImport.update({
    id: '/intelligence',
    path: '/intelligence',
    getParentRoute: () => AuthenticatedMissionsMissionIdRoute,
  } as any)
const AuthenticatedMissionsMissionIdBriefingRoute =
  AuthenticatedMissionsMissionIdBriefingRouteImport.update({
    id: '/briefing',
    path: '/briefing',
    getParentRoute: () => AuthenticatedMissionsMissionIdRoute,
  } as any)
const AuthenticatedMissionsMissionIdBriefRoute =
  AuthenticatedMissionsMissionIdBriefRouteImport.update({
    id: '/brief',
    path: '/brief',
    getParentRoute: () => AuthenticatedMissionsMissionIdRoute,
  } as any)
const AuthenticatedMissionsMissionIdActivityRoute =
  AuthenticatedMissionsMissionIdActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => AuthenticatedMissionsMissionIdRoute,
  } as any)
const AuthenticatedMissionsMissionIdQuestionsIndexRoute =
  AuthenticatedMissionsMissionIdQuestionsIndexRouteImport.update({
    id: '/questions/',
    path: '/questions/',
    getParentRoute: () => AuthenticatedMissionsMissionIdRoute,
  } as any)
const AuthenticatedMissionsMissionIdQuestionsQuestionIdRoute =
  AuthenticatedMissionsMissionIdQuestionsQuestionIdRouteImport.update({
    id: '/questions/$questionId',
    path: '/questions/$questionId',
    getParentRoute: () => AuthenticatedMissionsMissionIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/home': typeof AuthenticatedHomeRoute
  '/olympus': typeof AuthenticatedOlympusRouteWithChildren
  '/pathfinder': typeof AuthenticatedPathfinderRoute
  '/pipeline-horizon': typeof AuthenticatedPipelineHorizonRoute
  '/command/alignment': typeof AuthenticatedCommandAlignmentRoute
  '/command/alignment-conflicts': typeof AuthenticatedCommandAlignmentConflictsRoute
  '/command/attention': typeof AuthenticatedCommandAttentionRoute
  '/command/broadcasts': typeof AuthenticatedCommandBroadcastsRoute
  '/command/pens-down': typeof AuthenticatedCommandPensDownRoute
  '/command/question-health': typeof AuthenticatedCommandQuestionHealthRoute
  '/command/scores': typeof AuthenticatedCommandScoresRoute
  '/missions/$missionId': typeof AuthenticatedMissionsMissionIdRouteWithChildren
  '/olympus/atlas-sources': typeof AuthenticatedOlympusAtlasSourcesRoute
  '/olympus/audit': typeof AuthenticatedOlympusAuditRoute
  '/olympus/gates': typeof AuthenticatedOlympusGatesRoute
  '/olympus/intelligence': typeof AuthenticatedOlympusIntelligenceRoute
  '/olympus/iris-memory': typeof AuthenticatedOlympusIrisMemoryRoute
  '/olympus/questions': typeof AuthenticatedOlympusQuestionsRoute
  '/olympus/score-me': typeof AuthenticatedOlympusScoreMeRoute
  '/olympus/settings': typeof AuthenticatedOlympusSettingsRoute
  '/olympus/team': typeof AuthenticatedOlympusTeamRoute
  '/olympus/users': typeof AuthenticatedOlympusUsersRoute
  '/olympus/vault': typeof AuthenticatedOlympusVaultRoute
  '/olympus/win-themes': typeof AuthenticatedOlympusWinThemesRoute
  '/olympus/': typeof AuthenticatedOlympusIndexRoute
  '/missions/$missionId/activity': typeof AuthenticatedMissionsMissionIdActivityRoute
  '/missions/$missionId/brief': typeof AuthenticatedMissionsMissionIdBriefRoute
  '/missions/$missionId/briefing': typeof AuthenticatedMissionsMissionIdBriefingRoute
  '/missions/$missionId/intelligence': typeof AuthenticatedMissionsMissionIdIntelligenceRoute
  '/missions/$missionId/iris': typeof AuthenticatedMissionsMissionIdIrisRoute
  '/missions/$missionId/library': typeof AuthenticatedMissionsMissionIdLibraryRoute
  '/missions/$missionId/operations': typeof AuthenticatedMissionsMissionIdOperationsRoute
  '/missions/$missionId/overview': typeof AuthenticatedMissionsMissionIdOverviewRoute
  '/missions/$missionId/settings': typeof AuthenticatedMissionsMissionIdSettingsRoute
  '/missions/$missionId/studio': typeof AuthenticatedMissionsMissionIdStudioRoute
  '/missions/$missionId/team': typeof AuthenticatedMissionsMissionIdTeamRoute
  '/api/public/hooks/backfill-question-embeddings': typeof ApiPublicHooksBackfillQuestionEmbeddingsRoute
  '/api/public/hooks/ingest-intel': typeof ApiPublicHooksIngestIntelRoute
  '/api/public/hooks/refresh-intelligence': typeof ApiPublicHooksRefreshIntelligenceRoute
  '/missions/$missionId/': typeof AuthenticatedMissionsMissionIdIndexRoute
  '/missions/$missionId/questions/$questionId': typeof AuthenticatedMissionsMissionIdQuestionsQuestionIdRoute
  '/missions/$missionId/questions/': typeof AuthenticatedMissionsMissionIdQuestionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/home': typeof AuthenticatedHomeRoute
  '/pathfinder': typeof AuthenticatedPathfinderRoute
  '/pipeline-horizon': typeof AuthenticatedPipelineHorizonRoute
  '/command/alignment': typeof AuthenticatedCommandAlignmentRoute
  '/command/alignment-conflicts': typeof AuthenticatedCommandAlignmentConflictsRoute
  '/command/attention': typeof AuthenticatedCommandAttentionRoute
  '/command/broadcasts': typeof AuthenticatedCommandBroadcastsRoute
  '/command/pens-down': typeof AuthenticatedCommandPensDownRoute
  '/command/question-health': typeof AuthenticatedCommandQuestionHealthRoute
  '/command/scores': typeof AuthenticatedCommandScoresRoute
  '/olympus/atlas-sources': typeof AuthenticatedOlympusAtlasSourcesRoute
  '/olympus/audit': typeof AuthenticatedOlympusAuditRoute
  '/olympus/gates': typeof AuthenticatedOlympusGatesRoute
  '/olympus/intelligence': typeof AuthenticatedOlympusIntelligenceRoute
  '/olympus/iris-memory': typeof AuthenticatedOlympusIrisMemoryRoute
  '/olympus/questions': typeof AuthenticatedOlympusQuestionsRoute
  '/olympus/score-me': typeof AuthenticatedOlympusScoreMeRoute
  '/olympus/settings': typeof AuthenticatedOlympusSettingsRoute
  '/olympus/team': typeof AuthenticatedOlympusTeamRoute
  '/olympus/users': typeof AuthenticatedOlympusUsersRoute
  '/olympus/vault': typeof AuthenticatedOlympusVaultRoute
  '/olympus/win-themes': typeof AuthenticatedOlympusWinThemesRoute
  '/olympus': typeof AuthenticatedOlympusIndexRoute
  '/missions/$missionId/activity': typeof AuthenticatedMissionsMissionIdActivityRoute
  '/missions/$missionId/brief': typeof AuthenticatedMissionsMissionIdBriefRoute
  '/missions/$missionId/briefing': typeof AuthenticatedMissionsMissionIdBriefingRoute
  '/missions/$missionId/intelligence': typeof AuthenticatedMissionsMissionIdIntelligenceRoute
  '/missions/$missionId/iris': typeof AuthenticatedMissionsMissionIdIrisRoute
  '/missions/$missionId/library': typeof AuthenticatedMissionsMissionIdLibraryRoute
  '/missions/$missionId/operations': typeof AuthenticatedMissionsMissionIdOperationsRoute
  '/missions/$missionId/overview': typeof AuthenticatedMissionsMissionIdOverviewRoute
  '/missions/$missionId/settings': typeof AuthenticatedMissionsMissionIdSettingsRoute
  '/missions/$missionId/studio': typeof AuthenticatedMissionsMissionIdStudioRoute
  '/missions/$missionId/team': typeof AuthenticatedMissionsMissionIdTeamRoute
  '/api/public/hooks/backfill-question-embeddings': typeof ApiPublicHooksBackfillQuestionEmbeddingsRoute
  '/api/public/hooks/ingest-intel': typeof ApiPublicHooksIngestIntelRoute
  '/api/public/hooks/refresh-intelligence': typeof ApiPublicHooksRefreshIntelligenceRoute
  '/missions/$missionId': typeof AuthenticatedMissionsMissionIdIndexRoute
  '/missions/$missionId/questions/$questionId': typeof AuthenticatedMissionsMissionIdQuestionsQuestionIdRoute
  '/missions/$missionId/questions': typeof AuthenticatedMissionsMissionIdQuestionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/olympus': typeof AuthenticatedOlympusRouteWithChildren
  '/_authenticated/pathfinder': typeof AuthenticatedPathfinderRoute
  '/_authenticated/pipeline-horizon': typeof AuthenticatedPipelineHorizonRoute
  '/_authenticated/command/alignment': typeof AuthenticatedCommandAlignmentRoute
  '/_authenticated/command/alignment-conflicts': typeof AuthenticatedCommandAlignmentConflictsRoute
  '/_authenticated/command/attention': typeof AuthenticatedCommandAttentionRoute
  '/_authenticated/command/broadcasts': typeof AuthenticatedCommandBroadcastsRoute
  '/_authenticated/command/pens-down': typeof AuthenticatedCommandPensDownRoute
  '/_authenticated/command/question-health': typeof AuthenticatedCommandQuestionHealthRoute
  '/_authenticated/command/scores': typeof AuthenticatedCommandScoresRoute
  '/_authenticated/missions/$missionId': typeof AuthenticatedMissionsMissionIdRouteWithChildren
  '/_authenticated/olympus/atlas-sources': typeof AuthenticatedOlympusAtlasSourcesRoute
  '/_authenticated/olympus/audit': typeof AuthenticatedOlympusAuditRoute
  '/_authenticated/olympus/gates': typeof AuthenticatedOlympusGatesRoute
  '/_authenticated/olympus/intelligence': typeof AuthenticatedOlympusIntelligenceRoute
  '/_authenticated/olympus/iris-memory': typeof AuthenticatedOlympusIrisMemoryRoute
  '/_authenticated/olympus/questions': typeof AuthenticatedOlympusQuestionsRoute
  '/_authenticated/olympus/score-me': typeof AuthenticatedOlympusScoreMeRoute
  '/_authenticated/olympus/settings': typeof AuthenticatedOlympusSettingsRoute
  '/_authenticated/olympus/team': typeof AuthenticatedOlympusTeamRoute
  '/_authenticated/olympus/users': typeof AuthenticatedOlympusUsersRoute
  '/_authenticated/olympus/vault': typeof AuthenticatedOlympusVaultRoute
  '/_authenticated/olympus/win-themes': typeof AuthenticatedOlympusWinThemesRoute
  '/_authenticated/olympus/': typeof AuthenticatedOlympusIndexRoute
  '/_authenticated/missions/$missionId/activity': typeof AuthenticatedMissionsMissionIdActivityRoute
  '/_authenticated/missions/$missionId/brief': typeof AuthenticatedMissionsMissionIdBriefRoute
  '/_authenticated/missions/$missionId/briefing': typeof AuthenticatedMissionsMissionIdBriefingRoute
  '/_authenticated/missions/$missionId/intelligence': typeof AuthenticatedMissionsMissionIdIntelligenceRoute
  '/_authenticated/missions/$missionId/iris': typeof AuthenticatedMissionsMissionIdIrisRoute
  '/_authenticated/missions/$missionId/library': typeof AuthenticatedMissionsMissionIdLibraryRoute
  '/_authenticated/missions/$missionId/operations': typeof AuthenticatedMissionsMissionIdOperationsRoute
  '/_authenticated/missions/$missionId/overview': typeof AuthenticatedMissionsMissionIdOverviewRoute
  '/_authenticated/missions/$missionId/settings': typeof AuthenticatedMissionsMissionIdSettingsRoute
  '/_authenticated/missions/$missionId/studio': typeof AuthenticatedMissionsMissionIdStudioRoute
  '/_authenticated/missions/$missionId/team': typeof AuthenticatedMissionsMissionIdTeamRoute
  '/api/public/hooks/backfill-question-embeddings': typeof ApiPublicHooksBackfillQuestionEmbeddingsRoute
  '/api/public/hooks/ingest-intel': typeof ApiPublicHooksIngestIntelRoute
  '/api/public/hooks/refresh-intelligence': typeof ApiPublicHooksRefreshIntelligenceRoute
  '/_authenticated/missions/$missionId/': typeof AuthenticatedMissionsMissionIdIndexRoute
  '/_authenticated/missions/$missionId/questions/$questionId': typeof AuthenticatedMissionsMissionIdQuestionsQuestionIdRoute
  '/_authenticated/missions/$missionId/questions/': typeof AuthenticatedMissionsMissionIdQuestionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/home'
    | '/olympus'
    | '/pathfinder'
    | '/pipeline-horizon'
    | '/command/alignment'
    | '/command/alignment-conflicts'
    | '/command/attention'
    | '/command/broadcasts'
    | '/command/pens-down'
    | '/command/question-health'
    | '/command/scores'
    | '/missions/$missionId'
    | '/olympus/atlas-sources'
    | '/olympus/audit'
    | '/olympus/gates'
    | '/olympus/intelligence'
    | '/olympus/iris-memory'
    | '/olympus/questions'
    | '/olympus/score-me'
    | '/olympus/settings'
    | '/olympus/team'
    | '/olympus/users'
    | '/olympus/vault'
    | '/olympus/win-themes'
    | '/olympus/'
    | '/missions/$missionId/activity'
    | '/missions/$missionId/brief'
    | '/missions/$missionId/briefing'
    | '/missions/$missionId/intelligence'
    | '/missions/$missionId/iris'
    | '/missions/$missionId/library'
    | '/missions/$missionId/operations'
    | '/missions/$missionId/overview'
    | '/missions/$missionId/settings'
    | '/missions/$missionId/studio'
    | '/missions/$missionId/team'
    | '/api/public/hooks/backfill-question-embeddings'
    | '/api/public/hooks/ingest-intel'
    | '/api/public/hooks/refresh-intelligence'
    | '/missions/$missionId/'
    | '/missions/$missionId/questions/$questionId'
    | '/missions/$missionId/questions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/home'
    | '/pathfinder'
    | '/pipeline-horizon'
    | '/command/alignment'
    | '/command/alignment-conflicts'
    | '/command/attention'
    | '/command/broadcasts'
    | '/command/pens-down'
    | '/command/question-health'
    | '/command/scores'
    | '/olympus/atlas-sources'
    | '/olympus/audit'
    | '/olympus/gates'
    | '/olympus/intelligence'
    | '/olympus/iris-memory'
    | '/olympus/questions'
    | '/olympus/score-me'
    | '/olympus/settings'
    | '/olympus/team'
    | '/olympus/users'
    | '/olympus/vault'
    | '/olympus/win-themes'
    | '/olympus'
    | '/missions/$missionId/activity'
    | '/missions/$missionId/brief'
    | '/missions/$missionId/briefing'
    | '/missions/$missionId/intelligence'
    | '/missions/$missionId/iris'
    | '/missions/$missionId/library'
    | '/missions/$missionId/operations'
    | '/missions/$missionId/overview'
    | '/missions/$missionId/settings'
    | '/missions/$missionId/studio'
    | '/missions/$missionId/team'
    | '/api/public/hooks/backfill-question-embeddings'
    | '/api/public/hooks/ingest-intel'
    | '/api/public/hooks/refresh-intelligence'
    | '/missions/$missionId'
    | '/missions/$missionId/questions/$questionId'
    | '/missions/$missionId/questions'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/home'
    | '/_authenticated/olympus'
    | '/_authenticated/pathfinder'
    | '/_authenticated/pipeline-horizon'
    | '/_authenticated/command/alignment'
    | '/_authenticated/command/alignment-conflicts'
    | '/_authenticated/command/attention'
    | '/_authenticated/command/broadcasts'
    | '/_authenticated/command/pens-down'
    | '/_authenticated/command/question-health'
    | '/_authenticated/command/scores'
    | '/_authenticated/missions/$missionId'
    | '/_authenticated/olympus/atlas-sources'
    | '/_authenticated/olympus/audit'
    | '/_authenticated/olympus/gates'
    | '/_authenticated/olympus/intelligence'
    | '/_authenticated/olympus/iris-memory'
    | '/_authenticated/olympus/questions'
    | '/_authenticated/olympus/score-me'
    | '/_authenticated/olympus/settings'
    | '/_authenticated/olympus/team'
    | '/_authenticated/olympus/users'
    | '/_authenticated/olympus/vault'
    | '/_authenticated/olympus/win-themes'
    | '/_authenticated/olympus/'
    | '/_authenticated/missions/$missionId/activity'
    | '/_authenticated/missions/$missionId/brief'
    | '/_authenticated/missions/$missionId/briefing'
    | '/_authenticated/missions/$missionId/intelligence'
    | '/_authenticated/missions/$missionId/iris'
    | '/_authenticated/missions/$missionId/library'
    | '/_authenticated/missions/$missionId/operations'
    | '/_authenticated/missions/$missionId/overview'
    | '/_authenticated/missions/$missionId/settings'
    | '/_authenticated/missions/$missionId/studio'
    | '/_authenticated/missions/$missionId/team'
    | '/api/public/hooks/backfill-question-embeddings'
    | '/api/public/hooks/ingest-intel'
    | '/api/public/hooks/refresh-intelligence'
    | '/_authenticated/missions/$missionId/'
    | '/_authenticated/missions/$missionId/questions/$questionId'
    | '/_authenticated/missions/$missionId/questions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiPublicHooksBackfillQuestionEmbeddingsRoute: typeof ApiPublicHooksBackfillQuestionEmbeddingsRoute
  ApiPublicHooksIngestIntelRoute: typeof ApiPublicHooksIngestIntelRoute
  ApiPublicHooksRefreshIntelligenceRoute: typeof ApiPublicHooksRefreshIntelligenceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/pipeline-horizon': {
      id: '/_authenticated/pipeline-horizon'
      path: '/pipeline-horizon'
      fullPath: '/pipeline-horizon'
      preLoaderRoute: typeof AuthenticatedPipelineHorizonRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pathfinder': {
      id: '/_authenticated/pathfinder'
      path: '/pathfinder'
      fullPath: '/pathfinder'
      preLoaderRoute: typeof AuthenticatedPathfinderRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/olympus': {
      id: '/_authenticated/olympus'
      path: '/olympus'
      fullPath: '/olympus'
      preLoaderRoute: typeof AuthenticatedOlympusRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/olympus/': {
      id: '/_authenticated/olympus/'
      path: '/'
      fullPath: '/olympus/'
      preLoaderRoute: typeof AuthenticatedOlympusIndexRouteImport
      parentRoute: typeof AuthenticatedOlympusRoute
    }
    '/_authenticated/olympus/win-themes': {
      id: '/_authenticated/olympus/win-themes'
      path: '/win-themes'
      fullPath: '/olympus/win-themes'
      preLoaderRoute: typeof AuthenticatedOlympusWinThemesRouteImport
      parentRoute: typeof AuthenticatedOlympusRoute
    }
    '/_authenticated/olympus/vault': {
      id: '/_authenticated/olympus/vault'
      path: '/vault'
      fullPath: '/olympus/vault'
      preLoaderRoute: typeof AuthenticatedOlympusVaultRouteImport
      parentRoute: typeof AuthenticatedOlympusRoute
    }
    '/_authenticated/olympus/users': {
      id: '/_authenticated/olympus/users'
      path: '/users'
      fullPath: '/olympus/users'
      preLoaderRoute: typeof AuthenticatedOlympusUsersRouteImport
      parentRoute: typeof AuthenticatedOlympusRoute
    }
    '/_authenticated/olympus/team': {
      id: '/_authenticated/olympus/team'
      path: '/team'
      fullPath: '/olympus/team'
      preLoaderRoute: typeof AuthenticatedOlympusTeamRouteImport
      parentRoute: typeof AuthenticatedOlympusRoute
    }
    '/_authenticated/olympus/settings': {
      id: '/_authenticated/olympus/settings'
      path: '/settings'
      fullPath: '/olympus/settings'
      preLoaderRoute: typeof AuthenticatedOlympusSettingsRouteImport
      parentRoute: typeof AuthenticatedOlympusRoute
    }
    '/_authenticated/olympus/score-me': {
      id: '/_authenticated/olympus/score-me'
      path: '/score-me'
      fullPath: '/olympus/score-me'
      preLoaderRoute: typeof AuthenticatedOlympusScoreMeRouteImport
      parentRoute: typeof AuthenticatedOlympusRoute
    }
    '/_authenticated/olympus/questions': {
      id: '/_authenticated/olympus/questions'
      path: '/questions'
      fullPath: '/olympus/questions'
      preLoaderRoute: typeof AuthenticatedOlympusQuestionsRouteImport
      parentRoute: typeof AuthenticatedOlympusRoute
    }
    '/_authenticated/olympus/iris-memory': {
      id: '/_authenticated/olympus/iris-memory'
      path: '/iris-memory'
      fullPath: '/olympus/iris-memory'
      preLoaderRoute: typeof AuthenticatedOlympusIrisMemoryRouteImport
      parentRoute: typeof AuthenticatedOlympusRoute
    }
    '/_authenticated/olympus/intelligence': {
      id: '/_authenticated/olympus/intelligence'
      path: '/intelligence'
      fullPath: '/olympus/intelligence'
      preLoaderRoute: typeof AuthenticatedOlympusIntelligenceRouteImport
      parentRoute: typeof AuthenticatedOlympusRoute
    }
    '/_authenticated/olympus/gates': {
      id: '/_authenticated/olympus/gates'
      path: '/gates'
      fullPath: '/olympus/gates'
      preLoaderRoute: typeof AuthenticatedOlympusGatesRouteImport
      parentRoute: typeof AuthenticatedOlympusRoute
    }
    '/_authenticated/olympus/audit': {
      id: '/_authenticated/olympus/audit'
      path: '/audit'
      fullPath: '/olympus/audit'
      preLoaderRoute: typeof AuthenticatedOlympusAuditRouteImport
      parentRoute: typeof AuthenticatedOlympusRoute
    }
    '/_authenticated/olympus/atlas-sources': {
      id: '/_authenticated/olympus/atlas-sources'
      path: '/atlas-sources'
      fullPath: '/olympus/atlas-sources'
      preLoaderRoute: typeof AuthenticatedOlympusAtlasSourcesRouteImport
      parentRoute: typeof AuthenticatedOlympusRoute
    }
    '/_authenticated/missions/$missionId': {
      id: '/_authenticated/missions/$missionId'
      path: '/missions/$missionId'
      fullPath: '/missions/$missionId'
      preLoaderRoute: typeof AuthenticatedMissionsMissionIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/command/scores': {
      id: '/_authenticated/command/scores'
      path: '/command/scores'
      fullPath: '/command/scores'
      preLoaderRoute: typeof AuthenticatedCommandScoresRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/command/question-health': {
      id: '/_authenticated/command/question-health'
      path: '/command/question-health'
      fullPath: '/command/question-health'
      preLoaderRoute: typeof AuthenticatedCommandQuestionHealthRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/command/pens-down': {
      id: '/_authenticated/command/pens-down'
      path: '/command/pens-down'
      fullPath: '/command/pens-down'
      preLoaderRoute: typeof AuthenticatedCommandPensDownRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/command/broadcasts': {
      id: '/_authenticated/command/broadcasts'
      path: '/command/broadcasts'
      fullPath: '/command/broadcasts'
      preLoaderRoute: typeof AuthenticatedCommandBroadcastsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/command/attention': {
      id: '/_authenticated/command/attention'
      path: '/command/attention'
      fullPath: '/command/attention'
      preLoaderRoute: typeof AuthenticatedCommandAttentionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/command/alignment-conflicts': {
      id: '/_authenticated/command/alignment-conflicts'
      path: '/command/alignment-conflicts'
      fullPath: '/command/alignment-conflicts'
      preLoaderRoute: typeof AuthenticatedCommandAlignmentConflictsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/command/alignment': {
      id: '/_authenticated/command/alignment'
      path: '/command/alignment'
      fullPath: '/command/alignment'
      preLoaderRoute: typeof AuthenticatedCommandAlignmentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/missions/$missionId/': {
      id: '/_authenticated/missions/$missionId/'
      path: '/'
      fullPath: '/missions/$missionId/'
      preLoaderRoute: typeof AuthenticatedMissionsMissionIdIndexRouteImport
      parentRoute: typeof AuthenticatedMissionsMissionIdRoute
    }
    '/api/public/hooks/refresh-intelligence': {
      id: '/api/public/hooks/refresh-intelligence'
      path: '/api/public/hooks/refresh-intelligence'
      fullPath: '/api/public/hooks/refresh-intelligence'
      preLoaderRoute: typeof ApiPublicHooksRefreshIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/ingest-intel': {
      id: '/api/public/hooks/ingest-intel'
      path: '/api/public/hooks/ingest-intel'
      fullPath: '/api/public/hooks/ingest-intel'
      preLoaderRoute: typeof ApiPublicHooksIngestIntelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/backfill-question-embeddings': {
      id: '/api/public/hooks/backfill-question-embeddings'
      path: '/api/public/hooks/backfill-question-embeddings'
      fullPath: '/api/public/hooks/backfill-question-embeddings'
      preLoaderRoute: typeof ApiPublicHooksBackfillQuestionEmbeddingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/missions/$missionId/team': {
      id: '/_authenticated/missions/$missionId/team'
      path: '/team'
      fullPath: '/missions/$missionId/team'
      preLoaderRoute: typeof AuthenticatedMissionsMissionIdTeamRouteImport
      parentRoute: typeof AuthenticatedMissionsMissionIdRoute
    }
    '/_authenticated/missions/$missionId/studio': {
      id: '/_authenticated/missions/$missionId/studio'
      path: '/studio'
      fullPath: '/missions/$missionId/studio'
      preLoaderRoute: typeof AuthenticatedMissionsMissionIdStudioRouteImport
      parentRoute: typeof AuthenticatedMissionsMissionIdRoute
    }
    '/_authenticated/missions/$missionId/settings': {
      id: '/_authenticated/missions/$missionId/settings'
      path: '/settings'
      fullPath: '/missions/$missionId/settings'
      preLoaderRoute: typeof AuthenticatedMissionsMissionIdSettingsRouteImport
      parentRoute: typeof AuthenticatedMissionsMissionIdRoute
    }
    '/_authenticated/missions/$missionId/overview': {
      id: '/_authenticated/missions/$missionId/overview'
      path: '/overview'
      fullPath: '/missions/$missionId/overview'
      preLoaderRoute: typeof AuthenticatedMissionsMissionIdOverviewRouteImport
      parentRoute: typeof AuthenticatedMissionsMissionIdRoute
    }
    '/_authenticated/missions/$missionId/operations': {
      id: '/_authenticated/missions/$missionId/operations'
      path: '/operations'
      fullPath: '/missions/$missionId/operations'
      preLoaderRoute: typeof AuthenticatedMissionsMissionIdOperationsRouteImport
      parentRoute: typeof AuthenticatedMissionsMissionIdRoute
    }
    '/_authenticated/missions/$missionId/library': {
      id: '/_authenticated/missions/$missionId/library'
      path: '/library'
      fullPath: '/missions/$missionId/library'
      preLoaderRoute: typeof AuthenticatedMissionsMissionIdLibraryRouteImport
      parentRoute: typeof AuthenticatedMissionsMissionIdRoute
    }
    '/_authenticated/missions/$missionId/iris': {
      id: '/_authenticated/missions/$missionId/iris'
      path: '/iris'
      fullPath: '/missions/$missionId/iris'
      preLoaderRoute: typeof AuthenticatedMissionsMissionIdIrisRouteImport
      parentRoute: typeof AuthenticatedMissionsMissionIdRoute
    }
    '/_authenticated/missions/$missionId/intelligence': {
      id: '/_authenticated/missions/$missionId/intelligence'
      path: '/intelligence'
      fullPath: '/missions/$missionId/intelligence'
      preLoaderRoute: typeof AuthenticatedMissionsMissionIdIntelligenceRouteImport
      parentRoute: typeof AuthenticatedMissionsMissionIdRoute
    }
    '/_authenticated/missions/$missionId/briefing': {
      id: '/_authenticated/missions/$missionId/briefing'
      path: '/briefing'
      fullPath: '/missions/$missionId/briefing'
      preLoaderRoute: typeof AuthenticatedMissionsMissionIdBriefingRouteImport
      parentRoute: typeof AuthenticatedMissionsMissionIdRoute
    }
    '/_authenticated/missions/$missionId/brief': {
      id: '/_authenticated/missions/$missionId/brief'
      path: '/brief'
      fullPath: '/missions/$missionId/brief'
      preLoaderRoute: typeof AuthenticatedMissionsMissionIdBriefRouteImport
      parentRoute: typeof AuthenticatedMissionsMissionIdRoute
    }
    '/_authenticated/missions/$missionId/activity': {
      id: '/_authenticated/missions/$missionId/activity'
      path: '/activity'
      fullPath: '/missions/$missionId/activity'
      preLoaderRoute: typeof AuthenticatedMissionsMissionIdActivityRouteImport
      parentRoute: typeof AuthenticatedMissionsMissionIdRoute
    }
    '/_authenticated/missions/$missionId/questions/': {
      id: '/_authenticated/missions/$missionId/questions/'
      path: '/questions'
      fullPath: '/missions/$missionId/questions/'
      preLoaderRoute: typeof AuthenticatedMissionsMissionIdQuestionsIndexRouteImport
      parentRoute: typeof AuthenticatedMissionsMissionIdRoute
    }
    '/_authenticated/missions/$missionId/questions/$questionId': {
      id: '/_authenticated/missions/$missionId/questions/$questionId'
      path: '/questions/$questionId'
      fullPath: '/missions/$missionId/questions/$questionId'
      preLoaderRoute: typeof AuthenticatedMissionsMissionIdQuestionsQuestionIdRouteImport
      parentRoute: typeof AuthenticatedMissionsMissionIdRoute
    }
  }
}

interface AuthenticatedOlympusRouteChildren {
  AuthenticatedOlympusAtlasSourcesRoute: typeof AuthenticatedOlympusAtlasSourcesRoute
  AuthenticatedOlympusAuditRoute: typeof AuthenticatedOlympusAuditRoute
  AuthenticatedOlympusGatesRoute: typeof AuthenticatedOlympusGatesRoute
  AuthenticatedOlympusIntelligenceRoute: typeof AuthenticatedOlympusIntelligenceRoute
  AuthenticatedOlympusIrisMemoryRoute: typeof AuthenticatedOlympusIrisMemoryRoute
  AuthenticatedOlympusQuestionsRoute: typeof AuthenticatedOlympusQuestionsRoute
  AuthenticatedOlympusScoreMeRoute: typeof AuthenticatedOlympusScoreMeRoute
  AuthenticatedOlympusSettingsRoute: typeof AuthenticatedOlympusSettingsRoute
  AuthenticatedOlympusTeamRoute: typeof AuthenticatedOlympusTeamRoute
  AuthenticatedOlympusUsersRoute: typeof AuthenticatedOlympusUsersRoute
  AuthenticatedOlympusVaultRoute: typeof AuthenticatedOlympusVaultRoute
  AuthenticatedOlympusWinThemesRoute: typeof AuthenticatedOlympusWinThemesRoute
  AuthenticatedOlympusIndexRoute: typeof AuthenticatedOlympusIndexRoute
}

const AuthenticatedOlympusRouteChildren: AuthenticatedOlympusRouteChildren = {
  AuthenticatedOlympusAtlasSourcesRoute: AuthenticatedOlympusAtlasSourcesRoute,
  AuthenticatedOlympusAuditRoute: AuthenticatedOlympusAuditRoute,
  AuthenticatedOlympusGatesRoute: AuthenticatedOlympusGatesRoute,
  AuthenticatedOlympusIntelligenceRoute: AuthenticatedOlympusIntelligenceRoute,
  AuthenticatedOlympusIrisMemoryRoute: AuthenticatedOlympusIrisMemoryRoute,
  AuthenticatedOlympusQuestionsRoute: AuthenticatedOlympusQuestionsRoute,
  AuthenticatedOlympusScoreMeRoute: AuthenticatedOlympusScoreMeRoute,
  AuthenticatedOlympusSettingsRoute: AuthenticatedOlympusSettingsRoute,
  AuthenticatedOlympusTeamRoute: AuthenticatedOlympusTeamRoute,
  AuthenticatedOlympusUsersRoute: AuthenticatedOlympusUsersRoute,
  AuthenticatedOlympusVaultRoute: AuthenticatedOlympusVaultRoute,
  AuthenticatedOlympusWinThemesRoute: AuthenticatedOlympusWinThemesRoute,
  AuthenticatedOlympusIndexRoute: AuthenticatedOlympusIndexRoute,
}

const AuthenticatedOlympusRouteWithChildren =
  AuthenticatedOlympusRoute._addFileChildren(AuthenticatedOlympusRouteChildren)

interface AuthenticatedMissionsMissionIdRouteChildren {
  AuthenticatedMissionsMissionIdActivityRoute: typeof AuthenticatedMissionsMissionIdActivityRoute
  AuthenticatedMissionsMissionIdBriefRoute: typeof AuthenticatedMissionsMissionIdBriefRoute
  AuthenticatedMissionsMissionIdBriefingRoute: typeof AuthenticatedMissionsMissionIdBriefingRoute
  AuthenticatedMissionsMissionIdIntelligenceRoute: typeof AuthenticatedMissionsMissionIdIntelligenceRoute
  AuthenticatedMissionsMissionIdIrisRoute: typeof AuthenticatedMissionsMissionIdIrisRoute
  AuthenticatedMissionsMissionIdLibraryRoute: typeof AuthenticatedMissionsMissionIdLibraryRoute
  AuthenticatedMissionsMissionIdOperationsRoute: typeof AuthenticatedMissionsMissionIdOperationsRoute
  AuthenticatedMissionsMissionIdOverviewRoute: typeof AuthenticatedMissionsMissionIdOverviewRoute
  AuthenticatedMissionsMissionIdSettingsRoute: typeof AuthenticatedMissionsMissionIdSettingsRoute
  AuthenticatedMissionsMissionIdStudioRoute: typeof AuthenticatedMissionsMissionIdStudioRoute
  AuthenticatedMissionsMissionIdTeamRoute: typeof AuthenticatedMissionsMissionIdTeamRoute
  AuthenticatedMissionsMissionIdIndexRoute: typeof AuthenticatedMissionsMissionIdIndexRoute
  AuthenticatedMissionsMissionIdQuestionsQuestionIdRoute: typeof AuthenticatedMissionsMissionIdQuestionsQuestionIdRoute
  AuthenticatedMissionsMissionIdQuestionsIndexRoute: typeof AuthenticatedMissionsMissionIdQuestionsIndexRoute
}

const AuthenticatedMissionsMissionIdRouteChildren: AuthenticatedMissionsMissionIdRouteChildren =
  {
    AuthenticatedMissionsMissionIdActivityRoute:
      AuthenticatedMissionsMissionIdActivityRoute,
    AuthenticatedMissionsMissionIdBriefRoute:
      AuthenticatedMissionsMissionIdBriefRoute,
    AuthenticatedMissionsMissionIdBriefingRoute:
      AuthenticatedMissionsMissionIdBriefingRoute,
    AuthenticatedMissionsMissionIdIntelligenceRoute:
      AuthenticatedMissionsMissionIdIntelligenceRoute,
    AuthenticatedMissionsMissionIdIrisRoute:
      AuthenticatedMissionsMissionIdIrisRoute,
    AuthenticatedMissionsMissionIdLibraryRoute:
      AuthenticatedMissionsMissionIdLibraryRoute,
    AuthenticatedMissionsMissionIdOperationsRoute:
      AuthenticatedMissionsMissionIdOperationsRoute,
    AuthenticatedMissionsMissionIdOverviewRoute:
      AuthenticatedMissionsMissionIdOverviewRoute,
    AuthenticatedMissionsMissionIdSettingsRoute:
      AuthenticatedMissionsMissionIdSettingsRoute,
    AuthenticatedMissionsMissionIdStudioRoute:
      AuthenticatedMissionsMissionIdStudioRoute,
    AuthenticatedMissionsMissionIdTeamRoute:
      AuthenticatedMissionsMissionIdTeamRoute,
    AuthenticatedMissionsMissionIdIndexRoute:
      AuthenticatedMissionsMissionIdIndexRoute,
    AuthenticatedMissionsMissionIdQuestionsQuestionIdRoute:
      AuthenticatedMissionsMissionIdQuestionsQuestionIdRoute,
    AuthenticatedMissionsMissionIdQuestionsIndexRoute:
      AuthenticatedMissionsMissionIdQuestionsIndexRoute,
  }

const AuthenticatedMissionsMissionIdRouteWithChildren =
  AuthenticatedMissionsMissionIdRoute._addFileChildren(
    AuthenticatedMissionsMissionIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedOlympusRoute: typeof AuthenticatedOlympusRouteWithChildren
  AuthenticatedPathfinderRoute: typeof AuthenticatedPathfinderRoute
  AuthenticatedPipelineHorizonRoute: typeof AuthenticatedPipelineHorizonRoute
  AuthenticatedCommandAlignmentRoute: typeof AuthenticatedCommandAlignmentRoute
  AuthenticatedCommandAlignmentConflictsRoute: typeof AuthenticatedCommandAlignmentConflictsRoute
  AuthenticatedCommandAttentionRoute: typeof AuthenticatedCommandAttentionRoute
  AuthenticatedCommandBroadcastsRoute: typeof AuthenticatedCommandBroadcastsRoute
  AuthenticatedCommandPensDownRoute: typeof AuthenticatedCommandPensDownRoute
  AuthenticatedCommandQuestionHealthRoute: typeof AuthenticatedCommandQuestionHealthRoute
  AuthenticatedCommandScoresRoute: typeof AuthenticatedCommandScoresRoute
  AuthenticatedMissionsMissionIdRoute: typeof AuthenticatedMissionsMissionIdRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedOlympusRoute: AuthenticatedOlympusRouteWithChildren,
  AuthenticatedPathfinderRoute: AuthenticatedPathfinderRoute,
  AuthenticatedPipelineHorizonRoute: AuthenticatedPipelineHorizonRoute,
  AuthenticatedCommandAlignmentRoute: AuthenticatedCommandAlignmentRoute,
  AuthenticatedCommandAlignmentConflictsRoute:
    AuthenticatedCommandAlignmentConflictsRoute,
  AuthenticatedCommandAttentionRoute: AuthenticatedCommandAttentionRoute,
  AuthenticatedCommandBroadcastsRoute: AuthenticatedCommandBroadcastsRoute,
  AuthenticatedCommandPensDownRoute: AuthenticatedCommandPensDownRoute,
  AuthenticatedCommandQuestionHealthRoute:
    AuthenticatedCommandQuestionHealthRoute,
  AuthenticatedCommandScoresRoute: AuthenticatedCommandScoresRoute,
  AuthenticatedMissionsMissionIdRoute:
    AuthenticatedMissionsMissionIdRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiPublicHooksBackfillQuestionEmbeddingsRoute:
    ApiPublicHooksBackfillQuestionEmbeddingsRoute,
  ApiPublicHooksIngestIntelRoute: ApiPublicHooksIngestIntelRoute,
  ApiPublicHooksRefreshIntelligenceRoute:
    ApiPublicHooksRefreshIntelligenceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
