/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPipelineHorizonRouteImport } from './routes/_authenticated/pipeline-horizon'
import { Route as AuthenticatedPathfinderRouteImport } from './routes/_authenticated/pathfinder'
import { Route as AuthenticatedOlympusRouteImport } from './routes/_authenticated/olympus'
import { Route as AuthenticatedIntelligenceQueueRouteImport } from './routes/_authenticated/intelligence-queue'
import { Route as AuthenticatedIntelligenceRouteImport } from './routes/_authenticated/intelligence'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedBriefRoomRouteImport } from './routes/_authenticated/brief-room'
import { Route as AuthenticatedAtriumRouteImport } from './routes/_authenticated/atrium'
import { Route as AuthenticatedOlympusIndexRouteImport } from './routes/_authenticated/olympus/index'
import { Route as AuthenticatedProfileExpertiseRouteImport } from './routes/_authenticated/profile/expertise'
import { Route as AuthenticatedOlympusWriterDeletionRouteImport } from './routes/_authenticated/olympus/writer-deletion'
import { Route as AuthenticatedOlympusWinThemesRouteImport } from './routes/_authenticated/olympus/win-themes'
import { Route as AuthenticatedOlympusVaultRouteImport } from './routes/_authenticated/olympus/vault'
import { Route as AuthenticatedOlympusUsersRouteImport } from './routes/_authenticated/olympus/users'
import { Route as AuthenticatedOlympusTeamRouteImport } from './routes/_authenticated/olympus/team'
import { Route as AuthenticatedOlympusSourceLibraryRouteImport } from './routes/_authenticated/olympus/source-library'
import { Route as AuthenticatedOlympusSourceFinderRouteImport } from './routes/_authenticated/olympus/source-finder'
import { Route as AuthenticatedOlympusSettingsRouteImport } from './routes/_authenticated/olympus/settings'
import { Route as AuthenticatedOlympusSensitivitiesRouteImport } from './routes/_authenticated/olympus/sensitivities'
import { Route as AuthenticatedOlympusScoreMeRouteImport } from './routes/_authenticated/olympus/score-me'
import { Route as AuthenticatedOlympusReviewQueueRouteImport } from './routes/_authenticated/olympus/review-queue'
import { Route as AuthenticatedOlympusQuestionsRouteImport } from './routes/_authenticated/olympus/questions'
import { Route as AuthenticatedOlympusPhiLogRouteImport } from './routes/_authenticated/olympus/phi-log'
import { Route as AuthenticatedOlympusIrisMemoryRouteImport } from './routes/_authenticated/olympus/iris-memory'
import { Route as AuthenticatedOlympusInvitesRouteImport } from './routes/_authenticated/olympus/invites'
import { Route as AuthenticatedOlympusIntelligenceRouteImport } from './routes/_authenticated/olympus/intelligence'
import { Route as AuthenticatedOlympusGatesRouteImport } from './routes/_authenticated/olympus/gates'
import { Route as AuthenticatedOlympusExpertiseRouteImport } from './routes/_authenticated/olympus/expertise'
import { Route as AuthenticatedOlympusDiscoveryHistoryRouteImport } from './routes/_authenticated/olympus/discovery-history'
import { Route as AuthenticatedOlympusConflictsRouteImport } from './routes/_authenticated/olympus/conflicts'
import { Route as AuthenticatedOlympusCanonLibraryRouteImport } from './routes/_authenticated/olympus/canon-library'
import { Route as AuthenticatedOlympusBriefRoomRouteImport } from './routes/_authenticated/olympus/brief-room'
import { Route as AuthenticatedOlympusAuditRouteImport } from './routes/_authenticated/olympus/audit'
import { Route as AuthenticatedOlympusAtlasSourcesRouteImport } from './routes/_authenticated/olympus/atlas-sources'
import { Route as AuthenticatedOlympusAdminsRouteImport } from './routes/_authenticated/olympus/admins'
import { Route as AuthenticatedMissionsMissionIdRouteImport } from './routes/_authenticated/missions/$missionId'
import { Route as AuthenticatedCommandSecurityRouteImport } from './routes/_authenticated/command/security'
import { Route as AuthenticatedCommandScoresRouteImport } from './routes/_authenticated/command/scores'
import { Route as AuthenticatedCommandQuestionHealthRouteImport } from './routes/_authenticated/command/question-health'
import { Route as AuthenticatedCommandPensDownRouteImport } from './routes/_authenticated/command/pens-down'
import { Route as AuthenticatedCommandHealthRouteImport } from './routes/_authenticated/command/health'
import { Route as AuthenticatedCommandBroadcastsRouteImport } from './routes/_authenticated/command/broadcasts'
import { Route as AuthenticatedCommandAttentionRouteImport } from './routes/_authenticated/command/attention'
import { Route as AuthenticatedCommandAlignmentConflictsRouteImport } from './routes/_authenticated/command/alignment-conflicts'
import { Route as AuthenticatedCommandAlignmentRouteImport } from './routes/_authenticated/command/alignment'
import { Route as AuthenticatedMissionsMissionIdIndexRouteImport } from './routes/_authenticated/missions/$missionId/index'
import { Route as ApiPublicHooksRefreshIntelligenceRouteImport } from './routes/api/public/hooks/refresh-intelligence'
import { Route as ApiPublicHooksIngestIntelRouteImport } from './routes/api/public/hooks/ingest-intel'
import { Route as ApiPublicHooksBackfillQuestionEmbeddingsRouteImport } from './routes/api/public/hooks/backfill-question-embeddings'
import { Route as ApiPublicHooksBackfillAtlasEmbeddingsRouteImport } from './routes/api/public/hooks/backfill-atlas-embeddings'
import { Route as AuthenticatedMissionsMissionIdVaultRouteImport } from './routes/_authenticated/missions/$missionId/vault'
import { Route as AuthenticatedMissionsMissionIdTeamRouteImport } from './routes/_authenticated/missions/$missionId/team'
import { Route as AuthenticatedMissionsMissionIdStudioRouteImport } from './routes/_authenticated/missions/$missionId/studio'
import { Route as AuthenticatedMissionsMissionIdSettingsRouteImport } from './routes/_authenticated/missions/$missionId/settings'
import { Route as AuthenticatedMissionsMissionIdOverviewRouteImport } from './routes/_authenticated/missions/$missionId/overview'
import { Route as AuthenticatedMissionsMissionIdOperationsRouteImport } from './routes/_authenticated/missions/$missionId/operations'
import { Route as AuthenticatedMissionsMissionIdLibraryRouteImport } from './routes/_authenticated/missions/$missionId/library'
import { Route as AuthenticatedMissionsMissionIdIrisRouteImport } from './routes/_authenticated/missions/$missionId/iris'
import { Route as AuthenticatedMissionsMissionIdIntelligenceRouteImport } from './routes/_authenticated/missions/$missionId/intelligence'
import { Route as AuthenticatedMissionsMissionIdCommandRouteImport } from './routes/_authenticated/missions/$missionId/command'
import { Route as AuthenticatedMissionsMissionIdBriefingRouteImport } from './routes/_authenticated/missions/$missionId/briefing'
import { Route as AuthenticatedMissionsMissionIdBriefRouteImport } from './routes/_authenticated/missions/$missionId/brief'
import { Route as AuthenticatedMissionsMissionIdActivityRouteImport } from './routes/_authenticated/missions/$missionId/activity'
import { Route as AuthenticatedMissionsMissionIdQuestionsIndexRouteImport } from './routes/_authenticated/missions/$missionId/questions/index'
import { Route as AuthenticatedMissionsMissionIdQuestionsQuestionIdRouteImport } from './routes/_authenticated/missions/$missionId/questions/$questionId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPipelineHorizonRoute =
  AuthenticatedPipelineHorizonRouteImport.update({
    id: '/pipeline-horizon',
    path: '/pipeline-horizon',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPathfinderRoute = AuthenticatedPathfinderRouteImport.update({
  id: '/pathfinder',
  path: '/pathfinder',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOlympusRoute = AuthenticatedOlympusRouteImport.update({
  id: '/olympus',
  path: '/olympus',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIntelligenceQueueRoute =
  AuthenticatedIntelligenceQueueRouteImport.update({
    id: '/intelligence-queue',
    path: '/intelligence-queue',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedIntelligenceRoute =
  AuthenticatedIntelligenceRouteImport.update({
    id: '/intelligence',
    path: '/intelligence',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBriefRoomRoute = AuthenticatedBriefRoomRouteImport.update({
  id: '/brief-room',
  path: '/brief-room',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAtriumRoute = AuthenticatedAtriumRouteImport.update({
  id: '/atrium',
  path: '/atrium',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOlympusIndexRoute =
  AuthenticatedOlympusIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedOlympusRoute,
  } as any)
const AuthenticatedProfileExpertiseRoute =
  AuthenticatedProfileExpertiseRouteImport.update({
    id: '/profile/expertise',
    path: '/profile/expertise',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOlympusWriterDeletionRoute =
  AuthenticatedOlympusWriterDeletionRouteImport.update({
    id: '/writer-deletion',
    path: '/writer-deletion',
    getParentRoute: () => AuthenticatedOlympusRoute,
  } as any)
const AuthenticatedOlympusWinThemesRoute =
  AuthenticatedOlympusWinThemesRouteImport.update({
    id: '/win-themes',
    path: '/win-themes',
    getParentRoute: () => AuthenticatedOlympusRoute,
  } as any)
const AuthenticatedOlympusVaultRoute =
  AuthenticatedOlympusVaultRouteImport.update({
    id: '/vault',
    path: '/vault',
    getParentRoute: () => AuthenticatedOlympusRoute,
  } as any)
const AuthenticatedOlympusUsersRoute =
  AuthenticatedOlympusUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedOlympusRoute,
  } as any)
const AuthenticatedOlympusTeamRoute =
  AuthenticatedOlympusTeamRouteImport.update({
    id: '/team',
    path: '/team',
    getParentRoute: () => AuthenticatedOlympusRoute,
  } as any)
const AuthenticatedOlympusSourceLibraryRoute =
  AuthenticatedOlympusSourceLibraryRouteImport.update({
    id: '/source-library',
    path: '/source-library',
    getParentRoute: () => AuthenticatedOlympusRoute,
  } as any)
const AuthenticatedOlympusSourceFinderRoute =
  AuthenticatedOlympusSourceFinderRouteImport.update({
    id: '/source-finder',
    path: '/source-finder',
    getParentRoute: () => AuthenticatedOlympusRoute,
  } as any)
const AuthenticatedOlympusSettingsRoute =
  AuthenticatedOlympusSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedOlympusRoute,
  } as any)
const AuthenticatedOlympusSensitivitiesRoute =
  AuthenticatedOlympusSensitivitiesRouteImport.update({
    id: '/sensitivities',
    path: '/sensitivities',
    getParentRoute: () => AuthenticatedOlympusRoute,
  } as any)
const AuthenticatedOlympusScoreMeRoute =
  AuthenticatedOlympusScoreMeRouteImport.update({
    id: '/score-me',
    path: '/score-me',
    getParentRoute: () => AuthenticatedOlympusRoute,
  } as any)
const AuthenticatedOlympusReviewQueueRoute =
  AuthenticatedOlympusReviewQueueRouteImport.update({
    id: '/review-queue',
    path: '/review-queue',
    getParentRoute: () => AuthenticatedOlympusRoute,
  } as any)
const AuthenticatedOlympusQuestionsRoute =
  AuthenticatedOlympusQuestionsRouteImport.update({
    id: '/questions',
    path: '/questions',
    getParentRoute: () => AuthenticatedOlympusRoute,
  } as any)
const AuthenticatedOlympusPhiLogRoute =
  AuthenticatedOlympusPhiLogRouteImport.update({
    id: '/phi-log',
    path: '/phi-log',
    getParentRoute: () => AuthenticatedOlympusRoute,
  } as any)
const AuthenticatedOlympusIrisMemoryRoute =
  AuthenticatedOlympusIrisMemoryRouteImport.update({
    id: '/iris-memory',
    path: '/iris-memory',
    getParentRoute: () => AuthenticatedOlympusRoute,
  } as any)
const AuthenticatedOlympusInvitesRoute =
  AuthenticatedOlympusInvitesRouteImport.update({
    id: '/invites',
    path: '/invites',
    getParentRoute: () => AuthenticatedOlympusRoute,
  } as any)
const AuthenticatedOlympusIntelligenceRoute =
  AuthenticatedOlympusIntelligenceRouteImport.update({
    id: '/intelligence',
    path: '/intelligence',
    getParentRoute: () => AuthenticatedOlympusRoute,
  } as any)
const AuthenticatedOlympusGatesRoute =
  AuthenticatedOlympusGatesRouteImport.update({
    id: '/gates',
    path: '/gates',
    getParentRoute: () => AuthenticatedOlympusRoute,
  } as any)
const AuthenticatedOlympusExpertiseRoute =
  AuthenticatedOlympusExpertiseRouteImport.update({
    id: '/expertise',
    path: '/expertise',
    getParentRoute: () => AuthenticatedOlympusRoute,
  } as any)
const AuthenticatedOlympusDiscoveryHistoryRoute =
  AuthenticatedOlympusDiscoveryHistoryRouteImport.update({
    id: '/discovery-history',
    path: '/discovery-history',
    getParentRoute: () => AuthenticatedOlympusRoute,
  } as any)
const AuthenticatedOlympusConflictsRoute =
  AuthenticatedOlympusConflictsRouteImport.update({
    id: '/conflicts',
    path: '/conflicts',
    getParentRoute: () => AuthenticatedOlympusRoute,
  } as any)
const AuthenticatedOlympusCanonLibraryRoute =
  AuthenticatedOlympusCanonLibraryRouteImport.update({
    id: '/canon-library',
    path: '/canon-library',
    getParentRoute: () => AuthenticatedOlympusRoute,
  } as any)
const AuthenticatedOlympusBriefRoomRoute =
  AuthenticatedOlympusBriefRoomRouteImport.update({
    id: '/brief-room',
    path: '/brief-room',
    getParentRoute: () => AuthenticatedOlympusRoute,
  } as any)
const AuthenticatedOlympusAuditRoute =
  AuthenticatedOlympusAuditRouteImport.update({
    id: '/audit',
    path: '/audit',
    getParentRoute: () => AuthenticatedOlympusRoute,
  } as any)
const AuthenticatedOlympusAtlasSourcesRoute =
  AuthenticatedOlympusAtlasSourcesRouteImport.update({
    id: '/atlas-sources',
    path: '/atlas-sources',
    getParentRoute: () => AuthenticatedOlympusRoute,
  } as any)
const AuthenticatedOlympusAdminsRoute =
  AuthenticatedOlympusAdminsRouteImport.update({
    id: '/admins',
    path: '/admins',
    getParentRoute: () => AuthenticatedOlympusRoute,
  } as any)
const AuthenticatedMissionsMissionIdRoute =
  AuthenticatedMissionsMissionIdRouteImport.update({
    id: '/missions/$missionId',
    path: '/missions/$missionId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCommandSecurityRoute =
  AuthenticatedCommandSecurityRouteImport.update({
    id: '/command/security',
    path: '/command/security',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCommandScoresRoute =
  AuthenticatedCommandScoresRouteImport.update({
    id: '/command/scores',
    path: '/command/scores',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCommandQuestionHealthRoute =
  AuthenticatedCommandQuestionHealthRouteImport.update({
    id: '/command/question-health',
    path: '/command/question-health',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCommandPensDownRoute =
  AuthenticatedCommandPensDownRouteImport.update({
    id: '/command/pens-down',
    path: '/command/pens-down',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCommandHealthRoute =
  AuthenticatedCommandHealthRouteImport.update({
    id: '/command/health',
    path: '/command/health',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCommandBroadcastsRoute =
  AuthenticatedCommandBroadcastsRouteImport.update({
    id: '/command/broadcasts',
    path: '/command/broadcasts',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCommandAttentionRoute =
  AuthenticatedCommandAttentionRouteImport.update({
    id: '/command/attention',
    path: '/command/attention',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCommandAlignmentConflictsRoute =
  AuthenticatedCommandAlignmentConflictsRouteImport.update({
    id: '/command/alignment-conflicts',
    path: '/command/alignment-conflicts',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCommandAlignmentRoute =
  AuthenticatedCommandAlignmentRouteImport.update({
    id: '/command/alignment',
    path: '/command/alignment',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMissionsMissionIdIndexRoute =
  AuthenticatedMissionsMissionIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedMissionsMissionIdRoute,
  } as any)
const ApiPublicHooksRefreshIntelligenceRoute =
  ApiPublicHooksRefreshIntelligenceRouteImport.update({
    id: '/api/public/hooks/refresh-intelligence',
    path: '/api/public/hooks/refresh-intelligence',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksIngestIntelRoute =
  ApiPublicHooksIngestIntelRouteImport.update({
    id: '/api/public/hooks/ingest-intel',
    path: '/api/public/hooks/ingest-intel',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksBackfillQuestionEmbeddingsRoute =
  ApiPublicHooksBackfillQuestionEmbeddingsRouteImport.update({
    id: '/api/public/hooks/backfill-question-embeddings',
    path: '/api/public/hooks/backfill-question-embeddings',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksBackfillAtlasEmbeddingsRoute =
  ApiPublicHooksBackfillAtlasEmbeddingsRouteImport.update({
    id: '/api/public/hooks/backfill-atlas-embeddings',
    path: '/api/public/hooks/backfill-atlas-embeddings',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedMissionsMissionIdVaultRoute =
  AuthenticatedMissionsMissionIdVaultRouteImport.update({
    id: '/vault',
    path: '/vault',
    getParentRoute: () => AuthenticatedMissionsMissionIdRoute,
  } as any)
const AuthenticatedMissionsMissionIdTeamRoute =
  AuthenticatedMissionsMissionIdTeamRouteImport.update({
    id: '/team',
    path: '/team',
    getParentRoute: () => AuthenticatedMissionsMissionIdRoute,
  } as any)
const AuthenticatedMissionsMissionIdStudioRoute =
  AuthenticatedMissionsMissionIdStudioRouteImport.update({
    id: '/studio',
    path: '/studio',
    getParentRoute: () => AuthenticatedMissionsMissionIdRoute,
  } as any)
const AuthenticatedMissionsMissionIdSettingsRoute =
  AuthenticatedMissionsMissionIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedMissionsMissionIdRoute,
  } as any)
const AuthenticatedMissionsMissionIdOverviewRoute =
  AuthenticatedMissionsMissionIdOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => AuthenticatedMissionsMissionIdRoute,
  } as any)
const AuthenticatedMissionsMissionIdOperationsRoute =
  AuthenticatedMissionsMissionIdOperationsRouteImport.update({
    id: '/operations',
    path: '/operations',
    getParentRoute: () => AuthenticatedMissionsMissionIdRoute,
  } as any)
const AuthenticatedMissionsMissionIdLibraryRoute =
  AuthenticatedMissionsMissionIdLibraryRouteImport.update({
    id: '/library',
    path: '/library',
    getParentRoute: () => AuthenticatedMissionsMissionIdRoute,
  } as any)
const AuthenticatedMissionsMissionIdIrisRoute =
  AuthenticatedMissionsMissionIdIrisRouteImport.update({
    id: '/iris',
    path: '/iris',
    getParentRoute: () => AuthenticatedMissionsMissionIdRoute,
  } as any)
const AuthenticatedMissionsMissionIdIntelligenceRoute =
  AuthenticatedMissionsMissionIdIntelligenceRouteImport.update({
    id: '/intelligence',
    path: '/intelligence',
    getParentRoute: () => AuthenticatedMissionsMissionIdRoute,
  } as any)
const AuthenticatedMissionsMissionIdCommandRoute =
  AuthenticatedMissionsMissionIdCommandRouteImport.update({
    id: '/command',
    path: '/command',
    getParentRoute: () => AuthenticatedMissionsMissionIdRoute,
  } as any)
const AuthenticatedMissionsMissionIdBriefingRoute =
  AuthenticatedMissionsMissionIdBriefingRouteImport.update({
    id: '/briefing',
    path: '/briefing',
    getParentRoute: () => AuthenticatedMissionsMissionIdRoute,
  } as any)
const AuthenticatedMissionsMissionIdBriefRoute =
  AuthenticatedMissionsMissionIdBriefRouteImport.update({
    id: '/brief',
    path: '/brief',
    getParentRoute: () => AuthenticatedMissionsMissionIdRoute,
  } as any)
const AuthenticatedMissionsMissionIdActivityRoute =
  AuthenticatedMissionsMissionIdActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => AuthenticatedMissionsMissionIdRoute,
  } as any)
const AuthenticatedMissionsMissionIdQuestionsIndexRoute =
  AuthenticatedMissionsMissionIdQuestionsIndexRouteImport.update({
    id: '/questions/',
    path: '/questions/',
    getParentRoute: () => AuthenticatedMissionsMissionIdRoute,
  } as any)
const AuthenticatedMissionsMissionIdQuestionsQuestionIdRoute =
  AuthenticatedMissionsMissionIdQuestionsQuestionIdRouteImport.update({
    id: '/questions/$questionId',
    path: '/questions/$questionId',
    getParentRoute: () => AuthenticatedMissionsMissionIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/atrium': typeof AuthenticatedAtriumRoute
  '/brief-room': typeof AuthenticatedBriefRoomRoute
  '/home': typeof AuthenticatedHomeRoute
  '/intelligence': typeof AuthenticatedIntelligenceRoute
  '/intelligence-queue': typeof AuthenticatedIntelligenceQueueRoute
  '/olympus': typeof AuthenticatedOlympusRouteWithChildren
  '/pathfinder': typeof AuthenticatedPathfinderRoute
  '/pipeline-horizon': typeof AuthenticatedPipelineHorizonRoute
  '/command/alignment': typeof AuthenticatedCommandAlignmentRoute
  '/command/alignment-conflicts': typeof AuthenticatedCommandAlignmentConflictsRoute
  '/command/attention': typeof AuthenticatedCommandAttentionRoute
  '/command/broadcasts': typeof AuthenticatedCommandBroadcastsRoute
  '/command/health': typeof AuthenticatedCommandHealthRoute
  '/command/pens-down': typeof AuthenticatedCommandPensDownRoute
  '/command/question-health': typeof AuthenticatedCommandQuestionHealthRoute
  '/command/scores': typeof AuthenticatedCommandScoresRoute
  '/command/security': typeof AuthenticatedCommandSecurityRoute
  '/missions/$missionId': typeof AuthenticatedMissionsMissionIdRouteWithChildren
  '/olympus/admins': typeof AuthenticatedOlympusAdminsRoute
  '/olympus/atlas-sources': typeof AuthenticatedOlympusAtlasSourcesRoute
  '/olympus/audit': typeof AuthenticatedOlympusAuditRoute
  '/olympus/brief-room': typeof AuthenticatedOlympusBriefRoomRoute
  '/olympus/canon-library': typeof AuthenticatedOlympusCanonLibraryRoute
  '/olympus/conflicts': typeof AuthenticatedOlympusConflictsRoute
  '/olympus/discovery-history': typeof AuthenticatedOlympusDiscoveryHistoryRoute
  '/olympus/expertise': typeof AuthenticatedOlympusExpertiseRoute
  '/olympus/gates': typeof AuthenticatedOlympusGatesRoute
  '/olympus/intelligence': typeof AuthenticatedOlympusIntelligenceRoute
  '/olympus/invites': typeof AuthenticatedOlympusInvitesRoute
  '/olympus/iris-memory': typeof AuthenticatedOlympusIrisMemoryRoute
  '/olympus/phi-log': typeof AuthenticatedOlympusPhiLogRoute
  '/olympus/questions': typeof AuthenticatedOlympusQuestionsRoute
  '/olympus/review-queue': typeof AuthenticatedOlympusReviewQueueRoute
  '/olympus/score-me': typeof AuthenticatedOlympusScoreMeRoute
  '/olympus/sensitivities': typeof AuthenticatedOlympusSensitivitiesRoute
  '/olympus/settings': typeof AuthenticatedOlympusSettingsRoute
  '/olympus/source-finder': typeof AuthenticatedOlympusSourceFinderRoute
  '/olympus/source-library': typeof AuthenticatedOlympusSourceLibraryRoute
  '/olympus/team': typeof AuthenticatedOlympusTeamRoute
  '/olympus/users': typeof AuthenticatedOlympusUsersRoute
  '/olympus/vault': typeof AuthenticatedOlympusVaultRoute
  '/olympus/win-themes': typeof AuthenticatedOlympusWinThemesRoute
  '/olympus/writer-deletion': typeof AuthenticatedOlympusWriterDeletionRoute
  '/profile/expertise': typeof AuthenticatedProfileExpertiseRoute
  '/olympus/': typeof AuthenticatedOlympusIndexRoute
  '/missions/$missionId/activity': typeof AuthenticatedMissionsMissionIdActivityRoute
  '/missions/$missionId/brief': typeof AuthenticatedMissionsMissionIdBriefRoute
  '/missions/$missionId/briefing': typeof AuthenticatedMissionsMissionIdBriefingRoute
  '/missions/$missionId/command': typeof AuthenticatedMissionsMissionIdCommandRoute
  '/missions/$missionId/intelligence': typeof AuthenticatedMissionsMissionIdIntelligenceRoute
  '/missions/$missionId/iris': typeof AuthenticatedMissionsMissionIdIrisRoute
  '/missions/$missionId/library': typeof AuthenticatedMissionsMissionIdLibraryRoute
  '/missions/$missionId/operations': typeof AuthenticatedMissionsMissionIdOperationsRoute
  '/missions/$missionId/overview': typeof AuthenticatedMissionsMissionIdOverviewRoute
  '/missions/$missionId/settings': typeof AuthenticatedMissionsMissionIdSettingsRoute
  '/missions/$missionId/studio': typeof AuthenticatedMissionsMissionIdStudioRoute
  '/missions/$missionId/team': typeof AuthenticatedMissionsMissionIdTeamRoute
  '/missions/$missionId/vault': typeof AuthenticatedMissionsMissionIdVaultRoute
  '/api/public/hooks/backfill-atlas-embeddings': typeof ApiPublicHooksBackfillAtlasEmbeddingsRoute
  '/api/public/hooks/backfill-question-embeddings': typeof ApiPublicHooksBackfillQuestionEmbeddingsRoute
  '/api/public/hooks/ingest-intel': typeof ApiPublicHooksIngestIntelRoute
  '/api/public/hooks/refresh-intelligence': typeof ApiPublicHooksRefreshIntelligenceRoute
  '/missions/$missionId/': typeof AuthenticatedMissionsMissionIdIndexRoute
  '/missions/$missionId/questions/$questionId': typeof AuthenticatedMissionsMissionIdQuestionsQuestionIdRoute
  '/missions/$missionId/questions/': typeof AuthenticatedMissionsMissionIdQuestionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/atrium': typeof AuthenticatedAtriumRoute
  '/brief-room': typeof AuthenticatedBriefRoomRoute
  '/home': typeof AuthenticatedHomeRoute
  '/intelligence': typeof AuthenticatedIntelligenceRoute
  '/intelligence-queue': typeof AuthenticatedIntelligenceQueueRoute
  '/pathfinder': typeof AuthenticatedPathfinderRoute
  '/pipeline-horizon': typeof AuthenticatedPipelineHorizonRoute
  '/command/alignment': typeof AuthenticatedCommandAlignmentRoute
  '/command/alignment-conflicts': typeof AuthenticatedCommandAlignmentConflictsRoute
  '/command/attention': typeof AuthenticatedCommandAttentionRoute
  '/command/broadcasts': typeof AuthenticatedCommandBroadcastsRoute
  '/command/health': typeof AuthenticatedCommandHealthRoute
  '/command/pens-down': typeof AuthenticatedCommandPensDownRoute
  '/command/question-health': typeof AuthenticatedCommandQuestionHealthRoute
  '/command/scores': typeof AuthenticatedCommandScoresRoute
  '/command/security': typeof AuthenticatedCommandSecurityRoute
  '/olympus/admins': typeof AuthenticatedOlympusAdminsRoute
  '/olympus/atlas-sources': typeof AuthenticatedOlympusAtlasSourcesRoute
  '/olympus/audit': typeof AuthenticatedOlympusAuditRoute
  '/olympus/brief-room': typeof AuthenticatedOlympusBriefRoomRoute
  '/olympus/canon-library': typeof AuthenticatedOlympusCanonLibraryRoute
  '/olympus/conflicts': typeof AuthenticatedOlympusConflictsRoute
  '/olympus/discovery-history': typeof AuthenticatedOlympusDiscoveryHistoryRoute
  '/olympus/expertise': typeof AuthenticatedOlympusExpertiseRoute
  '/olympus/gates': typeof AuthenticatedOlympusGatesRoute
  '/olympus/intelligence': typeof AuthenticatedOlympusIntelligenceRoute
  '/olympus/invites': typeof AuthenticatedOlympusInvitesRoute
  '/olympus/iris-memory': typeof AuthenticatedOlympusIrisMemoryRoute
  '/olympus/phi-log': typeof AuthenticatedOlympusPhiLogRoute
  '/olympus/questions': typeof AuthenticatedOlympusQuestionsRoute
  '/olympus/review-queue': typeof AuthenticatedOlympusReviewQueueRoute
  '/olympus/score-me': typeof AuthenticatedOlympusScoreMeRoute
  '/olympus/sensitivities': typeof AuthenticatedOlympusSensitivitiesRoute
  '/olympus/settings': typeof AuthenticatedOlympusSettingsRoute
  '/olympus/source-finder': typeof AuthenticatedOlympusSourceFinderRoute
  '/olympus/source-library': typeof AuthenticatedOlympusSourceLibraryRoute
  '/olympus/team': typeof AuthenticatedOlympusTeamRoute
  '/olympus/users': typeof AuthenticatedOlympusUsersRoute
  '/olympus/vault': typeof AuthenticatedOlympusVaultRoute
  '/olympus/win-themes': typeof AuthenticatedOlympusWinThemesRoute
  '/olympus/writer-deletion': typeof AuthenticatedOlympusWriterDeletionRoute
  '/profile/expertise': typeof AuthenticatedProfileExpertiseRoute
  '/olympus': typeof AuthenticatedOlympusIndexRoute
  '/missions/$missionId/activity': typeof AuthenticatedMissionsMissionIdActivityRoute
  '/missions/$missionId/brief': typeof AuthenticatedMissionsMissionIdBriefRoute
  '/missions/$missionId/briefing': typeof AuthenticatedMissionsMissionIdBriefingRoute
  '/missions/$missionId/command': typeof AuthenticatedMissionsMissionIdCommandRoute
  '/missions/$missionId/intelligence': typeof AuthenticatedMissionsMissionIdIntelligenceRoute
  '/missions/$missionId/iris': typeof AuthenticatedMissionsMissionIdIrisRoute
  '/missions/$missionId/library': typeof AuthenticatedMissionsMissionIdLibraryRoute
  '/missions/$missionId/operations': typeof AuthenticatedMissionsMissionIdOperationsRoute
  '/missions/$missionId/overview': typeof AuthenticatedMissionsMissionIdOverviewRoute
  '/missions/$missionId/settings': typeof AuthenticatedMissionsMissionIdSettingsRoute
  '/missions/$missionId/studio': typeof AuthenticatedMissionsMissionIdStudioRoute
  '/missions/$missionId/team': typeof AuthenticatedMissionsMissionIdTeamRoute
  '/missions/$missionId/vault': typeof AuthenticatedMissionsMissionIdVaultRoute
  '/api/public/hooks/backfill-atlas-embeddings': typeof ApiPublicHooksBackfillAtlasEmbeddingsRoute
  '/api/public/hooks/backfill-question-embeddings': typeof ApiPublicHooksBackfillQuestionEmbeddingsRoute
  '/api/public/hooks/ingest-intel': typeof ApiPublicHooksIngestIntelRoute
  '/api/public/hooks/refresh-intelligence': typeof ApiPublicHooksRefreshIntelligenceRoute
  '/missions/$missionId': typeof AuthenticatedMissionsMissionIdIndexRoute
  '/missions/$missionId/questions/$questionId': typeof AuthenticatedMissionsMissionIdQuestionsQuestionIdRoute
  '/missions/$missionId/questions': typeof AuthenticatedMissionsMissionIdQuestionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/atrium': typeof AuthenticatedAtriumRoute
  '/_authenticated/brief-room': typeof AuthenticatedBriefRoomRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/intelligence': typeof AuthenticatedIntelligenceRoute
  '/_authenticated/intelligence-queue': typeof AuthenticatedIntelligenceQueueRoute
  '/_authenticated/olympus': typeof AuthenticatedOlympusRouteWithChildren
  '/_authenticated/pathfinder': typeof AuthenticatedPathfinderRoute
  '/_authenticated/pipeline-horizon': typeof AuthenticatedPipelineHorizonRoute
  '/_authenticated/command/alignment': typeof AuthenticatedCommandAlignmentRoute
  '/_authenticated/command/alignment-conflicts': typeof AuthenticatedCommandAlignmentConflictsRoute
  '/_authenticated/command/attention': typeof AuthenticatedCommandAttentionRoute
  '/_authenticated/command/broadcasts': typeof AuthenticatedCommandBroadcastsRoute
  '/_authenticated/command/health': typeof AuthenticatedCommandHealthRoute
  '/_authenticated/command/pens-down': typeof AuthenticatedCommandPensDownRoute
  '/_authenticated/command/question-health': typeof AuthenticatedCommandQuestionHealthRoute
  '/_authenticated/command/scores': typeof AuthenticatedCommandScoresRoute
  '/_authenticated/command/security': typeof AuthenticatedCommandSecurityRoute
  '/_authenticated/missions/$missionId': typeof AuthenticatedMissionsMissionIdRouteWithChildren
  '/_authenticated/olympus/admins': typeof AuthenticatedOlympusAdminsRoute
  '/_authenticated/olympus/atlas-sources': typeof AuthenticatedOlympusAtlasSourcesRoute
  '/_authenticated/olympus/audit': typeof AuthenticatedOlympusAuditRoute
  '/_authenticated/olympus/brief-room': typeof AuthenticatedOlympusBriefRoomRoute
  '/_authenticated/olympus/canon-library': typeof AuthenticatedOlympusCanonLibraryRoute
  '/_authenticated/olympus/conflicts': typeof AuthenticatedOlympusConflictsRoute
  '/_authenticated/olympus/discovery-history': typeof AuthenticatedOlympusDiscoveryHistoryRoute
  '/_authenticated/olympus/expertise': typeof AuthenticatedOlympusExpertiseRoute
  '/_authenticated/olympus/gates': typeof AuthenticatedOlympusGatesRoute
  '/_authenticated/olympus/intelligence': typeof AuthenticatedOlympusIntelligenceRoute
  '/_authenticated/olympus/invites': typeof AuthenticatedOlympusInvitesRoute
  '/_authenticated/olympus/iris-memory': typeof AuthenticatedOlympusIrisMemoryRoute
  '/_authenticated/olympus/phi-log': typeof AuthenticatedOlympusPhiLogRoute
  '/_authenticated/olympus/questions': typeof AuthenticatedOlympusQuestionsRoute
  '/_authenticated/olympus/review-queue': typeof AuthenticatedOlympusReviewQueueRoute
  '/_authenticated/olympus/score-me': typeof AuthenticatedOlympusScoreMeRoute
  '/_authenticated/olympus/sensitivities': typeof AuthenticatedOlympusSensitivitiesRoute
  '/_authenticated/olympus/settings': typeof AuthenticatedOlympusSettingsRoute
  '/_authenticated/olympus/source-finder': typeof AuthenticatedOlympusSourceFinderRoute
  '/_authenticated/olympus/source-library': typeof AuthenticatedOlympusSourceLibraryRoute
  '/_authenticated/olympus/team': typeof AuthenticatedOlympusTeamRoute
  '/_authenticated/olympus/users': typeof AuthenticatedOlympusUsersRoute
  '/_authenticated/olympus/vault': typeof AuthenticatedOlympusVaultRoute
  '/_authenticated/olympus/win-themes': typeof AuthenticatedOlympusWinThemesRoute
  '/_authenticated/olympus/writer-deletion': typeof AuthenticatedOlympusWriterDeletionRoute
  '/_authenticated/profile/expertise': typeof AuthenticatedProfileExpertiseRoute
  '/_authenticated/olympus/': typeof AuthenticatedOlympusIndexRoute
  '/_authenticated/missions/$missionId/activity': typeof AuthenticatedMissionsMissionIdActivityRoute
  '/_authenticated/missions/$missionId/brief': typeof AuthenticatedMissionsMissionIdBriefRoute
  '/_authenticated/missions/$missionId/briefing': typeof AuthenticatedMissionsMissionIdBriefingRoute
  '/_authenticated/missions/$missionId/command': typeof AuthenticatedMissionsMissionIdCommandRoute
  '/_authenticated/missions/$missionId/intelligence': typeof AuthenticatedMissionsMissionIdIntelligenceRoute
  '/_authenticated/missions/$missionId/iris': typeof AuthenticatedMissionsMissionIdIrisRoute
  '/_authenticated/missions/$missionId/library': typeof AuthenticatedMissionsMissionIdLibraryRoute
  '/_authenticated/missions/$missionId/operations': typeof AuthenticatedMissionsMissionIdOperationsRoute
  '/_authenticated/missions/$missionId/overview': typeof AuthenticatedMissionsMissionIdOverviewRoute
  '/_authenticated/missions/$missionId/settings': typeof AuthenticatedMissionsMissionIdSettingsRoute
  '/_authenticated/missions/$missionId/studio': typeof AuthenticatedMissionsMissionIdStudioRoute
  '/_authenticated/missions/$missionId/team': typeof AuthenticatedMissionsMissionIdTeamRoute
  '/_authenticated/missions/$missionId/vault': typeof AuthenticatedMissionsMissionIdVaultRoute
  '/api/public/hooks/backfill-atlas-embeddings': typeof ApiPublicHooksBackfillAtlasEmbeddingsRoute
  '/api/public/hooks/backfill-question-embeddings': typeof ApiPublicHooksBackfillQuestionEmbeddingsRoute
  '/api/public/hooks/ingest-intel': typeof ApiPublicHooksIngestIntelRoute
  '/api/public/hooks/refresh-intelligence': typeof ApiPublicHooksRefreshIntelligenceRoute
  '/_authenticated/missions/$missionId/': typeof AuthenticatedMissionsMissionIdIndexRoute
  '/_authenticated/missions/$missionId/questions/$questionId': typeof AuthenticatedMissionsMissionIdQuestionsQuestionIdRoute
  '/_authenticated/missions/$missionId/questions/': typeof AuthenticatedMissionsMissionIdQuestionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/atrium'
    | '/brief-room'
    | '/home'
    | '/intelligence'
    | '/intelligence-queue'
    | '/olympus'
    | '/pathfinder'
    | '/pipeline-horizon'
    | '/command/alignment'
    | '/command/alignment-conflicts'
    | '/command/attention'
    | '/command/broadcasts'
    | '/command/health'
    | '/command/pens-down'
    | '/command/question-health'
    | '/command/scores'
    | '/command/security'
    | '/missions/$missionId'
    | '/olympus/admins'
    | '/olympus/atlas-sources'
    | '/olympus/audit'
    | '/olympus/brief-room'
    | '/olympus/canon-library'
    | '/olympus/conflicts'
    | '/olympus/discovery-history'
    | '/olympus/expertise'
    | '/olympus/gates'
    | '/olympus/intelligence'
    | '/olympus/invites'
    | '/olympus/iris-memory'
    | '/olympus/phi-log'
    | '/olympus/questions'
    | '/olympus/review-queue'
    | '/olympus/score-me'
    | '/olympus/sensitivities'
    | '/olympus/settings'
    | '/olympus/source-finder'
    | '/olympus/source-library'
    | '/olympus/team'
    | '/olympus/users'
    | '/olympus/vault'
    | '/olympus/win-themes'
    | '/olympus/writer-deletion'
    | '/profile/expertise'
    | '/olympus/'
    | '/missions/$missionId/activity'
    | '/missions/$missionId/brief'
    | '/missions/$missionId/briefing'
    | '/missions/$missionId/command'
    | '/missions/$missionId/intelligence'
    | '/missions/$missionId/iris'
    | '/missions/$missionId/library'
    | '/missions/$missionId/operations'
    | '/missions/$missionId/overview'
    | '/missions/$missionId/settings'
    | '/missions/$missionId/studio'
    | '/missions/$missionId/team'
    | '/missions/$missionId/vault'
    | '/api/public/hooks/backfill-atlas-embeddings'
    | '/api/public/hooks/backfill-question-embeddings'
    | '/api/public/hooks/ingest-intel'
    | '/api/public/hooks/refresh-intelligence'
    | '/missions/$missionId/'
    | '/missions/$missionId/questions/$questionId'
    | '/missions/$missionId/questions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/atrium'
    | '/brief-room'
    | '/home'
    | '/intelligence'
    | '/intelligence-queue'
    | '/pathfinder'
    | '/pipeline-horizon'
    | '/command/alignment'
    | '/command/alignment-conflicts'
    | '/command/attention'
    | '/command/broadcasts'
    | '/command/health'
    | '/command/pens-down'
    | '/command/question-health'
    | '/command/scores'
    | '/command/security'
    | '/olympus/admins'
    | '/olympus/atlas-sources'
    | '/olympus/audit'
    | '/olympus/brief-room'
    | '/olympus/canon-library'
    | '/olympus/conflicts'
    | '/olympus/discovery-history'
    | '/olympus/expertise'
    | '/olympus/gates'
    | '/olympus/intelligence'
    | '/olympus/invites'
    | '/olympus/iris-memory'
    | '/olympus/phi-log'
    | '/olympus/questions'
    | '/olympus/review-queue'
    | '/olympus/score-me'
    | '/olympus/sensitivities'
    | '/olympus/settings'
    | '/olympus/source-finder'
    | '/olympus/source-library'
    | '/olympus/team'
    | '/olympus/users'
    | '/olympus/vault'
    | '/olympus/win-themes'
    | '/olympus/writer-deletion'
    | '/profile/expertise'
    | '/olympus'
    | '/missions/$missionId/activity'
    | '/missions/$missionId/brief'
    | '/missions/$missionId/briefing'
    | '/missions/$missionId/command'
    | '/missions/$missionId/intelligence'
    | '/missions/$missionId/iris'
    | '/missions/$missionId/library'
    | '/missions/$missionId/operations'
    | '/missions/$missionId/overview'
    | '/missions/$missionId/settings'
    | '/missions/$missionId/studio'
    | '/missions/$missionId/team'
    | '/missions/$missionId/vault'
    | '/api/public/hooks/backfill-atlas-embeddings'
    | '/api/public/hooks/backfill-question-embeddings'
    | '/api/public/hooks/ingest-intel'
    | '/api/public/hooks/refresh-intelligence'
    | '/missions/$missionId'
    | '/missions/$missionId/questions/$questionId'
    | '/missions/$missionId/questions'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/atrium'
    | '/_authenticated/brief-room'
    | '/_authenticated/home'
    | '/_authenticated/intelligence'
    | '/_authenticated/intelligence-queue'
    | '/_authenticated/olympus'
    | '/_authenticated/pathfinder'
    | '/_authenticated/pipeline-horizon'
    | '/_authenticated/command/alignment'
    | '/_authenticated/command/alignment-conflicts'
    | '/_authenticated/command/attention'
    | '/_authenticated/command/broadcasts'
    | '/_authenticated/command/health'
    | '/_authenticated/command/pens-down'
    | '/_authenticated/command/question-health'
    | '/_authenticated/command/scores'
    | '/_authenticated/command/security'
    | '/_authenticated/missions/$missionId'
    | '/_authenticated/olympus/admins'
    | '/_authenticated/olympus/atlas-sources'
    | '/_authenticated/olympus/audit'
    | '/_authenticated/olympus/brief-room'
    | '/_authenticated/olympus/canon-library'
    | '/_authenticated/olympus/conflicts'
    | '/_authenticated/olympus/discovery-history'
    | '/_authenticated/olympus/expertise'
    | '/_authenticated/olympus/gates'
    | '/_authenticated/olympus/intelligence'
    | '/_authenticated/olympus/invites'
    | '/_authenticated/olympus/iris-memory'
    | '/_authenticated/olympus/phi-log'
    | '/_authenticated/olympus/questions'
    | '/_authenticated/olympus/review-queue'
    | '/_authenticated/olympus/score-me'
    | '/_authenticated/olympus/sensitivities'
    | '/_authenticated/olympus/settings'
    | '/_authenticated/olympus/source-finder'
    | '/_authenticated/olympus/source-library'
    | '/_authenticated/olympus/team'
    | '/_authenticated/olympus/users'
    | '/_authenticated/olympus/vault'
    | '/_authenticated/olympus/win-themes'
    | '/_authenticated/olympus/writer-deletion'
    | '/_authenticated/profile/expertise'
    | '/_authenticated/olympus/'
    | '/_authenticated/missions/$missionId/activity'
    | '/_authenticated/missions/$missionId/brief'
    | '/_authenticated/missions/$missionId/briefing'
    | '/_authenticated/missions/$missionId/command'
    | '/_authenticated/missions/$missionId/intelligence'
    | '/_authenticated/missions/$missionId/iris'
    | '/_authenticated/missions/$missionId/library'
    | '/_authenticated/missions/$missionId/operations'
    | '/_authenticated/missions/$missionId/overview'
    | '/_authenticated/missions/$missionId/settings'
    | '/_authenticated/missions/$missionId/studio'
    | '/_authenticated/missions/$missionId/team'
    | '/_authenticated/missions/$missionId/vault'
    | '/api/public/hooks/backfill-atlas-embeddings'
    | '/api/public/hooks/backfill-question-embeddings'
    | '/api/public/hooks/ingest-intel'
    | '/api/public/hooks/refresh-intelligence'
    | '/_authenticated/missions/$missionId/'
    | '/_authenticated/missions/$missionId/questions/$questionId'
    | '/_authenticated/missions/$missionId/questions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiPublicHooksBackfillAtlasEmbeddingsRoute: typeof ApiPublicHooksBackfillAtlasEmbeddingsRoute
  ApiPublicHooksBackfillQuestionEmbeddingsRoute: typeof ApiPublicHooksBackfillQuestionEmbeddingsRoute
  ApiPublicHooksIngestIntelRoute: typeof ApiPublicHooksIngestIntelRoute
  ApiPublicHooksRefreshIntelligenceRoute: typeof ApiPublicHooksRefreshIntelligenceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/pipeline-horizon': {
      id: '/_authenticated/pipeline-horizon'
      path: '/pipeline-horizon'
      fullPath: '/pipeline-horizon'
      preLoaderRoute: typeof AuthenticatedPipelineHorizonRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pathfinder': {
      id: '/_authenticated/pathfinder'
      path: '/pathfinder'
      fullPath: '/pathfinder'
      preLoaderRoute: typeof AuthenticatedPathfinderRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/olympus': {
      id: '/_authenticated/olympus'
      path: '/olympus'
      fullPath: '/olympus'
      preLoaderRoute: typeof AuthenticatedOlympusRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/intelligence-queue': {
      id: '/_authenticated/intelligence-queue'
      path: '/intelligence-queue'
      fullPath: '/intelligence-queue'
      preLoaderRoute: typeof AuthenticatedIntelligenceQueueRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/intelligence': {
      id: '/_authenticated/intelligence'
      path: '/intelligence'
      fullPath: '/intelligence'
      preLoaderRoute: typeof AuthenticatedIntelligenceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/brief-room': {
      id: '/_authenticated/brief-room'
      path: '/brief-room'
      fullPath: '/brief-room'
      preLoaderRoute: typeof AuthenticatedBriefRoomRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/atrium': {
      id: '/_authenticated/atrium'
      path: '/atrium'
      fullPath: '/atrium'
      preLoaderRoute: typeof AuthenticatedAtriumRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/olympus/': {
      id: '/_authenticated/olympus/'
      path: '/'
      fullPath: '/olympus/'
      preLoaderRoute: typeof AuthenticatedOlympusIndexRouteImport
      parentRoute: typeof AuthenticatedOlympusRoute
    }
    '/_authenticated/profile/expertise': {
      id: '/_authenticated/profile/expertise'
      path: '/profile/expertise'
      fullPath: '/profile/expertise'
      preLoaderRoute: typeof AuthenticatedProfileExpertiseRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/olympus/writer-deletion': {
      id: '/_authenticated/olympus/writer-deletion'
      path: '/writer-deletion'
      fullPath: '/olympus/writer-deletion'
      preLoaderRoute: typeof AuthenticatedOlympusWriterDeletionRouteImport
      parentRoute: typeof AuthenticatedOlympusRoute
    }
    '/_authenticated/olympus/win-themes': {
      id: '/_authenticated/olympus/win-themes'
      path: '/win-themes'
      fullPath: '/olympus/win-themes'
      preLoaderRoute: typeof AuthenticatedOlympusWinThemesRouteImport
      parentRoute: typeof AuthenticatedOlympusRoute
    }
    '/_authenticated/olympus/vault': {
      id: '/_authenticated/olympus/vault'
      path: '/vault'
      fullPath: '/olympus/vault'
      preLoaderRoute: typeof AuthenticatedOlympusVaultRouteImport
      parentRoute: typeof AuthenticatedOlympusRoute
    }
    '/_authenticated/olympus/users': {
      id: '/_authenticated/olympus/users'
      path: '/users'
      fullPath: '/olympus/users'
      preLoaderRoute: typeof AuthenticatedOlympusUsersRouteImport
      parentRoute: typeof AuthenticatedOlympusRoute
    }
    '/_authenticated/olympus/team': {
      id: '/_authenticated/olympus/team'
      path: '/team'
      fullPath: '/olympus/team'
      preLoaderRoute: typeof AuthenticatedOlympusTeamRouteImport
      parentRoute: typeof AuthenticatedOlympusRoute
    }
    '/_authenticated/olympus/source-library': {
      id: '/_authenticated/olympus/source-library'
      path: '/source-library'
      fullPath: '/olympus/source-library'
      preLoaderRoute: typeof AuthenticatedOlympusSourceLibraryRouteImport
      parentRoute: typeof AuthenticatedOlympusRoute
    }
    '/_authenticated/olympus/source-finder': {
      id: '/_authenticated/olympus/source-finder'
      path: '/source-finder'
      fullPath: '/olympus/source-finder'
      preLoaderRoute: typeof AuthenticatedOlympusSourceFinderRouteImport
      parentRoute: typeof AuthenticatedOlympusRoute
    }
    '/_authenticated/olympus/settings': {
      id: '/_authenticated/olympus/settings'
      path: '/settings'
      fullPath: '/olympus/settings'
      preLoaderRoute: typeof AuthenticatedOlympusSettingsRouteImport
      parentRoute: typeof AuthenticatedOlympusRoute
    }
    '/_authenticated/olympus/sensitivities': {
      id: '/_authenticated/olympus/sensitivities'
      path: '/sensitivities'
      fullPath: '/olympus/sensitivities'
      preLoaderRoute: typeof AuthenticatedOlympusSensitivitiesRouteImport
      parentRoute: typeof AuthenticatedOlympusRoute
    }
    '/_authenticated/olympus/score-me': {
      id: '/_authenticated/olympus/score-me'
      path: '/score-me'
      fullPath: '/olympus/score-me'
      preLoaderRoute: typeof AuthenticatedOlympusScoreMeRouteImport
      parentRoute: typeof AuthenticatedOlympusRoute
    }
    '/_authenticated/olympus/review-queue': {
      id: '/_authenticated/olympus/review-queue'
      path: '/review-queue'
      fullPath: '/olympus/review-queue'
      preLoaderRoute: typeof AuthenticatedOlympusReviewQueueRouteImport
      parentRoute: typeof AuthenticatedOlympusRoute
    }
    '/_authenticated/olympus/questions': {
      id: '/_authenticated/olympus/questions'
      path: '/questions'
      fullPath: '/olympus/questions'
      preLoaderRoute: typeof AuthenticatedOlympusQuestionsRouteImport
      parentRoute: typeof AuthenticatedOlympusRoute
    }
    '/_authenticated/olympus/phi-log': {
      id: '/_authenticated/olympus/phi-log'
      path: '/phi-log'
      fullPath: '/olympus/phi-log'
      preLoaderRoute: typeof AuthenticatedOlympusPhiLogRouteImport
      parentRoute: typeof AuthenticatedOlympusRoute
    }
    '/_authenticated/olympus/iris-memory': {
      id: '/_authenticated/olympus/iris-memory'
      path: '/iris-memory'
      fullPath: '/olympus/iris-memory'
      preLoaderRoute: typeof AuthenticatedOlympusIrisMemoryRouteImport
      parentRoute: typeof AuthenticatedOlympusRoute
    }
    '/_authenticated/olympus/invites': {
      id: '/_authenticated/olympus/invites'
      path: '/invites'
      fullPath: '/olympus/invites'
      preLoaderRoute: typeof AuthenticatedOlympusInvitesRouteImport
      parentRoute: typeof AuthenticatedOlympusRoute
    }
    '/_authenticated/olympus/intelligence': {
      id: '/_authenticated/olympus/intelligence'
      path: '/intelligence'
      fullPath: '/olympus/intelligence'
      preLoaderRoute: typeof AuthenticatedOlympusIntelligenceRouteImport
      parentRoute: typeof AuthenticatedOlympusRoute
    }
    '/_authenticated/olympus/gates': {
      id: '/_authenticated/olympus/gates'
      path: '/gates'
      fullPath: '/olympus/gates'
      preLoaderRoute: typeof AuthenticatedOlympusGatesRouteImport
      parentRoute: typeof AuthenticatedOlympusRoute
    }
    '/_authenticated/olympus/expertise': {
      id: '/_authenticated/olympus/expertise'
      path: '/expertise'
      fullPath: '/olympus/expertise'
      preLoaderRoute: typeof AuthenticatedOlympusExpertiseRouteImport
      parentRoute: typeof AuthenticatedOlympusRoute
    }
    '/_authenticated/olympus/discovery-history': {
      id: '/_authenticated/olympus/discovery-history'
      path: '/discovery-history'
      fullPath: '/olympus/discovery-history'
      preLoaderRoute: typeof AuthenticatedOlympusDiscoveryHistoryRouteImport
      parentRoute: typeof AuthenticatedOlympusRoute
    }
    '/_authenticated/olympus/conflicts': {
      id: '/_authenticated/olympus/conflicts'
      path: '/conflicts'
      fullPath: '/olympus/conflicts'
      preLoaderRoute: typeof AuthenticatedOlympusConflictsRouteImport
      parentRoute: typeof AuthenticatedOlympusRoute
    }
    '/_authenticated/olympus/canon-library': {
      id: '/_authenticated/olympus/canon-library'
      path: '/canon-library'
      fullPath: '/olympus/canon-library'
      preLoaderRoute: typeof AuthenticatedOlympusCanonLibraryRouteImport
      parentRoute: typeof AuthenticatedOlympusRoute
    }
    '/_authenticated/olympus/brief-room': {
      id: '/_authenticated/olympus/brief-room'
      path: '/brief-room'
      fullPath: '/olympus/brief-room'
      preLoaderRoute: typeof AuthenticatedOlympusBriefRoomRouteImport
      parentRoute: typeof AuthenticatedOlympusRoute
    }
    '/_authenticated/olympus/audit': {
      id: '/_authenticated/olympus/audit'
      path: '/audit'
      fullPath: '/olympus/audit'
      preLoaderRoute: typeof AuthenticatedOlympusAuditRouteImport
      parentRoute: typeof AuthenticatedOlympusRoute
    }
    '/_authenticated/olympus/atlas-sources': {
      id: '/_authenticated/olympus/atlas-sources'
      path: '/atlas-sources'
      fullPath: '/olympus/atlas-sources'
      preLoaderRoute: typeof AuthenticatedOlympusAtlasSourcesRouteImport
      parentRoute: typeof AuthenticatedOlympusRoute
    }
    '/_authenticated/olympus/admins': {
      id: '/_authenticated/olympus/admins'
      path: '/admins'
      fullPath: '/olympus/admins'
      preLoaderRoute: typeof AuthenticatedOlympusAdminsRouteImport
      parentRoute: typeof AuthenticatedOlympusRoute
    }
    '/_authenticated/missions/$missionId': {
      id: '/_authenticated/missions/$missionId'
      path: '/missions/$missionId'
      fullPath: '/missions/$missionId'
      preLoaderRoute: typeof AuthenticatedMissionsMissionIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/command/security': {
      id: '/_authenticated/command/security'
      path: '/command/security'
      fullPath: '/command/security'
      preLoaderRoute: typeof AuthenticatedCommandSecurityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/command/scores': {
      id: '/_authenticated/command/scores'
      path: '/command/scores'
      fullPath: '/command/scores'
      preLoaderRoute: typeof AuthenticatedCommandScoresRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/command/question-health': {
      id: '/_authenticated/command/question-health'
      path: '/command/question-health'
      fullPath: '/command/question-health'
      preLoaderRoute: typeof AuthenticatedCommandQuestionHealthRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/command/pens-down': {
      id: '/_authenticated/command/pens-down'
      path: '/command/pens-down'
      fullPath: '/command/pens-down'
      preLoaderRoute: typeof AuthenticatedCommandPensDownRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/command/health': {
      id: '/_authenticated/command/health'
      path: '/command/health'
      fullPath: '/command/health'
      preLoaderRoute: typeof AuthenticatedCommandHealthRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/command/broadcasts': {
      id: '/_authenticated/command/broadcasts'
      path: '/command/broadcasts'
      fullPath: '/command/broadcasts'
      preLoaderRoute: typeof AuthenticatedCommandBroadcastsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/command/attention': {
      id: '/_authenticated/command/attention'
      path: '/command/attention'
      fullPath: '/command/attention'
      preLoaderRoute: typeof AuthenticatedCommandAttentionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/command/alignment-conflicts': {
      id: '/_authenticated/command/alignment-conflicts'
      path: '/command/alignment-conflicts'
      fullPath: '/command/alignment-conflicts'
      preLoaderRoute: typeof AuthenticatedCommandAlignmentConflictsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/command/alignment': {
      id: '/_authenticated/command/alignment'
      path: '/command/alignment'
      fullPath: '/command/alignment'
      preLoaderRoute: typeof AuthenticatedCommandAlignmentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/missions/$missionId/': {
      id: '/_authenticated/missions/$missionId/'
      path: '/'
      fullPath: '/missions/$missionId/'
      preLoaderRoute: typeof AuthenticatedMissionsMissionIdIndexRouteImport
      parentRoute: typeof AuthenticatedMissionsMissionIdRoute
    }
    '/api/public/hooks/refresh-intelligence': {
      id: '/api/public/hooks/refresh-intelligence'
      path: '/api/public/hooks/refresh-intelligence'
      fullPath: '/api/public/hooks/refresh-intelligence'
      preLoaderRoute: typeof ApiPublicHooksRefreshIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/ingest-intel': {
      id: '/api/public/hooks/ingest-intel'
      path: '/api/public/hooks/ingest-intel'
      fullPath: '/api/public/hooks/ingest-intel'
      preLoaderRoute: typeof ApiPublicHooksIngestIntelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/backfill-question-embeddings': {
      id: '/api/public/hooks/backfill-question-embeddings'
      path: '/api/public/hooks/backfill-question-embeddings'
      fullPath: '/api/public/hooks/backfill-question-embeddings'
      preLoaderRoute: typeof ApiPublicHooksBackfillQuestionEmbeddingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/backfill-atlas-embeddings': {
      id: '/api/public/hooks/backfill-atlas-embeddings'
      path: '/api/public/hooks/backfill-atlas-embeddings'
      fullPath: '/api/public/hooks/backfill-atlas-embeddings'
      preLoaderRoute: typeof ApiPublicHooksBackfillAtlasEmbeddingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/missions/$missionId/vault': {
      id: '/_authenticated/missions/$missionId/vault'
      path: '/vault'
      fullPath: '/missions/$missionId/vault'
      preLoaderRoute: typeof AuthenticatedMissionsMissionIdVaultRouteImport
      parentRoute: typeof AuthenticatedMissionsMissionIdRoute
    }
    '/_authenticated/missions/$missionId/team': {
      id: '/_authenticated/missions/$missionId/team'
      path: '/team'
      fullPath: '/missions/$missionId/team'
      preLoaderRoute: typeof AuthenticatedMissionsMissionIdTeamRouteImport
      parentRoute: typeof AuthenticatedMissionsMissionIdRoute
    }
    '/_authenticated/missions/$missionId/studio': {
      id: '/_authenticated/missions/$missionId/studio'
      path: '/studio'
      fullPath: '/missions/$missionId/studio'
      preLoaderRoute: typeof AuthenticatedMissionsMissionIdStudioRouteImport
      parentRoute: typeof AuthenticatedMissionsMissionIdRoute
    }
    '/_authenticated/missions/$missionId/settings': {
      id: '/_authenticated/missions/$missionId/settings'
      path: '/settings'
      fullPath: '/missions/$missionId/settings'
      preLoaderRoute: typeof AuthenticatedMissionsMissionIdSettingsRouteImport
      parentRoute: typeof AuthenticatedMissionsMissionIdRoute
    }
    '/_authenticated/missions/$missionId/overview': {
      id: '/_authenticated/missions/$missionId/overview'
      path: '/overview'
      fullPath: '/missions/$missionId/overview'
      preLoaderRoute: typeof AuthenticatedMissionsMissionIdOverviewRouteImport
      parentRoute: typeof AuthenticatedMissionsMissionIdRoute
    }
    '/_authenticated/missions/$missionId/operations': {
      id: '/_authenticated/missions/$missionId/operations'
      path: '/operations'
      fullPath: '/missions/$missionId/operations'
      preLoaderRoute: typeof AuthenticatedMissionsMissionIdOperationsRouteImport
      parentRoute: typeof AuthenticatedMissionsMissionIdRoute
    }
    '/_authenticated/missions/$missionId/library': {
      id: '/_authenticated/missions/$missionId/library'
      path: '/library'
      fullPath: '/missions/$missionId/library'
      preLoaderRoute: typeof AuthenticatedMissionsMissionIdLibraryRouteImport
      parentRoute: typeof AuthenticatedMissionsMissionIdRoute
    }
    '/_authenticated/missions/$missionId/iris': {
      id: '/_authenticated/missions/$missionId/iris'
      path: '/iris'
      fullPath: '/missions/$missionId/iris'
      preLoaderRoute: typeof AuthenticatedMissionsMissionIdIrisRouteImport
      parentRoute: typeof AuthenticatedMissionsMissionIdRoute
    }
    '/_authenticated/missions/$missionId/intelligence': {
      id: '/_authenticated/missions/$missionId/intelligence'
      path: '/intelligence'
      fullPath: '/missions/$missionId/intelligence'
      preLoaderRoute: typeof AuthenticatedMissionsMissionIdIntelligenceRouteImport
      parentRoute: typeof AuthenticatedMissionsMissionIdRoute
    }
    '/_authenticated/missions/$missionId/command': {
      id: '/_authenticated/missions/$missionId/command'
      path: '/command'
      fullPath: '/missions/$missionId/command'
      preLoaderRoute: typeof AuthenticatedMissionsMissionIdCommandRouteImport
      parentRoute: typeof AuthenticatedMissionsMissionIdRoute
    }
    '/_authenticated/missions/$missionId/briefing': {
      id: '/_authenticated/missions/$missionId/briefing'
      path: '/briefing'
      fullPath: '/missions/$missionId/briefing'
      preLoaderRoute: typeof AuthenticatedMissionsMissionIdBriefingRouteImport
      parentRoute: typeof AuthenticatedMissionsMissionIdRoute
    }
    '/_authenticated/missions/$missionId/brief': {
      id: '/_authenticated/missions/$missionId/brief'
      path: '/brief'
      fullPath: '/missions/$missionId/brief'
      preLoaderRoute: typeof AuthenticatedMissionsMissionIdBriefRouteImport
      parentRoute: typeof AuthenticatedMissionsMissionIdRoute
    }
    '/_authenticated/missions/$missionId/activity': {
      id: '/_authenticated/missions/$missionId/activity'
      path: '/activity'
      fullPath: '/missions/$missionId/activity'
      preLoaderRoute: typeof AuthenticatedMissionsMissionIdActivityRouteImport
      parentRoute: typeof AuthenticatedMissionsMissionIdRoute
    }
    '/_authenticated/missions/$missionId/questions/': {
      id: '/_authenticated/missions/$missionId/questions/'
      path: '/questions'
      fullPath: '/missions/$missionId/questions/'
      preLoaderRoute: typeof AuthenticatedMissionsMissionIdQuestionsIndexRouteImport
      parentRoute: typeof AuthenticatedMissionsMissionIdRoute
    }
    '/_authenticated/missions/$missionId/questions/$questionId': {
      id: '/_authenticated/missions/$missionId/questions/$questionId'
      path: '/questions/$questionId'
      fullPath: '/missions/$missionId/questions/$questionId'
      preLoaderRoute: typeof AuthenticatedMissionsMissionIdQuestionsQuestionIdRouteImport
      parentRoute: typeof AuthenticatedMissionsMissionIdRoute
    }
  }
}

interface AuthenticatedOlympusRouteChildren {
  AuthenticatedOlympusAdminsRoute: typeof AuthenticatedOlympusAdminsRoute
  AuthenticatedOlympusAtlasSourcesRoute: typeof AuthenticatedOlympusAtlasSourcesRoute
  AuthenticatedOlympusAuditRoute: typeof AuthenticatedOlympusAuditRoute
  AuthenticatedOlympusBriefRoomRoute: typeof AuthenticatedOlympusBriefRoomRoute
  AuthenticatedOlympusCanonLibraryRoute: typeof AuthenticatedOlympusCanonLibraryRoute
  AuthenticatedOlympusConflictsRoute: typeof AuthenticatedOlympusConflictsRoute
  AuthenticatedOlympusDiscoveryHistoryRoute: typeof AuthenticatedOlympusDiscoveryHistoryRoute
  AuthenticatedOlympusExpertiseRoute: typeof AuthenticatedOlympusExpertiseRoute
  AuthenticatedOlympusGatesRoute: typeof AuthenticatedOlympusGatesRoute
  AuthenticatedOlympusIntelligenceRoute: typeof AuthenticatedOlympusIntelligenceRoute
  AuthenticatedOlympusInvitesRoute: typeof AuthenticatedOlympusInvitesRoute
  AuthenticatedOlympusIrisMemoryRoute: typeof AuthenticatedOlympusIrisMemoryRoute
  AuthenticatedOlympusPhiLogRoute: typeof AuthenticatedOlympusPhiLogRoute
  AuthenticatedOlympusQuestionsRoute: typeof AuthenticatedOlympusQuestionsRoute
  AuthenticatedOlympusReviewQueueRoute: typeof AuthenticatedOlympusReviewQueueRoute
  AuthenticatedOlympusScoreMeRoute: typeof AuthenticatedOlympusScoreMeRoute
  AuthenticatedOlympusSensitivitiesRoute: typeof AuthenticatedOlympusSensitivitiesRoute
  AuthenticatedOlympusSettingsRoute: typeof AuthenticatedOlympusSettingsRoute
  AuthenticatedOlympusSourceFinderRoute: typeof AuthenticatedOlympusSourceFinderRoute
  AuthenticatedOlympusSourceLibraryRoute: typeof AuthenticatedOlympusSourceLibraryRoute
  AuthenticatedOlympusTeamRoute: typeof AuthenticatedOlympusTeamRoute
  AuthenticatedOlympusUsersRoute: typeof AuthenticatedOlympusUsersRoute
  AuthenticatedOlympusVaultRoute: typeof AuthenticatedOlympusVaultRoute
  AuthenticatedOlympusWinThemesRoute: typeof AuthenticatedOlympusWinThemesRoute
  AuthenticatedOlympusWriterDeletionRoute: typeof AuthenticatedOlympusWriterDeletionRoute
  AuthenticatedOlympusIndexRoute: typeof AuthenticatedOlympusIndexRoute
}

const AuthenticatedOlympusRouteChildren: AuthenticatedOlympusRouteChildren = {
  AuthenticatedOlympusAdminsRoute: AuthenticatedOlympusAdminsRoute,
  AuthenticatedOlympusAtlasSourcesRoute: AuthenticatedOlympusAtlasSourcesRoute,
  AuthenticatedOlympusAuditRoute: AuthenticatedOlympusAuditRoute,
  AuthenticatedOlympusBriefRoomRoute: AuthenticatedOlympusBriefRoomRoute,
  AuthenticatedOlympusCanonLibraryRoute: AuthenticatedOlympusCanonLibraryRoute,
  AuthenticatedOlympusConflictsRoute: AuthenticatedOlympusConflictsRoute,
  AuthenticatedOlympusDiscoveryHistoryRoute:
    AuthenticatedOlympusDiscoveryHistoryRoute,
  AuthenticatedOlympusExpertiseRoute: AuthenticatedOlympusExpertiseRoute,
  AuthenticatedOlympusGatesRoute: AuthenticatedOlympusGatesRoute,
  AuthenticatedOlympusIntelligenceRoute: AuthenticatedOlympusIntelligenceRoute,
  AuthenticatedOlympusInvitesRoute: AuthenticatedOlympusInvitesRoute,
  AuthenticatedOlympusIrisMemoryRoute: AuthenticatedOlympusIrisMemoryRoute,
  AuthenticatedOlympusPhiLogRoute: AuthenticatedOlympusPhiLogRoute,
  AuthenticatedOlympusQuestionsRoute: AuthenticatedOlympusQuestionsRoute,
  AuthenticatedOlympusReviewQueueRoute: AuthenticatedOlympusReviewQueueRoute,
  AuthenticatedOlympusScoreMeRoute: AuthenticatedOlympusScoreMeRoute,
  AuthenticatedOlympusSensitivitiesRoute:
    AuthenticatedOlympusSensitivitiesRoute,
  AuthenticatedOlympusSettingsRoute: AuthenticatedOlympusSettingsRoute,
  AuthenticatedOlympusSourceFinderRoute: AuthenticatedOlympusSourceFinderRoute,
  AuthenticatedOlympusSourceLibraryRoute:
    AuthenticatedOlympusSourceLibraryRoute,
  AuthenticatedOlympusTeamRoute: AuthenticatedOlympusTeamRoute,
  AuthenticatedOlympusUsersRoute: AuthenticatedOlympusUsersRoute,
  AuthenticatedOlympusVaultRoute: AuthenticatedOlympusVaultRoute,
  AuthenticatedOlympusWinThemesRoute: AuthenticatedOlympusWinThemesRoute,
  AuthenticatedOlympusWriterDeletionRoute:
    AuthenticatedOlympusWriterDeletionRoute,
  AuthenticatedOlympusIndexRoute: AuthenticatedOlympusIndexRoute,
}

const AuthenticatedOlympusRouteWithChildren =
  AuthenticatedOlympusRoute._addFileChildren(AuthenticatedOlympusRouteChildren)

interface AuthenticatedMissionsMissionIdRouteChildren {
  AuthenticatedMissionsMissionIdActivityRoute: typeof AuthenticatedMissionsMissionIdActivityRoute
  AuthenticatedMissionsMissionIdBriefRoute: typeof AuthenticatedMissionsMissionIdBriefRoute
  AuthenticatedMissionsMissionIdBriefingRoute: typeof AuthenticatedMissionsMissionIdBriefingRoute
  AuthenticatedMissionsMissionIdCommandRoute: typeof AuthenticatedMissionsMissionIdCommandRoute
  AuthenticatedMissionsMissionIdIntelligenceRoute: typeof AuthenticatedMissionsMissionIdIntelligenceRoute
  AuthenticatedMissionsMissionIdIrisRoute: typeof AuthenticatedMissionsMissionIdIrisRoute
  AuthenticatedMissionsMissionIdLibraryRoute: typeof AuthenticatedMissionsMissionIdLibraryRoute
  AuthenticatedMissionsMissionIdOperationsRoute: typeof AuthenticatedMissionsMissionIdOperationsRoute
  AuthenticatedMissionsMissionIdOverviewRoute: typeof AuthenticatedMissionsMissionIdOverviewRoute
  AuthenticatedMissionsMissionIdSettingsRoute: typeof AuthenticatedMissionsMissionIdSettingsRoute
  AuthenticatedMissionsMissionIdStudioRoute: typeof AuthenticatedMissionsMissionIdStudioRoute
  AuthenticatedMissionsMissionIdTeamRoute: typeof AuthenticatedMissionsMissionIdTeamRoute
  AuthenticatedMissionsMissionIdVaultRoute: typeof AuthenticatedMissionsMissionIdVaultRoute
  AuthenticatedMissionsMissionIdIndexRoute: typeof AuthenticatedMissionsMissionIdIndexRoute
  AuthenticatedMissionsMissionIdQuestionsQuestionIdRoute: typeof AuthenticatedMissionsMissionIdQuestionsQuestionIdRoute
  AuthenticatedMissionsMissionIdQuestionsIndexRoute: typeof AuthenticatedMissionsMissionIdQuestionsIndexRoute
}

const AuthenticatedMissionsMissionIdRouteChildren: AuthenticatedMissionsMissionIdRouteChildren =
  {
    AuthenticatedMissionsMissionIdActivityRoute:
      AuthenticatedMissionsMissionIdActivityRoute,
    AuthenticatedMissionsMissionIdBriefRoute:
      AuthenticatedMissionsMissionIdBriefRoute,
    AuthenticatedMissionsMissionIdBriefingRoute:
      AuthenticatedMissionsMissionIdBriefingRoute,
    AuthenticatedMissionsMissionIdCommandRoute:
      AuthenticatedMissionsMissionIdCommandRoute,
    AuthenticatedMissionsMissionIdIntelligenceRoute:
      AuthenticatedMissionsMissionIdIntelligenceRoute,
    AuthenticatedMissionsMissionIdIrisRoute:
      AuthenticatedMissionsMissionIdIrisRoute,
    AuthenticatedMissionsMissionIdLibraryRoute:
      AuthenticatedMissionsMissionIdLibraryRoute,
    AuthenticatedMissionsMissionIdOperationsRoute:
      AuthenticatedMissionsMissionIdOperationsRoute,
    AuthenticatedMissionsMissionIdOverviewRoute:
      AuthenticatedMissionsMissionIdOverviewRoute,
    AuthenticatedMissionsMissionIdSettingsRoute:
      AuthenticatedMissionsMissionIdSettingsRoute,
    AuthenticatedMissionsMissionIdStudioRoute:
      AuthenticatedMissionsMissionIdStudioRoute,
    AuthenticatedMissionsMissionIdTeamRoute:
      AuthenticatedMissionsMissionIdTeamRoute,
    AuthenticatedMissionsMissionIdVaultRoute:
      AuthenticatedMissionsMissionIdVaultRoute,
    AuthenticatedMissionsMissionIdIndexRoute:
      AuthenticatedMissionsMissionIdIndexRoute,
    AuthenticatedMissionsMissionIdQuestionsQuestionIdRoute:
      AuthenticatedMissionsMissionIdQuestionsQuestionIdRoute,
    AuthenticatedMissionsMissionIdQuestionsIndexRoute:
      AuthenticatedMissionsMissionIdQuestionsIndexRoute,
  }

const AuthenticatedMissionsMissionIdRouteWithChildren =
  AuthenticatedMissionsMissionIdRoute._addFileChildren(
    AuthenticatedMissionsMissionIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAtriumRoute: typeof AuthenticatedAtriumRoute
  AuthenticatedBriefRoomRoute: typeof AuthenticatedBriefRoomRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedIntelligenceRoute: typeof AuthenticatedIntelligenceRoute
  AuthenticatedIntelligenceQueueRoute: typeof AuthenticatedIntelligenceQueueRoute
  AuthenticatedOlympusRoute: typeof AuthenticatedOlympusRouteWithChildren
  AuthenticatedPathfinderRoute: typeof AuthenticatedPathfinderRoute
  AuthenticatedPipelineHorizonRoute: typeof AuthenticatedPipelineHorizonRoute
  AuthenticatedCommandAlignmentRoute: typeof AuthenticatedCommandAlignmentRoute
  AuthenticatedCommandAlignmentConflictsRoute: typeof AuthenticatedCommandAlignmentConflictsRoute
  AuthenticatedCommandAttentionRoute: typeof AuthenticatedCommandAttentionRoute
  AuthenticatedCommandBroadcastsRoute: typeof AuthenticatedCommandBroadcastsRoute
  AuthenticatedCommandHealthRoute: typeof AuthenticatedCommandHealthRoute
  AuthenticatedCommandPensDownRoute: typeof AuthenticatedCommandPensDownRoute
  AuthenticatedCommandQuestionHealthRoute: typeof AuthenticatedCommandQuestionHealthRoute
  AuthenticatedCommandScoresRoute: typeof AuthenticatedCommandScoresRoute
  AuthenticatedCommandSecurityRoute: typeof AuthenticatedCommandSecurityRoute
  AuthenticatedMissionsMissionIdRoute: typeof AuthenticatedMissionsMissionIdRouteWithChildren
  AuthenticatedProfileExpertiseRoute: typeof AuthenticatedProfileExpertiseRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAtriumRoute: AuthenticatedAtriumRoute,
  AuthenticatedBriefRoomRoute: AuthenticatedBriefRoomRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedIntelligenceRoute: AuthenticatedIntelligenceRoute,
  AuthenticatedIntelligenceQueueRoute: AuthenticatedIntelligenceQueueRoute,
  AuthenticatedOlympusRoute: AuthenticatedOlympusRouteWithChildren,
  AuthenticatedPathfinderRoute: AuthenticatedPathfinderRoute,
  AuthenticatedPipelineHorizonRoute: AuthenticatedPipelineHorizonRoute,
  AuthenticatedCommandAlignmentRoute: AuthenticatedCommandAlignmentRoute,
  AuthenticatedCommandAlignmentConflictsRoute:
    AuthenticatedCommandAlignmentConflictsRoute,
  AuthenticatedCommandAttentionRoute: AuthenticatedCommandAttentionRoute,
  AuthenticatedCommandBroadcastsRoute: AuthenticatedCommandBroadcastsRoute,
  AuthenticatedCommandHealthRoute: AuthenticatedCommandHealthRoute,
  AuthenticatedCommandPensDownRoute: AuthenticatedCommandPensDownRoute,
  AuthenticatedCommandQuestionHealthRoute:
    AuthenticatedCommandQuestionHealthRoute,
  AuthenticatedCommandScoresRoute: AuthenticatedCommandScoresRoute,
  AuthenticatedCommandSecurityRoute: AuthenticatedCommandSecurityRoute,
  AuthenticatedMissionsMissionIdRoute:
    AuthenticatedMissionsMissionIdRouteWithChildren,
  AuthenticatedProfileExpertiseRoute: AuthenticatedProfileExpertiseRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiPublicHooksBackfillAtlasEmbeddingsRoute:
    ApiPublicHooksBackfillAtlasEmbeddingsRoute,
  ApiPublicHooksBackfillQuestionEmbeddingsRoute:
    ApiPublicHooksBackfillQuestionEmbeddingsRoute,
  ApiPublicHooksIngestIntelRoute: ApiPublicHooksIngestIntelRoute,
  ApiPublicHooksRefreshIntelligenceRoute:
    ApiPublicHooksRefreshIntelligenceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
